# Copyright (c) 2025-2026 TSN Lab, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 3, as published by the Free
# Software Foundation. A proprietary license is also available on request - see README.md.

"""The capacity table one interface package is generated with: TickLE's shipped defaults for the
build's tt_MAX_BUFFER_LENGTH, with the user's own rows on top. Run by the CMake hook at configure
time; the result is what the generator reads (--capacities) and what is installed beside the package
for anything that nests its types (tickle_typesupport/capacities.py explains why it has to travel).

The user's decision of 2026-09-24: TickLE ships per-message capacity defaults and the user can
override them.

Shipped defaults: one profile per tt_MAX_BUFFER_LENGTH, `profile_<N>.tsv` in the shipped directory,
each covering every package TickLE has sized (Plan's inventory of jazzy - a capacity is a fixed C
buffer, so what a datagram can hold decides what a sensible default is). The profile used is the
largest one not above the build's N: at the rmw default 65507, the 65507 profile; at a user's 8192,
the 1472 one, whose types all fit 8192 where the 65507 profile's images would not. Below the
smallest profile, the smallest - some types may then be too large, and rmw_tickle refuses those at
creation with an error naming them.

User overrides: `<package>.capacities` in any directory on TICKLE_CAPACITIES_PATH (like PATH, the
first entries winning), rows in the same format. They are merged row by row over the shipped profile,
so an override lists only what it changes. Every row still has to land - the generator checks the
merged table exactly as it checks a shipped one.
"""

import argparse
import os
import pathlib
import re
import sys

_PROFILE_RE = re.compile(r"^profile_(\d+)\.tsv$")


def choose_profile(shipped_dir, max_buffer_length):
    """The shipped profile file for this N, or None when there are none."""
    profiles = {}
    for entry in pathlib.Path(shipped_dir).iterdir() if pathlib.Path(shipped_dir).is_dir() else ():
        match = _PROFILE_RE.match(entry.name)
        if match:
            profiles[int(match.group(1))] = entry
    if not profiles:
        return None
    fitting = [n for n in profiles if n <= max_buffer_length]
    return profiles[max(fitting) if fitting else min(profiles)]


def _rows(text, package, source, strict):
    """{(interface, field): line} for `package`'s rows, in order, comments dropped. A shipped profile
    covers many packages and is filtered; a user's `<package>.capacities` is strict, because a row
    there for another package is a mistake that filtering would silently hide."""
    rows = {}
    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        cols = line.split()
        if len(cols) >= 2 and cols[0].startswith(package + "/"):
            rows[(cols[0], cols[1])] = raw.strip()
        elif strict:
            raise ValueError(f"{source}:{number}: '{line}' is not a {package} row - this file is {package}'s")
    return rows


def user_files(package, search_path):
    """The user's override files for `package`, highest priority LAST (merge order)."""
    found = []
    for directory in (search_path or "").split(os.pathsep):
        if directory:
            candidate = pathlib.Path(directory) / f"{package}.capacities"
            if candidate.is_file():
                found.append(candidate)
    return list(reversed(found))  # the first PATH entry wins, so it is merged last


def effective_table(package, max_buffer_length, shipped_dir, search_path):
    """(text, sources): the merged rows for `package`, and the files they came from."""
    sources = []
    rows = {}
    profile = choose_profile(shipped_dir, max_buffer_length)
    if profile is not None:
        shipped = _rows(profile.read_text(encoding="utf-8"), package, profile, strict=False)
        if shipped:
            rows.update(shipped)
            sources.append(profile)
    for path in user_files(package, search_path):
        rows.update(_rows(path.read_text(encoding="utf-8"), package, path, strict=True))
        sources.append(path)
    header = [
        f"# Effective capacities for {package} at tt_MAX_BUFFER_LENGTH {max_buffer_length}.",
        "# Generated by rosidl_typesupport_tickle_c.capacity_profile from, in merge order:",
    ] + [f"#   {s}" for s in sources] + ["#   (nothing - no shipped rows and no user overrides)"] * (not sources)
    return "\n".join(header + list(rows.values())) + "\n", sources


def main(argv=None):
    parser = argparse.ArgumentParser(prog="capacity_profile")
    parser.add_argument("--package", required=True)
    parser.add_argument("--max-buffer-length", type=int, required=True)
    parser.add_argument("--shipped-dir", required=True)
    parser.add_argument("--search-path", default=os.environ.get("TICKLE_CAPACITIES_PATH", ""))
    parser.add_argument("--out", required=True)
    parser.add_argument("--depends-out", help="write the files consulted, one per line (CMAKE_CONFIGURE_DEPENDS)")
    args = parser.parse_args(argv)

    text, sources = effective_table(args.package, args.max_buffer_length, args.shipped_dir, args.search_path)
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    # Only rewritten when it changed: it is a generator DEPENDS, and touching it would regenerate
    # every interface of the package on every configure.
    if not out.is_file() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
    if args.depends_out:
        pathlib.Path(args.depends_out).write_text("".join(f"{s}\n" for s in sources), encoding="utf-8")
    rows = sum(1 for line in text.splitlines() if line and not line.startswith("#"))
    print(f"{args.package}: {rows} capacity rows from {', '.join(str(s) for s in sources) or 'nowhere'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
