# Copyright (c) 2025-2026 TSN Lab, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 3, as published by the Free
# Software Foundation. A proprietary license is also available on request - see README.md.

"""Entry point `python3 -m rosidl_typesupport_tickle_c.ros2_cli`, invoked once per .msg/.srv by rosidl_
typesupport_tickle_c's own CMake extension (rmw_tickle/rosidl_typesupport_tickle_c/cmake/
rosidl_typesupport_tickle_c_generate_interfaces.cmake, registered into `rosidl_generate_
interfaces()`'s `rosidl_generate_idl_interfaces` extension point - rmw_tickle/PLAN.md's Milestone
1(c)) during a *real* ROS 2 `colcon build` - NOT the `tickle-typesupport` console script (cli.py),
which targets tools/typesupport's own codegen pipeline for TickLE's own examples/ and has no
notion of ROS 2 at all.

For one <package>/msg/<name>.msg, writes into --outdir:
  <name>.h / <name>.c                                              - TickLE's own codec (cli.py's
                                                                      generate_interface() output,
                                                                      unchanged - just invoked
                                                                      programmatically here)
  <package>__msg__<name>__rosidl_typesupport_tickle_c.h/.c         - the ROS 2 <-> TickLE struct
                                                                      converter (ros2_adapter.
                                                                      render_adapter())
  <package>__msg__<name>__type_support.c                          - the rosidl_message_type_
                                                                      support_t wrapper that makes
                                                                      the above actually reachable
                                                                      from a real rmw_create_
                                                                      publisher() call (ros2_adapter.
                                                                      render_type_support() - see its
                                                                      own docstring for why this step
                                                                      is mandatory, not optional)

For one <package>/srv/<name>.srv, writes the same three files *twice* - once for
<package>__srv__<name>_Request, once for <package>__srv__<name>_Response (a .srv's request/
response are each ordinary ROS 2 messages in their own right, generated by rosidl_generator_c the
same way any other message is - just sharing one <name>.h/.c pair, rendered by render.
render_service() instead of render.render_topic()) - plus one more:
  <package>__srv__<name>__type_support.c    - the rosidl_service_type_support_t wrapper
                                               (ros2_adapter.render_service_type_support()),
                                               tying the request/response message handles above
                                               together into the one handle rmw_create_client()/
                                               rmw_create_service() actually receive

Rejects (SystemExit) anything else (subfolders other than msg/srv, e.g. action). A nested message
field is resolved via ros2_resolve.Ros2Resolver - see its own doc comment for why that's a genuinely
different resolver than cli.py's own -I/tickle_typesupport.builtins-based one, not just a thin
wrapper: every message a real ROS 2 package's own nested field could reference is *also*
independently generated as its own top-level interface by this exact same extension (either a
sibling .msg in this same package - the common case, and the only one this CLI can find without
an explicit -I - or another package's, if it too builds rosidl_typesupport_tickle_c and is found
on a caller-supplied -I path), so Ros2Resolver reuses that already-generated struct/codec instead
of writing (and linking) a second, differently-named copy. Only TickLE's own two small bundled
builtins (std_msgs/Header, builtin_interfaces/Time) still need - and get - their own freshly
generated <pkg>__<Name>.h/.c pair, written out here the same way cli.py's own loop does it.
"""

import argparse
import os
import sys

from tickle_typesupport import _rosidl_parser as rosidl
from tickle_typesupport import adapt, cli, model, postprocess, render
from tickle_typesupport import capacities as capacity_file

from . import ros2_adapter, ros2_cpp_adapter, ros2_resolve


def _write_text(outdir, filename, text, source_label, fmt_dir):
    path = os.path.join(outdir, filename)
    formatted = postprocess.clang_format(postprocess.add_banner(text, source_label), style_dir=fmt_dir, filename=filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(formatted)
    return path


def _generate_message_typesupport(struct, ros_name, tickle_header, source_label, outdir, fmt_dir):
    """The adapter + type-support-wrapper pair every ROS 2 message needs - shared between a plain
    .msg (called once) and a .srv's request/response structs (called once each, see generate()
    below) - both are ordinary ROS 2 messages as far as rosidl_typesupport_tickle_c is concerned.
    Returns the list of file paths written."""
    written = []
    adapter_header_name = f"{ros_name}__rosidl_typesupport_tickle_c.h"
    adapter_source_name = f"{ros_name}__rosidl_typesupport_tickle_c.c"
    adapter_header, adapter_source = ros2_adapter.render_adapter(struct, ros_name, tickle_header)
    written.append(_write_text(outdir, adapter_header_name, adapter_header, source_label, fmt_dir))
    written.append(_write_text(outdir, adapter_source_name, adapter_source, source_label, fmt_dir))

    type_support_name = f"{ros_name}__type_support.c"
    type_support_source = ros2_adapter.render_type_support(struct, ros_name, tickle_header, adapter_header_name)
    written.append(_write_text(outdir, type_support_name, type_support_source, source_label, fmt_dir))

    # The C++ converters rclcpp's messages need (ros2_cpp_adapter.py). Written here, from the same
    # struct, rather than by rosidl_typesupport_tickle_cpp's own extension, so the two sides cannot
    # disagree on the layout; that extension compiles them.
    cpp_header, cpp_source = ros2_cpp_adapter.render_cpp_adapter(struct, ros_name, tickle_header)
    written.append(_write_text(outdir, f"{ros_name}__rosidl_typesupport_tickle_cpp.hpp", cpp_header, source_label, fmt_dir))
    written.append(_write_text(outdir, f"{ros_name}__rosidl_typesupport_tickle_cpp.cpp", cpp_source, source_label, fmt_dir))
    return written


def _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir):
    """ros2_resolve.Ros2Resolver's own in_discovery_order() only ever reports TickLE's two small
    bundled builtins (std_msgs/Header, builtin_interfaces/Time) - everything else it resolves
    reuses an already-independently-generated sibling .msg's own file instead of writing a new
    one (see its own doc comment). Same render_nested() call cli.py's own identical loop makes."""
    written = []
    for _pkg_name, _msg_name, nested_struct in resolver.in_discovery_order():
        nested_header, nested_source = render.render_nested(nested_struct)
        written += cli._write_generated(nested_struct.c_name, nested_header, nested_source, source_label, outdir, fmt_dir)
    return written


# The implicit interfaces rosidl derives from a .action, and that its type support dispatch asks
# every typesupport for (rosidl_typesupport_c's action__type_support.c.em): four messages and two
# services, all under the "action" subfolder.
ACTION_MESSAGES = ("Goal", "Result", "Feedback", "FeedbackMessage")
ACTION_SERVICES = ("SendGoal", "GetResult")
# Bytes an action's Goal/Result/Feedback leave free when their capacities are auto-derived, for the
# wrapper each is also sent inside: a 16-byte goal id (SendGoal request, FeedbackMessage) or an
# int8 status (GetResult response), plus alignment. Generous rather than exact - a few bytes of one
# array's capacity, against a wrapper that could never be sent.
ACTION_WRAPPER_RESERVE = 64


def _interfaces_of(subfolder, name):
    """(messages, services) generated for one .msg/.srv/.action, by type name."""
    if subfolder == "msg":
        return [name], []
    if subfolder == "srv":
        return [], [name]
    return [f"{name}_{m}" for m in ACTION_MESSAGES], [f"{name}_{s}" for s in ACTION_SERVICES]


def _interface_files(package, subfolder, name):
    """(every file generate() writes for this interface, the ROS names of its messages).

    rosidl_typesupport_tickle_c_generate_interfaces.cmake declares the same set by the same rule,
    and must: a file CMake expects and the generator does not write fails the build. Per message
    M: TickLE's codec M.{h,c} (a .srv's own is "<name>_srv"), the C adapter, its type support, and
    the C++ converters. Per service: the codec, both halves' adapters and C++ converters, and the
    service-level type support."""
    messages, services = _interfaces_of(subfolder, name)
    filenames = []
    message_names = []

    def message_files(ros_name):
        message_names.append(ros_name)
        return [
            f"{ros_name}__rosidl_typesupport_tickle_c.h",
            f"{ros_name}__rosidl_typesupport_tickle_c.c",
            f"{ros_name}__type_support.c",
            f"{ros_name}__rosidl_typesupport_tickle_cpp.hpp",
            f"{ros_name}__rosidl_typesupport_tickle_cpp.cpp",
        ]

    for message in messages:
        filenames += [f"{message}.h", f"{message}.c"] + message_files(f"{package}__{subfolder}__{message}")
    for service in services:
        ros_service_name = f"{package}__{subfolder}__{service}"
        filenames += [f"{service}_srv.h", f"{service}_srv.c", f"{ros_service_name}__type_support.c"]
        for part in ("Request", "Response"):
            filenames += message_files(f"{ros_service_name}_{part}")
    return filenames, message_names


def _decline(package, subfolder, name, outdir, source_label, fmt_dir, reason):
    """Writes the files CMake expects for a message TickLE cannot generate, carrying the reason.

    The files have to exist: rosidl_typesupport_tickle_c_generate_interfaces.cmake declares each
    one by name in an add_custom_command, so a missing output fails the build exactly as hard as
    a broken one. What they must not do is define anything - no struct, no codec, and above all no
    get_message_type_support_handle symbol, so rosidl's own lookup finds nothing and
    rmw_create_publisher refuses the topic with a clear error instead of accepting it and failing
    later.

    The reason goes in the file rather than only in build output, because build output scrolls
    past and the generated header is what somebody opens when they want to know why their message
    does not work.
    """
    filenames, message_names = _interface_files(package, subfolder, name)
    ros_name = f"{package}__{subfolder}__{name}"
    banner = (
        f"// TickLE has no typesupport for {package}/{subfolder}/{name}.\n"
        f"//\n"
        f"// {reason}\n"
        f"//\n"
        f"// This file is deliberately empty of declarations. Nothing is registered, so\n"
        f"// rmw_create_publisher()/rmw_create_subscription() on this type fails with a clear\n"
        f"// error rather than succeeding and breaking later. Every other type in this package is\n"
        f"// unaffected - declining one type must not fail a build for consumers that never use\n"
        f"// it, which is the whole reason this is a stub and not a compile error.\n"
    )
    # A typedef rather than nothing at all: an empty translation unit is not valid ISO C.
    marker = f"typedef int {ros_name}__tickle_unsupported_t;\n"
    # A C++ header says so in a form rosidl_typesupport_tickle_cpp's type support wrapper can test:
    # it then hands rclcpp no handle at all, instead of one that calls C converters which were
    # never generated.
    cpp_headers = {f"{m}__rosidl_typesupport_tickle_cpp.hpp": m for m in message_names}
    written = []
    for filename in filenames:
        body = f"#define {cpp_headers[filename]}__TICKLE_UNSUPPORTED 1\n" if filename in cpp_headers else marker
        written.append(_write_text(outdir, filename, banner + body, source_label, fmt_dir))
    print(f"{source_label}: DECLINED - {reason}", file=sys.stderr)
    return written


def _nested_package_reason(unsupported):
    return (
        f"It nests {unsupported.pkg_name}/{unsupported.msg_name}, and {unsupported.pkg_name} does not "
        f"build rosidl_typesupport_tickle_c. This applies even to a type TickLE bundles a definition "
        f"for, such as std_msgs/Header: having the struct is not the same as being able to adapt it, "
        f"because the generated ROS adapter needs {unsupported.pkg_name}'s own "
        f"...__rosidl_typesupport_tickle_c.h to convert the ROS C struct into the TickLE one, and that "
        f"header exists only if {unsupported.pkg_name} builds this typesupport itself. "
        f"This is NOT a size limit - see <Name>_FITS_ONE_DATAGRAM for that, which is a different problem "
        f"with a different fix. The remedy here is to build {unsupported.pkg_name} from source in this "
        f"workspace with the TickLE typesupport extension applied, the way std_msgs ships FastDDS "
        f"typesupport of its own."
    )


def _field_reason(error):
    # A field TickLE cannot represent (a wstring, an unbounded field whose capacity cannot be
    # derived, ...). Declined rather than failed, for the same reason as a nested package: one such
    # type in a package must not stop every other type in it from building. A capacity-file row
    # that does not apply is NOT this - capacities.CapacityError is not caught, and fails the build.
    return (
        f"{error} The capacity file for this package is where an unbounded field gets its size "
        f"(tools/typesupport/tickle_typesupport/capacities.py); a field that no capacity can fix, such as "
        f"a wstring, keeps the type unsupported."
    )


def _action_texts(name, text):
    """The .msg/.srv text of each implicit interface rosidl derives from an action: its own goal,
    result and feedback, and the wrappers rcl_action sends them in (rosidl_parser's action
    definition - the same fields, names and order rosidl_generator_c gives the ROS structs, which
    the adapters convert field by field). Split on the separator exactly as the vendored
    parse_action_string() does, which is called first to reject a malformed file."""
    lines = text.splitlines()
    separators = [i for i, line in enumerate(lines) if line == rosidl.ACTION_REQUEST_RESPONSE_SEPARATOR]
    goal = "\n".join(lines[: separators[0]]) + "\n"
    result = "\n".join(lines[separators[0] + 1 : separators[1]]) + "\n"
    feedback = "\n".join(lines[separators[1] + 1 :]) + "\n"
    messages = {
        f"{name}_Goal": goal,
        f"{name}_Result": result,
        f"{name}_Feedback": feedback,
        f"{name}_FeedbackMessage": f"unique_identifier_msgs/UUID goal_id\n{name}_Feedback feedback\n",
    }
    services = {
        f"{name}_SendGoal": (
            f"unique_identifier_msgs/UUID goal_id\n{name}_Goal goal\n---\nbool accepted\nbuiltin_interfaces/Time stamp\n"
        ),
        f"{name}_GetResult": f"unique_identifier_msgs/UUID goal_id\n---\nint8 status\n{name}_Result result\n",
    }
    return messages, services


def _generate_action(package, name, text, resolver, table, source_label, outdir, fmt_dir):
    """A .action: its four implicit messages and two implicit services, each generated as an
    ordinary message or service under the "action" subfolder. rmw needs nothing more - there is no
    action API in rmw; rcl_action builds an action from these services and topics, and
    rosidl_typesupport_c assembles the action type support from the dispatch symbols this emits.
    Declined as a whole if any part cannot be represented: half an action is no action."""
    rosidl.parse_action_string(package, name, text)
    messages, services = _action_texts(name, text)
    for message_name, message_text in messages.items():
        # The wrappers nest the action's own messages; these are where the resolver finds them.
        resolver.add_action_local(message_name, message_text)
    try:
        # Every place an action's message is adapted - top level here, nested inside a wrapper by
        # the resolver - is inside this block, so they agree on its capacities.
        with model.reserving_for_wrapper(ACTION_WRAPPER_RESERVE):
            message_irs = [
                (
                    message_name,
                    adapt.adapt_message(
                        message_name,
                        rosidl.parse_message_string(package, message_name, message_text),
                        resolver,
                        capacity_file.for_message(table, message_name, "action"),
                    ),
                )
                for message_name, message_text in messages.items()
            ]
            service_irs = []
            for service_name, service_text in services.items():
                spec = rosidl.parse_service_string(package, service_name, service_text)
                request_capacities, response_capacities = capacity_file.for_service(
                    table, service_name, {f.name for f in spec.request.fields}, {f.name for f in spec.response.fields}
                )
                service_irs.append(
                    (
                        service_name,
                        adapt.adapt_service(f"{service_name}_srv", spec, resolver, request_capacities, response_capacities),
                    )
                )
    except ros2_resolve.UnsupportedNestedPackage as unsupported:
        return _decline(package, "action", name, outdir, source_label, fmt_dir, _nested_package_reason(unsupported))
    except adapt.UnsupportedFieldError as error:
        return _decline(package, "action", name, outdir, source_label, fmt_dir, _field_reason(error))

    written = []
    for message_name, ir in message_irs:
        header, source = render.render_topic(ir)
        written += cli._write_generated(message_name, header, source, source_label, outdir, fmt_dir)
        written += _generate_message_typesupport(
            ir.data, f"{package}__action__{message_name}", f"{message_name}.h", source_label, outdir, fmt_dir
        )
    for service_name, ir in service_irs:
        header, source = render.render_service(ir)
        written += cli._write_generated(f"{service_name}_srv", header, source, source_label, outdir, fmt_dir)
        ros_service_name = f"{package}__action__{service_name}"
        for part, struct in (("Request", ir.request), ("Response", ir.response)):
            written += _generate_message_typesupport(
                struct, f"{ros_service_name}_{part}", f"{service_name}_srv.h", source_label, outdir, fmt_dir
            )
        written.append(
            _write_text(
                outdir,
                f"{ros_service_name}__type_support.c",
                ros2_adapter.render_service_type_support(ros_service_name),
                source_label,
                fmt_dir,
            )
        )
    written += _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir)
    return written


def generate(package, subfolder, name, input_path, outdir, *, style_dir=None, include_dirs=(),
             typesupport_packages=(), capacities_path=None):
    """Returns the list of file paths written - same "top-level interface first" convention as
    cli.generate_interface().

    capacities_path: this package's capacity file (capacities.py), or None. Every row is checked
    against the package on every run, not only the rows for this interface."""
    os.makedirs(outdir, exist_ok=True)
    fmt_dir = style_dir or outdir
    source_label = os.path.basename(input_path)
    text = open(input_path, encoding="utf-8").read()
    tickle_header = f"{name}.h"
    # A nested field's own type is looked for in this package's own msg/ dir first (ros2_resolve.
    # Ros2Resolver's own "same-package sibling" case - see its doc comment) - a *nested* field is
    # always some other .msg, never a .srv (ROS 2's own grammar doesn't allow a .srv to nest another
    # .srv), so this is msg/ regardless of whether --input itself is a .msg or a .srv: for a .msg,
    # os.path.dirname(input_path) already *is* <pkg>/msg, so going up one more level and back down
    # into "msg" is a no-op; for a .srv, plain os.path.dirname(input_path) would give <pkg>/srv
    # instead - the real bug this sidesteps (found via rcl_interfaces' own SetParameters.srv, which
    # nests msg/Parameter - a same-package sibling *lookup that used to look in the wrong
    # directory and silently fall through to a stale copy on the -I search path instead, e.g. an
    # apt-installed rcl_interfaces missing rcl_interfaces_rmw_tickle.patch's own `# @capacity`
    # annotations - see rosidl_typesupport_tickle_c_generate_interfaces.cmake's own former .srv
    # skip, removed together with this fix).
    package_root = os.path.dirname(os.path.dirname(input_path))
    table = {}
    if capacities_path:
        table = capacity_file.load(capacities_path, package)
        capacity_file.check_types_exist(table, package_root)
    resolver = ros2_resolve.Ros2Resolver(package, os.path.join(package_root, "msg"), include_dirs,
                                    typesupport_packages, table)

    if subfolder == "msg":
        spec = rosidl.parse_message_string(package, name, text)
        try:
            ir = adapt.adapt_message(name, spec, resolver, capacity_file.for_message(table, name))
        except ros2_resolve.UnsupportedNestedPackage as unsupported:
            return _decline(package, subfolder, name, outdir, source_label, fmt_dir, _nested_package_reason(unsupported))
        except adapt.UnsupportedFieldError as error:
            return _decline(package, subfolder, name, outdir, source_label, fmt_dir, _field_reason(error))
        header, source = render.render_topic(ir)
        written = list(cli._write_generated(name, header, source, source_label, outdir, fmt_dir))
        ros_name = f"{package}__msg__{name}"
        written += _generate_message_typesupport(ir.data, ros_name, tickle_header, source_label, outdir, fmt_dir)
        written += _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir)
        return written

    if subfolder == "srv":
        # Milestone 55/56 - a same-package .msg and .srv can share one base name (real, found via
        # test_msgs' own BasicTypes.msg + BasicTypes.srv): both would otherwise write a bare
        # "<name>.h/.c" into their own msg/srv output subdirectory, and since a real CMake build
        # puts *both* directories on one compile unit's own -I list simultaneously, the C
        # preprocessor's own same-directory-first quoted-include search silently picks whichever
        # one lives in *this* file's own directory - wrong whenever a .srv needs the .msg's own
        # struct (Arrays.srv nesting the real BasicTypes message, say), a hard "incomplete element
        # type" compile error, not a warning. A .srv's own file, unlike a .msg's, is never a valid
        # *nested-field* target (ROS 2's grammar has no way to nest a .srv inside anything), so
        # nothing outside this one function ever looks a .srv's own TickLE-side name up again the
        # way ros2_resolve.Ros2Resolver does for a .msg - safe to qualify only this side, leaving every
        # .msg's own existing bare "<name>.h/.c" convention (and ros2_resolve.Ros2Resolver's own
        # matching "{msg_name}.h" computation) completely untouched.
        srv_tickle_name = f"{name}_srv"
        spec = rosidl.parse_service_string(package, name, text)
        request_capacities, response_capacities = capacity_file.for_service(
            table, name, {f.name for f in spec.request.fields}, {f.name for f in spec.response.fields}
        )
        try:
            ir = adapt.adapt_service(srv_tickle_name, spec, resolver, request_capacities, response_capacities)
        except ros2_resolve.UnsupportedNestedPackage as unsupported:
            return _decline(package, subfolder, name, outdir, source_label, fmt_dir, _nested_package_reason(unsupported))
        except adapt.UnsupportedFieldError as error:
            return _decline(package, subfolder, name, outdir, source_label, fmt_dir, _field_reason(error))
        header, source = render.render_service(ir)
        written = list(cli._write_generated(srv_tickle_name, header, source, source_label, outdir, fmt_dir))
        srv_tickle_header = f"{srv_tickle_name}.h"
        ros_service_name = f"{package}__srv__{name}"
        written += _generate_message_typesupport(
            ir.request, f"{ros_service_name}_Request", srv_tickle_header, source_label, outdir, fmt_dir
        )
        written += _generate_message_typesupport(
            ir.response, f"{ros_service_name}_Response", srv_tickle_header, source_label, outdir, fmt_dir
        )
        service_type_support_source = ros2_adapter.render_service_type_support(ros_service_name)
        written.append(
            _write_text(outdir, f"{ros_service_name}__type_support.c", service_type_support_source, source_label, fmt_dir)
        )
        written += _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir)
        return written

    if subfolder == "action":
        return _generate_action(package, name, text, resolver, table, source_label, outdir, fmt_dir)

    raise SystemExit(f"{input_path}: rosidl_typesupport_tickle_c only supports .msg/.srv/.action, not .{subfolder}")


def main(argv=None):
    parser = argparse.ArgumentParser(prog="tickle-typesupport-ros2")
    parser.add_argument("--package", required=True)
    parser.add_argument("--subfolder", required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--input", required=True, metavar="FILE.msg|FILE.srv")
    parser.add_argument("--outdir", required=True)
    parser.add_argument("--style-dir")
    parser.add_argument(
        "-I",
        "--include-dir",
        action="append",
        default=[],
        metavar="DIR",
        help="search DIR/<pkg>/msg/<Name>.msg to resolve a *cross-package* nested message field "
        "(repeatable) - a same-package sibling is always found automatically, no -I needed; "
        "builtin_interfaces/Time and std_msgs/Header are always available even without one - see "
        "ros2_resolve.Ros2Resolver/tickle_typesupport.builtins. The real CMake extension "
        "(rosidl_typesupport_tickle_c_generate_interfaces.cmake) passes one of these per "
        "dependency package (each one's own share root, computed from that package's own "
        "find_package()-set _DIR variable) - see rmw_tickle/PLAN.md's own Milestone for this.",
    )
    parser.add_argument(
        "--typesupport-package",
        action="append",
        default=[],
        metavar="PKG",
        help="PKG builds TickLE typesupport of its own, so a nested field from it can be resolved "
        "(repeatable). Without this, a cross-package nested type is DECLINED, because nothing "
        "visible here distinguishes a package that generated its own TickLE struct and ROS adapter "
        "from one that merely has a .msg on the -I search path - std_msgs has the .msg and neither "
        "of the rest. The CMake extension determines it by looking for that package's exported "
        "<pkg>::<pkg>__rosidl_typesupport_tickle_c target, which only exists if it ran this "
        "extension.",
    )
    parser.add_argument(
        "--capacities",
        metavar="FILE",
        help="this package's capacity file: '<pkg>/<msg|srv>/<Type> <field> <N>' rows sizing its "
        "unbounded arrays and plain strings, outranking in-.msg @capacity annotations. Every row "
        "must apply, or generation fails - see tickle_typesupport/capacities.py.",
    )
    parser.add_argument(
        "--max-buffer-length",
        type=int,
        default=model.TT_MAX_BUFFER_LENGTH,
        metavar="N",
        help="the tt_MAX_BUFFER_LENGTH the generated code will be built with (default %(default)s, core's). "
        "Auto-derived capacities fill a datagram of this size, so it must match the build's.",
    )
    args = parser.parse_args(argv)
    model.set_max_buffer_length(args.max_buffer_length)

    written = generate(
        args.package,
        args.subfolder,
        args.name,
        args.input,
        args.outdir,
        style_dir=args.style_dir,
        include_dirs=args.include_dir,
        typesupport_packages=args.typesupport_package,
        capacities_path=args.capacities,
    )
    print(f"{args.input} -> {', '.join(written)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
