#!/usr/bin/env bash
# clang-tidy for examples/perf_hil/fastdds, which `make check-gates` does not cover.
#
# WHY THIS EXISTS. platform/linux/Makefile says it in its own comment: the lint gate's clang-tidy
# skips two trees that clang-format still covers, and this is one of them - while CI's cpp-linter
# lints it. So a green `make check-gates` says nothing about clang-tidy here, and on 2026-10-04 a
# one-letter variable name (readability-identifier-length wants three) reddened main for 44
# minutes after a gate run that was green and had no way not to be.
#
# It is not wired into check-gates, on purpose. It needs a Fast DDS 2.14 header tree that this
# host does not have - /opt/ros here is Fast DDS 3.x, different namespaces - so it fetches and
# builds one under $CACHE. A gate that depends on a /tmp tree would pass silently after a reboot
# removed it, which is worse than a gate that is not there: the same reason find_blind_harnesses.sh
# is not a gate either. Run it by hand before touching this tree, or point CACHE somewhere durable.
#
# WHAT MAKES IT TRUSTWORTHY, AND WHAT DOES NOT. Hand-written stubs were tried for this once and
# were wrong in a way that mattered - include-cleaner judged ReturnCode_t by where the stub
# declared it, while real 2.14 brings it in through a using-declaration. So this builds the real
# upstream headers. It was then validated against a finding CI had actually produced, in both
# directions and over the whole tree:
#
#   with the one-letter name restored, one finding, and it is CI's message, file and line:
#     harness_common.hpp:187:21: warning: variable name 'v' is too short ... [readability-identifier-length]
#   with the name fixed, zero findings across all 18 sources - which is what CI said about the
#   same tree.
#
# THE HEADER FILTER IS THE WHOLE DIFFICULTY, and getting it wrong is not subtle in its effect, only
# in its appearance. A first version filtered on 'examples/perf_hil/fastdds', which matches the
# PATH STRING of ../../tickle/common/BenchStats.h as included from here, and reported 1582 findings
# where CI reported 1 - magic numbers and C-style arrays in a shared header that CI does not flag
# in this context. It had been "validated" by a control narrowed to harness_common, and a control
# that narrow only ever licensed a claim that narrow. If you widen HEADER_FILTER, re-run the pair
# above before believing the result; a setup that cannot reproduce a known finding, or that
# reproduces a thousand CI never mentions, is not a check.
#
# Usage:  .github/scripts/fastdds_lint.sh [file.cpp ...]   (default: every .cpp in the tree)
#         CACHE=/path  to keep the header tree somewhere that survives a reboot
#         HEADER_FILTER=<regex>  which headers to report findings in (default: the harness's own)
# Exit:   1 if clang-tidy reported anything, 0 if not. Nothing is modified.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CACHE="${CACHE:-/tmp/fddslint}"
FDDS_VER=2.14.7 # the rpis' version; build.sh's own comment explains why 3.x is not interchangeable
FCDR_VER=2.2.8
TIDY="${CLANG_TIDY:-}"
for candidate in "$(command -v clang-tidy-19 || true)" /tmp/lintenv/bin/clang-tidy; do
    [ -z "$TIDY" ] && [ -x "$candidate" ] && TIDY="$candidate"
done
if [ -z "$TIDY" ]; then
    echo "fastdds_lint: no clang-tidy 19 (set CLANG_TIDY=, or build /tmp/lintenv as check_gates.sh describes)" >&2
    exit 2
fi

build_tree() {
    echo "fastdds_lint: building the Fast DDS $FDDS_VER header tree under $CACHE (one-off, a few minutes)"
    rm -rf "$CACHE"
    mkdir -p "$CACHE" || return 1
    curl -sSL -o "$CACHE/fdds.tar.gz" \
        "https://codeload.github.com/eProsima/Fast-DDS/tar.gz/refs/tags/v$FDDS_VER" || return 1
    curl -sSL -o "$CACHE/fcdr.tar.gz" \
        "https://codeload.github.com/eProsima/Fast-CDR/tar.gz/refs/tags/v$FCDR_VER" || return 1
    tar xzf "$CACHE/fdds.tar.gz" -C "$CACHE" || return 1
    tar xzf "$CACHE/fcdr.tar.gz" -C "$CACHE" || return 1
    mkdir -p "$CACHE/inc" "$CACHE/gen"
    cp -r "$CACHE/Fast-DDS-$FDDS_VER/include/." "$CACHE/inc/" || return 1
    cp -r "$CACHE/Fast-CDR-$FCDR_VER/include/." "$CACHE/inc/" || return 1

    # config.h is generated by cmake at build time; these are the values a default Linux build of
    # 2.14 produces. Only the ones the headers actually branch on matter for a parse.
    sed -e 's/@PROJECT_VERSION_MAJOR@/2/; s/@PROJECT_VERSION_MINOR@/14/; s/@PROJECT_VERSION_PATCH@/7/' \
        -e "s/@PROJECT_VERSION@/$FDDS_VER/" \
        -e 's/@HAVE_CXX20@/0/; s/@HAVE_CXX17@/1/; s/@HAVE_CXX14@/1/; s/@HAVE_CXX1Y@/1/; s/@HAVE_CXX11@/1/' \
        -e 's/@FASTDDS_IS_BIG_ENDIAN_TARGET@/0/; s/@HAVE_SECURITY@/0/; s/@HAVE_SQLITE3@/0/; s/@TLS_FOUND@/0/' \
        -e 's/@HAVE_STRICT_REALTIME@/0/; s/@ENABLE_OLD_LOG_MACROS_@/1/; s/@HAVE_LOG_NO_INFO@/1/' \
        -e 's/@HAVE_LOG_NO_WARNING@/0/; s/@HAVE_LOG_NO_ERROR@/0/' \
        -e 's|^#cmakedefine01 USE_THIRDPARTY_SHARED_MUTEX|#define USE_THIRDPARTY_SHARED_MUTEX 0|' \
        -e 's|^#cmakedefine FASTDDS_ENFORCE_LOG_INFO|// FASTDDS_ENFORCE_LOG_INFO off|' \
        -e 's|^#cmakedefine FASTDDS_STATISTICS|// FASTDDS_STATISTICS off|' \
        "$CACHE/inc/fastrtps/config.h.in" >"$CACHE/inc/fastrtps/config.h" || return 1
    sed -e 's/@PROJECT_VERSION_MAJOR@/2/; s/@PROJECT_VERSION_MINOR@/2/; s/@PROJECT_VERSION_PATCH@/8/' \
        -e "s/@PROJECT_VERSION@/$FCDR_VER/" \
        -e 's/@HAVE_CXX11@/1/; s/@FASTCDR_IS_BIG_ENDIAN_TARGET@/0/' \
        -e 's/@FASTCDR_HAVE_FLOAT128@/1/; s/@FASTCDR_SIZEOF_LONG_DOUBLE@/16/' \
        "$CACHE/inc/fastcdr/config.h.in" >"$CACHE/inc/fastcdr/config.h" || return 1
    if grep -q '@' "$CACHE/inc/fastrtps/config.h" "$CACHE/inc/fastcdr/config.h"; then
        echo "fastdds_lint: a config.h still has an unexpanded @VAR@ - upstream added one" >&2
        return 1
    fi

    # fastddsgen is not installed here. These stand in for its Bench.h/BenchPubSubTypes.h, in the
    # v2 accessor shape (methods, not members) the rpis' fastddsgen 2.3.0 emits - which is what the
    # harness sources are written against (msg.seq(), msg.send_ns()).
    cat >"$CACHE/gen/Bench.h" <<'STANDIN'
#ifndef BENCH_STANDIN_H
#define BENCH_STANDIN_H
#include <array>
#include <cstdint>
#ifndef BENCH_SAMPLE_BYTES
#define BENCH_SAMPLE_BYTES 76
#endif
class Bench {
  public:
    void seq(uint64_t value) { seq_ = value; }
    uint64_t seq() const { return seq_; }
    void send_ns(uint64_t value) { send_ns_ = value; }
    uint64_t send_ns() const { return send_ns_; }
    std::array<uint8_t, BENCH_SAMPLE_BYTES - 16>& payload() { return payload_; }

  private:
    uint64_t seq_ = 0;
    uint64_t send_ns_ = 0;
    std::array<uint8_t, BENCH_SAMPLE_BYTES - 16> payload_ {};
};
#endif
STANDIN
    cat >"$CACHE/gen/BenchPubSubTypes.h" <<'STANDIN'
#ifndef BENCH_PUBSUBTYPES_STANDIN_H
#define BENCH_PUBSUBTYPES_STANDIN_H
#include <fastdds/dds/topic/TopicDataType.hpp>
#include "Bench.h"
// Every pure virtual of TopicDataType has to be overridden or `new BenchPubSubType()` will not
// compile - the same list fastddsgen emits.
class BenchPubSubType : public eprosima::fastdds::dds::TopicDataType {
  public:
    BenchPubSubType() { setName("Bench"); m_typeSize = sizeof(Bench); }
    bool serialize(void*, eprosima::fastrtps::rtps::SerializedPayload_t*) override { return true; }
    bool serialize(void*, eprosima::fastrtps::rtps::SerializedPayload_t*,
                   eprosima::fastdds::dds::DataRepresentationId_t) override { return true; }
    bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t*, void*) override { return true; }
    std::function<uint32_t()> getSerializedSizeProvider(void*) override { return []() { return 0U; }; }
    std::function<uint32_t()> getSerializedSizeProvider(void*,
        eprosima::fastdds::dds::DataRepresentationId_t) override { return []() { return 0U; }; }
    void* createData() override { return nullptr; }
    void deleteData(void*) override {}
    bool getKey(void*, eprosima::fastrtps::rtps::InstanceHandle_t*, bool) override { return false; }
};
#endif
STANDIN
    echo "fastdds_lint: header tree ready"
}

[ -f "$CACHE/inc/fastrtps/config.h" ] && [ -f "$CACHE/gen/BenchPubSubTypes.h" ] || build_tree || {
    echo "fastdds_lint: could not build the header tree" >&2
    exit 2
}

# The host's own libstdc++ search path, asked of the compiler rather than guessed. Guessing a
# library path is what made the first run of this verification void.
STDARGS=()
while IFS= read -r line; do [ -n "$line" ] && STDARGS+=("$line"); done < <(
    g++ -E -x c++ - -v </dev/null 2>&1 |
        sed -n '/#include <...> search starts here:/,/End of search list/p' | grep '^ /' |
        while IFS= read -r dir; do
            printf '%s\n%s\n' "-isystem" "${dir# }"
        done
)

if [ $# -gt 0 ]; then
    FILES=("$@")
else
    mapfile -t FILES < <(find "$REPO/examples/perf_hil/fastdds" -name '*.cpp' | sort)
fi

findings=0
for f in "${FILES[@]}"; do
    out=$("$TIDY" --quiet -header-filter="${HEADER_FILTER:-harness_common\.hpp}" "$f" -- \
        -std=c++17 -DBENCH_SAMPLE_BYTES=76 "${STDARGS[@]}" \
        -I"$CACHE/gen" -I"$CACHE/inc" \
        -isystem "$CACHE/Fast-DDS-$FDDS_VER/thirdparty/boost/include" 2>&1)
    hits=$(printf '%s' "$out" | grep -cE 'warning:|error:' || true)
    if [ "$hits" != "0" ]; then
        printf '%s\n' "$out" | grep -E 'warning:|error:'
        findings=$((findings + hits))
    fi
    printf '  %-62s %s\n' "${f#"$REPO"/}" "$([ "$hits" = 0 ] && echo ok || echo "$hits finding(s)")"
done

echo "---"
echo "fastdds_lint: $findings finding(s) across ${#FILES[@]} file(s)"
exit $((findings > 0 ? 1 : 0))
