/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// The one string every generated <pkg>__<subfolder>__<Name>__type_support.c's
// rosidl_message_type_support_t sets as its own .typesupport_identifier, and the same string
// this package registers as an ament_index "rosidl_typesupport_c" resource (see this package's
// own CMakeLists.txt) - together, what lets a real rmw_create_publisher() call's standard
// get_message_typesupport_handle(type_support, rosidl_typesupport_tickle_c__identifier) reach a
// message generated by this package at all (rmw_tickle/PLAN.md's Milestone 1(c)).
extern const char* rosidl_typesupport_tickle_c__identifier;

#ifdef __cplusplus
}
#endif
