/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

#pragma once

#include <stdbool.h>
#include <stddef.h>

#include <tickle/tickle.h> // tt_DATA_ENCODE_SIZE/tt_DATA_ENCODE/tt_DATA_DECODE/tt_DATA_FREE

#ifdef __cplusplus
extern "C" {
#endif

// rosidl's typesupport contract never inspects a rosidl_message_type_support_t's own `.data`
// pointer (see rosidl_runtime_c/message_type_support_struct.h's own doc comment) - it's opaque to
// everyone except whichever specific typesupport implementation's identifier matches, so this
// shape is private to rmw_tickle and the code tools/typesupport/tickle_typesupport/ros2_cli.py
// generates (ros2_adapter.render_type_support()) - the two only need to agree with EACH OTHER,
// not with rosidl/ament_cmake or any other typesupport.
//
// A generic `const void*`/`void*` pair rather than the real ROS 2 struct / TickLE struct types,
// the same type-erasure idiom examples/*/*.c's own <Name>Topic definitions already use for
// TickLE's own tt_DATA_ENCODE et al. (a real per-message struct pointer cast through a common
// function pointer signature) - to_tickle/from_tickle need their own pair of typedefs here since,
// unlike tt_DATA_ENCODE et al., TickLE's tt_Data itself has nothing to do with ROS 2's own struct
// shape on the other side of the conversion.
typedef bool (*rosidl_typesupport_tickle_c_to_tickle_function)(const void* ros_message, void* tickle_message);
typedef bool (*rosidl_typesupport_tickle_c_from_tickle_function)(const void* tickle_message, void* ros_message);

// tickle_max_encoded_size below when the type has no computable upper bound.
//
// Deliberately 0, which is also what zero-initialisation gives. A callbacks struct that omits the
// field - one written by hand, or generated before this field existed - then reads as "no bound
// known" and gets TickLE's datagram ceiling, exactly as it did before any of this. The alternative
// (a distinctive sentinel like SIZE_MAX) would make such a struct read as "bounded, zero bytes"
// and silently under-reserve, which costs retention. Between a default that wastes memory and one
// that drops retained samples, the choice isn't close.
//
// The cost, stated so nobody rediscovers it: a genuinely empty message (std_msgs/msg/Empty, true
// maximum 0) is indistinguishable from an unbounded one here and reserves the ceiling it doesn't
// need. Rare, harmless, and the right side of that trade.
#define ROSIDL_TYPESUPPORT_TICKLE_C_ENCODED_SIZE_UNBOUNDED ((size_t)0)

typedef struct rosidl_typesupport_tickle_c_message_callbacks_t {
    // "pkg/subfolder/Type" (e.g. "test_msgs/msg/Simple") - the same string tt_Topic.name needs
    // (rmw_tickle/PLAN.md's Milestone 3: tt_hash_id(topic->name, endpoint_name) mixes in both the
    // type and the ROS topic name, matching ROS 2's own "both type and topic name must match to
    // connect" rule), stable and identical across every process/build so two independently
    // generated rmw_tickle nodes agree on the same hash for the same message type.
    const char* ros_type_name;
    size_t tickle_struct_size; // sizeof() the generated TickLE-side struct - lets rmw_tickle
                               // allocate scratch storage generically, without needing a
                               // per-message struct definition of its own
    size_t ros_struct_size;    // sizeof() the rosidl_generator_c struct - same reason, for the ROS
                               // 2 side (a subscriber's receive queue holds already-from_tickle()-
                               // converted, independently-owned ROS messages - see rmw_tickle's
                               // own rmw_subscription.c - so it needs to allocate these without a
                               // per-message struct definition of its own either)
    rosidl_typesupport_tickle_c_to_tickle_function to_tickle;
    rosidl_typesupport_tickle_c_from_tickle_function from_tickle;
    tt_DATA_ENCODE_SIZE tickle_encode_size;
    tt_DATA_ENCODE tickle_encode;
    tt_DATA_DECODE tickle_decode;
    tt_DATA_FREE tickle_free;

    // An upper bound on this type's encoded payload in bytes, or ROSIDL_TYPESUPPORT_TICKLE_C_
    // ENCODED_SIZE_UNBOUNDED when no such bound exists. Generated by layout.max_encoded_size()
    // (tools/typesupport) - see its docstring for exactly which field shapes resolve.
    //
    // Why a bound can be absent at all, since the question comes up: a plain `string` field is a
    // char* aliasing external memory (DESIGN.md's "Strings" rule), not a fixed buffer, so it has
    // no capacity to bound it - the generator deliberately doesn't auto-derive one - and the
    // runtime cap is tt_MAX_STRING_LENGTH, 65535, forty-four times a single datagram. The same
    // goes for an array whose elements are strings, and for a nested type containing either.
    // sensor_msgs/msg/Image and std_srvs/srv/SetBool are both in that category.
    //
    // rmw_tickle uses this to size a KEEP_ALL publisher's retained-sample arena, where the
    // alternative is assuming TickLE's whole single-datagram ceiling per sample: about 12 MB for a
    // depth-8192 DURABLE publisher of a 76-byte type. Under-reserving costs retention (an oversize
    // sample is sent but not retained), so an absent bound has to mean "use the ceiling" rather
    // than "guess".
    size_t tickle_max_encoded_size;
} rosidl_typesupport_tickle_c_message_callbacks_t;

#ifdef __cplusplus
}
#endif
