/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from ArrayDefaults.msg - do not edit by hand.

#include "ArrayDefaults.h"

#include <stdint.h>
#include <string.h>

#include <tickle/hal.h>
#include <tickle/tickle.h>

struct tt_Topic ArrayDefaultsTopic = {
    .name = "ArrayDefaultsTopic",
    .data_size = sizeof(struct ArrayDefaultsData),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)ArrayDefaultsData_encode_size,
    .data_encode = (tt_DATA_ENCODE)ArrayDefaultsData_encode,
    .data_decode = (tt_DATA_DECODE)ArrayDefaultsData_decode,
    .data_free = (tt_DATA_FREE)ArrayDefaultsData_free,
};

void ArrayDefaultsData_init(struct ArrayDefaultsData* data) {
    memset(data, 0, sizeof(*data));
    data->fixed_with_default[0] = 1;
    data->fixed_with_default[1] = 2;
    data->fixed_with_default[2] = 3;
    data->fixed_with_default[3] = 4;
    data->bounded_with_default[0] = 10;
    data->bounded_with_default[1] = 20;
    data->bounded_with_default_count = 2;
}

int32_t ArrayDefaultsData_encode_size(struct ArrayDefaultsData* data) {
    int32_t size = 0;
    size += 4;
    if (data->bounded_with_default_count > 4) {
        return -2;
    }
    size += 2;
    size += (int32_t)((uint32_t)(-size) & 1U);
    size += (int32_t)((uint32_t)data->bounded_with_default_count * 2);
    return size;
}

int32_t ArrayDefaultsData_encode(struct ArrayDefaultsData* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        memcpy(payload + encoded, data->fixed_with_default, 4);
        encoded += 4;
    }
    if (data->bounded_with_default_count > 4) {
        return -2;
    }
    {
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = data->bounded_with_default_count;
        encoded += 2;
        {
            uint32_t pad = ((uint32_t)(-encoded) & 1U);
            if ((uint32_t)encoded + pad > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad);
            encoded += (int32_t)pad;
        }
        if ((uint32_t)encoded + ((uint32_t)data->bounded_with_default_count * 2) > len) {
            return -1;
        }
        for (uint32_t i = 0; i < data->bounded_with_default_count; i++) {
            *(uint16_t*)(payload + encoded + ((size_t)i * 2)) = data->bounded_with_default[i];
        }
        encoded += (int32_t)((uint32_t)data->bounded_with_default_count * 2);
    }
    return encoded;
}

int32_t ArrayDefaultsData_decode(struct ArrayDefaultsData* data, const uint8_t* payload, uint32_t len,
                                 bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        memcpy(data->fixed_with_default, payload + decoded, 4);
        decoded += 4;
    }
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t count = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            count = _tt_bswap_16(count);
        }
        if (count > 4) {
            return -2;
        }
        decoded += 2;
        {
            uint32_t pad = ((uint32_t)(-decoded) & 1U);
            if ((uint32_t)decoded + pad > len) {
                return -1;
            }
            decoded += (int32_t)pad;
        }
        if ((uint32_t)decoded + ((uint32_t)count * 2) > len) {
            return -1;
        }
        for (uint32_t i = 0; i < count; i++) {
            uint16_t raw = *(const uint16_t*)(payload + decoded + ((size_t)i * 2));
            if (!is_native_endian) {
                raw = _tt_bswap_16(raw);
            }
            data->bounded_with_default[i] = raw;
        }
        decoded += (int32_t)((uint32_t)count * 2);
        data->bounded_with_default_count = count;
    }
    return decoded;
}

void ArrayDefaultsData_free(struct ArrayDefaultsData* data) {
    (void)data;
}
