/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Arrays.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#define ARRAYSDATA__BOUNDED_VALUES_CAPACITY 8
#define ARRAYSDATA__SAMPLES_CAPACITY 16

#pragma pack(push, 4)
struct ArraysData {
    uint8_t fixed_bytes[4];
    int32_t fixed_ints[3];
    uint16_t bounded_values_count; // <= 8
    uint16_t bounded_values[8];
    uint16_t samples_count; // <= 16
    float samples[16];
};
#pragma pack(pop)

int32_t ArraysData_encode_size(struct ArraysData* data);
int32_t ArraysData_encode(struct ArraysData* data, uint8_t* payload, uint32_t len);
int32_t ArraysData_decode(struct ArraysData* data, const uint8_t* payload, uint32_t len, bool is_native_endian);
void ArraysData_free(struct ArraysData* data);

_Static_assert(100 <= tt_MAX_BUFFER_LENGTH, "ArraysData's worst-case wire size exceeds a single datagram");

extern struct tt_Topic ArraysTopic;
