/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from ArrayDefaults.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#define ARRAYDEFAULTSDATA__BOUNDED_WITH_DEFAULT_CAPACITY 4

#pragma pack(push, 4)
struct ArrayDefaultsData {
    uint8_t fixed_with_default[4];
    uint16_t bounded_with_default_count; // <= 4
    uint16_t bounded_with_default[4];
};
#pragma pack(pop)

void ArrayDefaultsData_init(struct ArrayDefaultsData* data);
int32_t ArrayDefaultsData_encode_size(struct ArrayDefaultsData* data);
int32_t ArrayDefaultsData_encode(struct ArrayDefaultsData* data, uint8_t* payload, uint32_t len);
int32_t ArrayDefaultsData_decode(struct ArrayDefaultsData* data, const uint8_t* payload, uint32_t len,
                                 bool is_native_endian);
void ArrayDefaultsData_free(struct ArrayDefaultsData* data);

_Static_assert(14 <= tt_MAX_BUFFER_LENGTH, "ArrayDefaultsData's worst-case wire size exceeds a single datagram");

extern struct tt_Topic ArrayDefaultsTopic;
