/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Arrays.msg - do not edit by hand.

#include "Arrays.h"

#include <stdint.h>
#include <string.h>

#include <tickle/hal.h>
#include <tickle/tickle.h>

struct tt_Topic ArraysTopic = {
    .name = "ArraysTopic",
    .data_size = sizeof(struct ArraysData),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)ArraysData_encode_size,
    .data_encode = (tt_DATA_ENCODE)ArraysData_encode,
    .data_decode = (tt_DATA_DECODE)ArraysData_decode,
    .data_free = (tt_DATA_FREE)ArraysData_free,
};

int32_t ArraysData_encode_size(struct ArraysData* data) {
    int32_t size = 0;
    size += 4;
    size += 12;
    if (data->bounded_values_count > 8) {
        return -2;
    }
    size += 2;
    size += (int32_t)((uint32_t)(-size) & 1U);
    size += (int32_t)((uint32_t)data->bounded_values_count * 2);
    size += (int32_t)((uint32_t)(-size) & 1U);
    if (data->samples_count > 16) {
        return -2;
    }
    size += 2;
    size += (int32_t)((uint32_t)(-size) & 3U);
    size += (int32_t)((uint32_t)data->samples_count * 4);
    return size;
}

int32_t ArraysData_encode(struct ArraysData* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        memcpy(payload + encoded, data->fixed_bytes, 4);
        encoded += 4;
    }
    {
        if ((uint32_t)encoded + 12 > len) {
            return -1;
        }
        for (uint32_t i = 0; i < 3; i++) {
            *(int32_t*)(payload + encoded + ((size_t)i * 4)) = data->fixed_ints[i];
        }
        encoded += 12;
    }
    if (data->bounded_values_count > 8) {
        return -2;
    }
    {
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = data->bounded_values_count;
        encoded += 2;
        {
            uint32_t pad = ((uint32_t)(-encoded) & 1U);
            if ((uint32_t)encoded + pad > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad);
            encoded += (int32_t)pad;
        }
        if ((uint32_t)encoded + ((uint32_t)data->bounded_values_count * 2) > len) {
            return -1;
        }
        for (uint32_t i = 0; i < data->bounded_values_count; i++) {
            *(uint16_t*)(payload + encoded + ((size_t)i * 2)) = data->bounded_values[i];
        }
        encoded += (int32_t)((uint32_t)data->bounded_values_count * 2);
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 1U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    if (data->samples_count > 16) {
        return -2;
    }
    {
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = data->samples_count;
        encoded += 2;
        {
            uint32_t pad = ((uint32_t)(-encoded) & 3U);
            if ((uint32_t)encoded + pad > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad);
            encoded += (int32_t)pad;
        }
        if ((uint32_t)encoded + ((uint32_t)data->samples_count * 4) > len) {
            return -1;
        }
        for (uint32_t i = 0; i < data->samples_count; i++) {
            union {
                float value;
                uint32_t bits;
            } convert;
            convert.value = data->samples[i];
            *(uint32_t*)(payload + encoded + ((size_t)i * 4)) = convert.bits;
        }
        encoded += (int32_t)((uint32_t)data->samples_count * 4);
    }
    return encoded;
}

int32_t ArraysData_decode(struct ArraysData* data, const uint8_t* payload, uint32_t len, bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        memcpy(data->fixed_bytes, payload + decoded, 4);
        decoded += 4;
    }
    {
        if ((uint32_t)decoded + 12 > len) {
            return -1;
        }
        for (uint32_t i = 0; i < 3; i++) {
            uint32_t raw = *(const uint32_t*)(payload + decoded + ((size_t)i * 4));
            if (!is_native_endian) {
                raw = _tt_bswap_32(raw);
            }
            data->fixed_ints[i] = (int32_t)raw;
        }
        decoded += 12;
    }
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t count = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            count = _tt_bswap_16(count);
        }
        if (count > 8) {
            return -2;
        }
        decoded += 2;
        {
            uint32_t pad = ((uint32_t)(-decoded) & 1U);
            if ((uint32_t)decoded + pad > len) {
                return -1;
            }
            decoded += (int32_t)pad;
        }
        if ((uint32_t)decoded + ((uint32_t)count * 2) > len) {
            return -1;
        }
        for (uint32_t i = 0; i < count; i++) {
            uint16_t raw = *(const uint16_t*)(payload + decoded + ((size_t)i * 2));
            if (!is_native_endian) {
                raw = _tt_bswap_16(raw);
            }
            data->bounded_values[i] = raw;
        }
        decoded += (int32_t)((uint32_t)count * 2);
        data->bounded_values_count = count;
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 1U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t count = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            count = _tt_bswap_16(count);
        }
        if (count > 16) {
            return -2;
        }
        decoded += 2;
        {
            uint32_t pad = ((uint32_t)(-decoded) & 3U);
            if ((uint32_t)decoded + pad > len) {
                return -1;
            }
            decoded += (int32_t)pad;
        }
        if ((uint32_t)decoded + ((uint32_t)count * 4) > len) {
            return -1;
        }
        for (uint32_t i = 0; i < count; i++) {
            uint32_t raw = *(const uint32_t*)(payload + decoded + ((size_t)i * 4));
            if (!is_native_endian) {
                raw = _tt_bswap_32(raw);
            }
            union {
                uint32_t bits;
                float value;
            } convert;
            convert.bits = raw;
            data->samples[i] = convert.value;
        }
        decoded += (int32_t)((uint32_t)count * 4);
        data->samples_count = count;
    }
    return decoded;
}

void ArraysData_free(struct ArraysData* data) {
    (void)data;
}
