/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from BoundedString.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#define BOUNDEDSTRINGDATA__BOUNDED_NAME_CAPACITY 8
#define BOUNDEDSTRINGDATA__ANNOTATED_NAME_CAPACITY 4

#pragma pack(push, 4)
struct BoundedStringData {
    char bounded_name[9];   // <= 8 chars + NUL
    char annotated_name[5]; // <= 4 chars + NUL
    char* plain_name;
};
#pragma pack(pop)

void BoundedStringData_init(struct BoundedStringData* data);
int32_t BoundedStringData_encode_size(struct BoundedStringData* data);
int32_t BoundedStringData_encode(struct BoundedStringData* data, uint8_t* payload, uint32_t len);
int32_t BoundedStringData_decode(struct BoundedStringData* data, const uint8_t* payload, uint32_t len,
                                 bool is_native_endian);
void BoundedStringData_free(struct BoundedStringData* data);

_Static_assert(22 <= tt_MAX_BUFFER_LENGTH, "BoundedStringData's worst-case wire size exceeds a single datagram");

extern struct tt_Topic BoundedStringTopic;
