/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from BoundedString.msg - do not edit by hand.

#include "BoundedString.h"

#include <stdint.h>
#include <string.h>

#include <tickle/config.h> // tt_MAX_STRING_LENGTH
#include <tickle/hal.h>
#include <tickle/tickle.h>

struct tt_Topic BoundedStringTopic = {
    .name = "BoundedStringTopic",
    .data_size = sizeof(struct BoundedStringData),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)BoundedStringData_encode_size,
    .data_encode = (tt_DATA_ENCODE)BoundedStringData_encode,
    .data_decode = (tt_DATA_DECODE)BoundedStringData_decode,
    .data_free = (tt_DATA_FREE)BoundedStringData_free,
};

void BoundedStringData_init(struct BoundedStringData* data) {
    memset(data, 0, sizeof(*data));
    memcpy(data->bounded_name, "hi", 3);
}

int32_t BoundedStringData_encode_size(struct BoundedStringData* data) {
    int32_t size = 0;
    {
        size_t str_len = _tt_strnlen(data->bounded_name, 9) + 1;
        if (str_len > 9) {
            return -2;
        }
        size += (int32_t)(2 + str_len);
        size += (int32_t)((uint32_t)(-size) & 3U);
    }
    size += (int32_t)((uint32_t)(-size) & 1U);
    {
        size_t str_len = _tt_strnlen(data->annotated_name, 5) + 1;
        if (str_len > 5) {
            return -2;
        }
        size += (int32_t)(2 + str_len);
        size += (int32_t)((uint32_t)(-size) & 3U);
    }
    size += (int32_t)((uint32_t)(-size) & 1U);
    if (data->plain_name == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(data->plain_name, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        size += (int32_t)(2 + str_len);
        size += (int32_t)((uint32_t)(-size) & 3U);
    }
    return size;
}

int32_t BoundedStringData_encode(struct BoundedStringData* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        size_t str_len = _tt_strnlen(data->bounded_name, 9) + 1;
        if (str_len > 9) {
            return -2;
        }
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = (uint16_t)str_len;
        encoded += 2;
        if ((uint32_t)encoded + str_len > len) {
            return -1;
        }
        memcpy(payload + encoded, data->bounded_name, str_len);
        encoded += (int32_t)str_len;
        {
            uint32_t pad4 = ((uint32_t)(-encoded) & 3U);
            if ((uint32_t)encoded + pad4 > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad4);
            encoded += (int32_t)pad4;
        }
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 1U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    {
        size_t str_len = _tt_strnlen(data->annotated_name, 5) + 1;
        if (str_len > 5) {
            return -2;
        }
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = (uint16_t)str_len;
        encoded += 2;
        if ((uint32_t)encoded + str_len > len) {
            return -1;
        }
        memcpy(payload + encoded, data->annotated_name, str_len);
        encoded += (int32_t)str_len;
        {
            uint32_t pad4 = ((uint32_t)(-encoded) & 3U);
            if ((uint32_t)encoded + pad4 > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad4);
            encoded += (int32_t)pad4;
        }
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 1U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    if (data->plain_name == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(data->plain_name, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = (uint16_t)str_len;
        encoded += 2;
        if ((uint32_t)encoded + str_len > len) {
            return -1;
        }
        memcpy(payload + encoded, data->plain_name, str_len);
        encoded += (int32_t)str_len;
        {
            uint32_t pad4 = ((uint32_t)(-encoded) & 3U);
            if ((uint32_t)encoded + pad4 > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad4);
            encoded += (int32_t)pad4;
        }
    }
    return encoded;
}

int32_t BoundedStringData_decode(struct BoundedStringData* data, const uint8_t* payload, uint32_t len,
                                 bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t str_len = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            str_len = _tt_bswap_16(str_len);
        }
        if (str_len == 0) {
            return -2;
        }
        if (str_len > 9) {
            return -2;
        }
        decoded += 2;
        if ((uint32_t)decoded + str_len > len) {
            return -1;
        }
        if (payload[decoded + str_len - 1] != '\0') {
            return -2;
        }
        memcpy(data->bounded_name, payload + decoded, str_len);
        decoded += str_len;
        decoded += (int32_t)((uint32_t)(-decoded) & 3U);
        if ((uint32_t)decoded > len) {
            return -1;
        }
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 1U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t str_len = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            str_len = _tt_bswap_16(str_len);
        }
        if (str_len == 0) {
            return -2;
        }
        if (str_len > 5) {
            return -2;
        }
        decoded += 2;
        if ((uint32_t)decoded + str_len > len) {
            return -1;
        }
        if (payload[decoded + str_len - 1] != '\0') {
            return -2;
        }
        memcpy(data->annotated_name, payload + decoded, str_len);
        decoded += str_len;
        decoded += (int32_t)((uint32_t)(-decoded) & 3U);
        if ((uint32_t)decoded > len) {
            return -1;
        }
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 1U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t str_len = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            str_len = _tt_bswap_16(str_len);
        }
        if (str_len == 0) {
            return -2;
        }
        decoded += 2;
        if ((uint32_t)decoded + str_len > len) {
            return -1;
        }
        if (payload[decoded + str_len - 1] != '\0') {
            return -2;
        }
        data->plain_name = (char*)(payload + decoded); // aliases the input buffer - see *_free()
        decoded += str_len;
        decoded += (int32_t)((uint32_t)(-decoded) & 3U);
        if ((uint32_t)decoded > len) {
            return -1;
        }
    }
    return decoded;
}

void BoundedStringData_free(struct BoundedStringData* data) {
    (void)data;
}
