/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from builtin_interfaces/Time.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH

#pragma pack(push, 4)
struct builtin_interfaces__Time {
    int32_t sec;
    uint32_t nanosec;
};
#pragma pack(pop)

int32_t builtin_interfaces__Time_encode_size(struct builtin_interfaces__Time* data);
int32_t builtin_interfaces__Time_encode(struct builtin_interfaces__Time* data, uint8_t* payload, uint32_t len);
int32_t builtin_interfaces__Time_decode(struct builtin_interfaces__Time* data, const uint8_t* payload, uint32_t len,
                                        bool is_native_endian);
int32_t builtin_interfaces__Time_encode_inplace(struct builtin_interfaces__Time* data, const uint8_t** payload_out);
struct builtin_interfaces__Time* builtin_interfaces__Time_decode_inplace(const uint8_t* payload, uint32_t len,
                                                                         bool is_native_endian);
void builtin_interfaces__Time_free(struct builtin_interfaces__Time* data);

_Static_assert(sizeof(struct builtin_interfaces__Time) == 8,
               "builtin_interfaces__Time must match its CDR-4 wire size - ABI mismatch");
_Static_assert(8 <= tt_MAX_BUFFER_LENGTH, "builtin_interfaces__Time's worst-case wire size exceeds a single datagram");
