/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from builtin_interfaces/Time.msg - do not edit by hand.

#include "builtin_interfaces__Time.h"

#include <stdint.h>

#include <tickle/hal.h>

int32_t builtin_interfaces__Time_encode_size(struct builtin_interfaces__Time* data) {
    (void)data;
    return 8;
}

int32_t builtin_interfaces__Time_encode(struct builtin_interfaces__Time* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        *(int32_t*)(payload + encoded) = data->sec;
        encoded += 4;
    }
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        *(uint32_t*)(payload + encoded) = data->nanosec;
        encoded += 4;
    }
    return encoded;
}

int32_t builtin_interfaces__Time_decode(struct builtin_interfaces__Time* data, const uint8_t* payload, uint32_t len,
                                        bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        uint32_t raw = *(const uint32_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_32(raw);
        }
        data->sec = (int32_t)raw;
        decoded += 4;
    }
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        uint32_t raw = *(const uint32_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_32(raw);
        }
        data->nanosec = raw;
        decoded += 4;
    }
    return decoded;
}

void builtin_interfaces__Time_free(struct builtin_interfaces__Time* data) {
    (void)data;
}
