/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Bulk.msg - do not edit by hand.

#include "Bulk.h"

#include <stddef.h> // NULL, in *_decode_inplace
#include <stdint.h>
#include <string.h>

#include <tickle/hal.h>
#include <tickle/tickle.h>

struct tt_Topic BulkTopic = {
    .name = "BulkTopic",
    .data_size = sizeof(struct BulkData),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)BulkData_encode_size,
    .data_encode = (tt_DATA_ENCODE)BulkData_encode,
    .data_encode_inplace = (tt_DATA_ENCODE_INPLACE)BulkData_encode_inplace,
    .data_decode = (tt_DATA_DECODE)BulkData_decode,
    .data_decode_inplace = (tt_DATA_DECODE_INPLACE)BulkData_decode_inplace,
    .data_free = (tt_DATA_FREE)BulkData_free,
};

int32_t BulkData_encode_size(struct BulkData* data) {
    int32_t size = 0;
    size += 4;
    if (data->payload_count > 1442) {
        return -2;
    }
    size += 2;
    size += (int32_t)((uint32_t)data->payload_count * 1);
    return size;
}

int32_t BulkData_encode(struct BulkData* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        *(uint32_t*)(payload + encoded) = data->seq;
        encoded += 4;
    }
    if (data->payload_count > 1442) {
        return -2;
    }
    {
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = data->payload_count;
        encoded += 2;
        if ((uint32_t)encoded + data->payload_count > len) {
            return -1;
        }
        memcpy(payload + encoded, data->payload, data->payload_count);
        encoded += (int32_t)data->payload_count;
    }
    return encoded;
}

int32_t BulkData_decode(struct BulkData* data, const uint8_t* payload, uint32_t len, bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        uint32_t raw = *(const uint32_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_32(raw);
        }
        data->seq = raw;
        decoded += 4;
    }
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t count = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            count = _tt_bswap_16(count);
        }
        if (count > 1442) {
            return -2;
        }
        decoded += 2;
        if ((uint32_t)decoded + count > len) {
            return -1;
        }
        memcpy(data->payload, payload + decoded, count);
        decoded += (int32_t)count;
        data->payload_count = count;
    }
    return decoded;
}

int32_t BulkData_encode_inplace(struct BulkData* data, const uint8_t** payload_out) {
    if (data->payload_count > 1442) {
        return -2;
    }
    *payload_out = (const uint8_t*)data;
    return 4 + 2 + (int32_t)data->payload_count;
}

struct BulkData* BulkData_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian) {
    if (!is_native_endian || len < (uint32_t)4 + 2) {
        return NULL;
    }
    {
        uint16_t count = *(const uint16_t*)(payload + 4);
        if (count > 1442 || (uint32_t)4 + 2 + count > len) {
            return NULL;
        }
    }
    return (struct BulkData*)payload;
}

void BulkData_free(struct BulkData* data) {
    (void)data;
}
