/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from geometry_msgs/Vector3.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH

#pragma pack(push, 4)
struct geometry_msgs__Vector3 {
    double x;
    double y;
    double z;
};
#pragma pack(pop)

int32_t geometry_msgs__Vector3_encode_size(struct geometry_msgs__Vector3* data);
int32_t geometry_msgs__Vector3_encode(struct geometry_msgs__Vector3* data, uint8_t* payload, uint32_t len);
int32_t geometry_msgs__Vector3_decode(struct geometry_msgs__Vector3* data, const uint8_t* payload, uint32_t len,
                                      bool is_native_endian);
int32_t geometry_msgs__Vector3_encode_inplace(struct geometry_msgs__Vector3* data, const uint8_t** payload_out);
struct geometry_msgs__Vector3* geometry_msgs__Vector3_decode_inplace(const uint8_t* payload, uint32_t len,
                                                                     bool is_native_endian);
void geometry_msgs__Vector3_free(struct geometry_msgs__Vector3* data);

_Static_assert(sizeof(struct geometry_msgs__Vector3) == 24,
               "geometry_msgs__Vector3 must match its CDR-4 wire size - ABI mismatch");
_Static_assert(24 <= tt_MAX_BUFFER_LENGTH, "geometry_msgs__Vector3's worst-case wire size exceeds a single datagram");
