/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from geometry_msgs/Vector3.msg - do not edit by hand.

#include "geometry_msgs__Vector3.h"

#include <stdint.h>

#include <tickle/hal.h>

int32_t geometry_msgs__Vector3_encode_size(struct geometry_msgs__Vector3* data) {
    (void)data;
    return 24;
}

int32_t geometry_msgs__Vector3_encode(struct geometry_msgs__Vector3* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 8 > len) {
            return -1;
        }
        union {
            double value;
            uint64_t bits;
        } convert;
        convert.value = data->x;
        *(uint64_t*)(payload + encoded) = convert.bits;
        encoded += 8;
    }
    {
        if ((uint32_t)encoded + 8 > len) {
            return -1;
        }
        union {
            double value;
            uint64_t bits;
        } convert;
        convert.value = data->y;
        *(uint64_t*)(payload + encoded) = convert.bits;
        encoded += 8;
    }
    {
        if ((uint32_t)encoded + 8 > len) {
            return -1;
        }
        union {
            double value;
            uint64_t bits;
        } convert;
        convert.value = data->z;
        *(uint64_t*)(payload + encoded) = convert.bits;
        encoded += 8;
    }
    return encoded;
}

int32_t geometry_msgs__Vector3_decode(struct geometry_msgs__Vector3* data, const uint8_t* payload, uint32_t len,
                                      bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 8 > len) {
            return -1;
        }
        uint64_t raw = *(const uint64_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_64(raw);
        }
        union {
            uint64_t bits;
            double value;
        } convert;
        convert.bits = raw;
        data->x = convert.value;
        decoded += 8;
    }
    {
        if ((uint32_t)decoded + 8 > len) {
            return -1;
        }
        uint64_t raw = *(const uint64_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_64(raw);
        }
        union {
            uint64_t bits;
            double value;
        } convert;
        convert.bits = raw;
        data->y = convert.value;
        decoded += 8;
    }
    {
        if ((uint32_t)decoded + 8 > len) {
            return -1;
        }
        uint64_t raw = *(const uint64_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_64(raw);
        }
        union {
            uint64_t bits;
            double value;
        } convert;
        convert.bits = raw;
        data->z = convert.value;
        decoded += 8;
    }
    return decoded;
}

int32_t geometry_msgs__Vector3_encode_inplace(struct geometry_msgs__Vector3* data, const uint8_t** payload_out) {
    *payload_out = (const uint8_t*)data;
    return 24;
}

struct geometry_msgs__Vector3* geometry_msgs__Vector3_decode_inplace(const uint8_t* payload, uint32_t len,
                                                                     bool is_native_endian) {
    if (!is_native_endian || len < 24) {
        return NULL;
    }
    return (struct geometry_msgs__Vector3*)payload;
}

void geometry_msgs__Vector3_free(struct geometry_msgs__Vector3* data) {
    (void)data;
}
