/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Image.msg - do not edit by hand.

#include "Image.h"

#include <stdint.h>
#include <string.h>

#include <tickle/config.h> // tt_MAX_STRING_LENGTH
#include <tickle/hal.h>
#include <tickle/tickle.h>

#include "std_msgs__Header.h"

struct tt_Topic ImageTopic = {
    .name = "ImageTopic",
    .data_size = sizeof(struct ImageData),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)ImageData_encode_size,
    .data_encode = (tt_DATA_ENCODE)ImageData_encode,
    .data_decode = (tt_DATA_DECODE)ImageData_decode,
    .data_free = (tt_DATA_FREE)ImageData_free,
};

int32_t ImageData_encode_size(struct ImageData* data) {
    int32_t size = 0;
    {
        int32_t nested_size = std_msgs__Header_encode_size(&data->header);
        if (nested_size < 0) {
            return nested_size;
        }
        size += nested_size;
    }
    size += (int32_t)((uint32_t)(-size) & 3U);
    size += 4;
    size += (int32_t)((uint32_t)(-size) & 3U);
    size += 4;
    size += (int32_t)((uint32_t)(-size) & 1U);
    if (data->encoding == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(data->encoding, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        size += (int32_t)(2 + str_len);
        size += (int32_t)((uint32_t)(-size) & 3U);
    }
    size += 1;
    size += (int32_t)((uint32_t)(-size) & 3U);
    size += 4;
    size += (int32_t)((uint32_t)(-size) & 1U);
    if (data->data_count > 1400) {
        return -2;
    }
    size += 2;
    size += (int32_t)((uint32_t)data->data_count * 1);
    return size;
}

int32_t ImageData_encode(struct ImageData* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        int32_t nested_size = std_msgs__Header_encode(&data->header, payload + encoded, len - (uint32_t)encoded);
        if (nested_size < 0) {
            return nested_size;
        }
        encoded += nested_size;
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 3U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        *(uint32_t*)(payload + encoded) = data->height;
        encoded += 4;
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 3U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        *(uint32_t*)(payload + encoded) = data->width;
        encoded += 4;
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 1U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    if (data->encoding == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(data->encoding, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = (uint16_t)str_len;
        encoded += 2;
        if ((uint32_t)encoded + str_len > len) {
            return -1;
        }
        memcpy(payload + encoded, data->encoding, str_len);
        encoded += (int32_t)str_len;
        {
            uint32_t pad4 = ((uint32_t)(-encoded) & 3U);
            if ((uint32_t)encoded + pad4 > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad4);
            encoded += (int32_t)pad4;
        }
    }
    {
        if ((uint32_t)encoded + 1 > len) {
            return -1;
        }
        *(uint8_t*)(payload + encoded) = data->is_bigendian;
        encoded += 1;
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 3U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        *(uint32_t*)(payload + encoded) = data->step;
        encoded += 4;
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 1U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    if (data->data_count > 1400) {
        return -2;
    }
    {
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = data->data_count;
        encoded += 2;
        if ((uint32_t)encoded + data->data_count > len) {
            return -1;
        }
        memcpy(payload + encoded, data->data, data->data_count);
        encoded += (int32_t)data->data_count;
    }
    return encoded;
}

int32_t ImageData_decode(struct ImageData* data, const uint8_t* payload, uint32_t len, bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        int32_t nested_size =
            std_msgs__Header_decode(&data->header, payload + decoded, len - (uint32_t)decoded, is_native_endian);
        if (nested_size < 0) {
            return nested_size;
        }
        decoded += nested_size;
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 3U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        uint32_t raw = *(const uint32_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_32(raw);
        }
        data->height = raw;
        decoded += 4;
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 3U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        uint32_t raw = *(const uint32_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_32(raw);
        }
        data->width = raw;
        decoded += 4;
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 1U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t str_len = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            str_len = _tt_bswap_16(str_len);
        }
        if (str_len == 0) {
            return -2;
        }
        decoded += 2;
        if ((uint32_t)decoded + str_len > len) {
            return -1;
        }
        if (payload[decoded + str_len - 1] != '\0') {
            return -2;
        }
        data->encoding = (char*)(payload + decoded); // aliases the input buffer - see *_free()
        decoded += str_len;
        decoded += (int32_t)((uint32_t)(-decoded) & 3U);
        if ((uint32_t)decoded > len) {
            return -1;
        }
    }
    {
        if ((uint32_t)decoded + 1 > len) {
            return -1;
        }
        data->is_bigendian = *(const uint8_t*)(payload + decoded);
        decoded += 1;
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 3U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        uint32_t raw = *(const uint32_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_32(raw);
        }
        data->step = raw;
        decoded += 4;
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 1U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t count = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            count = _tt_bswap_16(count);
        }
        if (count > 1400) {
            return -2;
        }
        decoded += 2;
        if ((uint32_t)decoded + count > len) {
            return -1;
        }
        memcpy(data->data, payload + decoded, count);
        decoded += (int32_t)count;
        data->data_count = count;
    }
    return decoded;
}

void ImageData_free(struct ImageData* data) {
    (void)data;
}
