/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Image.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#include "std_msgs__Header.h"

#define IMAGEDATA__DATA_CAPACITY 1400

#pragma pack(push, 4)
struct ImageData {
    struct std_msgs__Header header;
    uint32_t height;
    uint32_t width;
    char* encoding;
    uint8_t is_bigendian;
    uint32_t step;
    uint16_t data_count; // <= 1400
    uint8_t data[1400];
};
#pragma pack(pop)

int32_t ImageData_encode_size(struct ImageData* data);
int32_t ImageData_encode(struct ImageData* data, uint8_t* payload, uint32_t len);
int32_t ImageData_decode(struct ImageData* data, const uint8_t* payload, uint32_t len, bool is_native_endian);
void ImageData_free(struct ImageData* data);

_Static_assert(1430 <= tt_MAX_BUFFER_LENGTH, "ImageData's worst-case wire size exceeds a single datagram");

extern struct tt_Topic ImageTopic;
