/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from nested_arrays_pkg/OddAlign.msg - do not edit by hand.

#include "nested_arrays_pkg__OddAlign.h"

#include <stddef.h> // NULL, in *_decode_inplace
#include <stdint.h>
#include <string.h>

#include <tickle/hal.h>

int32_t nested_arrays_pkg__OddAlign_encode_size(struct nested_arrays_pkg__OddAlign* data) {
    (void)data;
    return 13;
}

int32_t nested_arrays_pkg__OddAlign_encode(struct nested_arrays_pkg__OddAlign* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 1 > len) {
            return -1;
        }
        *(bool*)(payload + encoded) = data->flag;
        encoded += 1;
    }
    if ((uint32_t)encoded + (3) > len) {
        return -1;
    }
    memset(payload + encoded, 0, 3);
    encoded += (int32_t)(3);
    {
        if ((uint32_t)encoded + 8 > len) {
            return -1;
        }
        *(int64_t*)(payload + encoded) = data->big;
        encoded += 8;
    }
    {
        if ((uint32_t)encoded + 1 > len) {
            return -1;
        }
        *(uint8_t*)(payload + encoded) = data->tail;
        encoded += 1;
    }
    return encoded;
}

int32_t nested_arrays_pkg__OddAlign_decode(struct nested_arrays_pkg__OddAlign* data, const uint8_t* payload,
                                           uint32_t len, bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 1 > len) {
            return -1;
        }
        data->flag = *(const bool*)(payload + decoded);
        decoded += 1;
    }
    if ((uint32_t)decoded + 3 > len) {
        return -1;
    }
    decoded += 3;
    {
        if ((uint32_t)decoded + 8 > len) {
            return -1;
        }
        uint64_t raw = *(const uint64_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_64(raw);
        }
        data->big = (int64_t)raw;
        decoded += 8;
    }
    {
        if ((uint32_t)decoded + 1 > len) {
            return -1;
        }
        data->tail = *(const uint8_t*)(payload + decoded);
        decoded += 1;
    }
    return decoded;
}

int32_t nested_arrays_pkg__OddAlign_encode_inplace(struct nested_arrays_pkg__OddAlign* data,
                                                   const uint8_t** payload_out) {
    *payload_out = (const uint8_t*)data;
    return 13;
}

struct nested_arrays_pkg__OddAlign* nested_arrays_pkg__OddAlign_decode_inplace(const uint8_t* payload, uint32_t len,
                                                                               bool is_native_endian) {
    if (!is_native_endian || len < 13) {
        return NULL;
    }
    return (struct nested_arrays_pkg__OddAlign*)payload;
}

void nested_arrays_pkg__OddAlign_free(struct nested_arrays_pkg__OddAlign* data) {
    (void)data;
}
