/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from NestedArrays.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#include "nested_arrays_pkg__OddAlign.h"

#define NESTEDARRAYSDATA__BOUNDED_ITEMS_CAPACITY 3
#define NESTEDARRAYSDATA__TAGGED_ITEMS_CAPACITY 4

#pragma pack(push, 4)
struct NestedArraysData {
    struct nested_arrays_pkg__OddAlign fixed_items[2];
    uint16_t bounded_items_count; // <= 3
    struct nested_arrays_pkg__OddAlign bounded_items[3];
    uint16_t tagged_items_count; // <= 4
    struct nested_arrays_pkg__OddAlign tagged_items[4];
};
#pragma pack(pop)

int32_t NestedArraysData_encode_size(struct NestedArraysData* data);
int32_t NestedArraysData_encode(struct NestedArraysData* data, uint8_t* payload, uint32_t len);
int32_t NestedArraysData_decode(struct NestedArraysData* data, const uint8_t* payload, uint32_t len,
                                bool is_native_endian);
void NestedArraysData_free(struct NestedArraysData* data);

_Static_assert(148 <= tt_MAX_BUFFER_LENGTH, "NestedArraysData's worst-case wire size exceeds a single datagram");

extern struct tt_Topic NestedArraysTopic;
