/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from nested_arrays_pkg/OddAlign.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH

#pragma pack(push, 4)
struct nested_arrays_pkg__OddAlign {
    bool flag;
    int64_t big;
    uint8_t tail;
};
#pragma pack(pop)

int32_t nested_arrays_pkg__OddAlign_encode_size(struct nested_arrays_pkg__OddAlign* data);
int32_t nested_arrays_pkg__OddAlign_encode(struct nested_arrays_pkg__OddAlign* data, uint8_t* payload, uint32_t len);
int32_t nested_arrays_pkg__OddAlign_decode(struct nested_arrays_pkg__OddAlign* data, const uint8_t* payload,
                                           uint32_t len, bool is_native_endian);
int32_t nested_arrays_pkg__OddAlign_encode_inplace(struct nested_arrays_pkg__OddAlign* data,
                                                   const uint8_t** payload_out);
struct nested_arrays_pkg__OddAlign* nested_arrays_pkg__OddAlign_decode_inplace(const uint8_t* payload, uint32_t len,
                                                                               bool is_native_endian);
void nested_arrays_pkg__OddAlign_free(struct nested_arrays_pkg__OddAlign* data);

_Static_assert(sizeof(struct nested_arrays_pkg__OddAlign) == 16,
               "nested_arrays_pkg__OddAlign must match its CDR-4 wire size - ABI mismatch");
#define nested_arrays_pkg__OddAlign_FITS_ONE_DATAGRAM (13 <= tt_MAX_BUFFER_LENGTH)
