/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from NestedArrays.msg - do not edit by hand.

#include "NestedArrays.h"

#include <stdint.h>
#include <string.h>

#include <tickle/hal.h>
#include <tickle/tickle.h>

#include "nested_arrays_pkg__OddAlign.h"

struct tt_Topic NestedArraysTopic = {
    .name = "NestedArraysTopic",
    .data_size = sizeof(struct NestedArraysData),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)NestedArraysData_encode_size,
    .data_encode = (tt_DATA_ENCODE)NestedArraysData_encode,
    .data_decode = (tt_DATA_DECODE)NestedArraysData_decode,
    .data_free = (tt_DATA_FREE)NestedArraysData_free,
};

static int32_t NestedArraysData_encode_nested_arrays_pkg__OddAlign_element(struct nested_arrays_pkg__OddAlign* item,
                                                                           uint8_t* payload, uint32_t len,
                                                                           int32_t encoded, bool is_first) {
    if (!is_first) {
        uint32_t pad = ((uint32_t)(-encoded) & 3U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    int32_t nested_size = nested_arrays_pkg__OddAlign_encode(item, payload + encoded, len - (uint32_t)encoded);
    if (nested_size < 0) {
        return nested_size;
    }
    return encoded + nested_size;
}

static int32_t NestedArraysData_decode_nested_arrays_pkg__OddAlign_element(struct nested_arrays_pkg__OddAlign* item,
                                                                           const uint8_t* payload, uint32_t len,
                                                                           int32_t decoded, bool is_native_endian,
                                                                           bool is_first) {
    if (!is_first) {
        decoded += (int32_t)((uint32_t)(-decoded) & 3U);
        if ((uint32_t)decoded > len) {
            return -1;
        }
    }
    int32_t nested_size =
        nested_arrays_pkg__OddAlign_decode(item, payload + decoded, len - (uint32_t)decoded, is_native_endian);
    if (nested_size < 0) {
        return nested_size;
    }
    return decoded + nested_size;
}

int32_t NestedArraysData_encode_size(struct NestedArraysData* data) {
    int32_t size = 0;
    size += 29;
    size += 1;
    if (data->bounded_items_count > 3) {
        return -2;
    }
    size += 2;
    size += (int32_t)((uint32_t)(-size) & 3U);
    for (uint32_t i = 0; i < data->bounded_items_count; i++) {
        if (i > 0) {
            size += (int32_t)((uint32_t)(-size) & 3U);
        }
        int32_t nested_size = nested_arrays_pkg__OddAlign_encode_size(&data->bounded_items[i]);
        if (nested_size < 0) {
            return nested_size;
        }
        size += nested_size;
    }
    size += (int32_t)((uint32_t)(-size) & 1U);
    if (data->tagged_items_count > 4) {
        return -2;
    }
    size += 2;
    size += (int32_t)((uint32_t)(-size) & 3U);
    for (uint32_t i = 0; i < data->tagged_items_count; i++) {
        if (i > 0) {
            size += (int32_t)((uint32_t)(-size) & 3U);
        }
        int32_t nested_size = nested_arrays_pkg__OddAlign_encode_size(&data->tagged_items[i]);
        if (nested_size < 0) {
            return nested_size;
        }
        size += nested_size;
    }
    return size;
}

int32_t NestedArraysData_encode(struct NestedArraysData* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    for (uint32_t i = 0; i < 2; i++) {
        int32_t next = NestedArraysData_encode_nested_arrays_pkg__OddAlign_element(&data->fixed_items[i], payload, len,
                                                                                   encoded, i == 0);
        if (next < 0) {
            return next;
        }
        encoded = next;
    }
    if ((uint32_t)encoded + (1) > len) {
        return -1;
    }
    memset(payload + encoded, 0, 1);
    encoded += (int32_t)(1);
    if (data->bounded_items_count > 3) {
        return -2;
    }
    if ((uint32_t)encoded + 2 > len) {
        return -1;
    }
    *(uint16_t*)(payload + encoded) = data->bounded_items_count;
    encoded += 2;
    {
        uint32_t pad = ((uint32_t)(-encoded) & 3U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    for (uint32_t i = 0; i < data->bounded_items_count; i++) {
        int32_t next = NestedArraysData_encode_nested_arrays_pkg__OddAlign_element(&data->bounded_items[i], payload,
                                                                                   len, encoded, i == 0);
        if (next < 0) {
            return next;
        }
        encoded = next;
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 1U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    if (data->tagged_items_count > 4) {
        return -2;
    }
    if ((uint32_t)encoded + 2 > len) {
        return -1;
    }
    *(uint16_t*)(payload + encoded) = data->tagged_items_count;
    encoded += 2;
    {
        uint32_t pad = ((uint32_t)(-encoded) & 3U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    for (uint32_t i = 0; i < data->tagged_items_count; i++) {
        int32_t next = NestedArraysData_encode_nested_arrays_pkg__OddAlign_element(&data->tagged_items[i], payload, len,
                                                                                   encoded, i == 0);
        if (next < 0) {
            return next;
        }
        encoded = next;
    }
    return encoded;
}

int32_t NestedArraysData_decode(struct NestedArraysData* data, const uint8_t* payload, uint32_t len,
                                bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    for (uint32_t i = 0; i < 2; i++) {
        int32_t next = NestedArraysData_decode_nested_arrays_pkg__OddAlign_element(&data->fixed_items[i], payload, len,
                                                                                   decoded, is_native_endian, i == 0);
        if (next < 0) {
            return next;
        }
        decoded = next;
    }
    if ((uint32_t)decoded + 1 > len) {
        return -1;
    }
    decoded += 1;
    if ((uint32_t)decoded + 2 > len) {
        return -1;
    }
    {
        uint16_t count = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            count = _tt_bswap_16(count);
        }
        if (count > 3) {
            return -2;
        }
        decoded += 2;
        {
            decoded += (int32_t)((uint32_t)(-decoded) & 3U);
            if ((uint32_t)decoded > len) {
                return -1;
            }
        }
        for (uint32_t i = 0; i < count; i++) {
            int32_t next = NestedArraysData_decode_nested_arrays_pkg__OddAlign_element(
                &data->bounded_items[i], payload, len, decoded, is_native_endian, i == 0);
            if (next < 0) {
                return next;
            }
            decoded = next;
        }
        data->bounded_items_count = count;
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 1U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    if ((uint32_t)decoded + 2 > len) {
        return -1;
    }
    {
        uint16_t count = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            count = _tt_bswap_16(count);
        }
        if (count > 4) {
            return -2;
        }
        decoded += 2;
        {
            decoded += (int32_t)((uint32_t)(-decoded) & 3U);
            if ((uint32_t)decoded > len) {
                return -1;
            }
        }
        for (uint32_t i = 0; i < count; i++) {
            int32_t next = NestedArraysData_decode_nested_arrays_pkg__OddAlign_element(
                &data->tagged_items[i], payload, len, decoded, is_native_endian, i == 0);
            if (next < 0) {
                return next;
            }
            decoded = next;
        }
        data->tagged_items_count = count;
    }
    return decoded;
}

void NestedArraysData_free(struct NestedArraysData* data) {
    (void)data;
}
