/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from PingPong.srv - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#pragma pack(push, 4)
struct PingPongRequest {
    uint32_t seq;
    uint64_t timestamp;
};
#pragma pack(pop)

int32_t PingPongRequest_encode_size(struct PingPongRequest* data);
int32_t PingPongRequest_encode(struct PingPongRequest* data, uint8_t* payload, uint32_t len);
int32_t PingPongRequest_decode(struct PingPongRequest* data, const uint8_t* payload, uint32_t len,
                               bool is_native_endian);
int32_t PingPongRequest_encode_inplace(struct PingPongRequest* data, const uint8_t** payload_out);
struct PingPongRequest* PingPongRequest_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian);
void PingPongRequest_free(struct PingPongRequest* data);

_Static_assert(sizeof(struct PingPongRequest) == 12, "PingPongRequest must match its CDR-4 wire size - ABI mismatch");
_Static_assert(12 <= tt_MAX_BUFFER_LENGTH, "PingPongRequest's worst-case wire size exceeds a single datagram");

#pragma pack(push, 4)
struct PingPongResponse {
    uint32_t seq;
    uint64_t timestamp;
};
#pragma pack(pop)

int32_t PingPongResponse_encode_size(struct PingPongResponse* data);
int32_t PingPongResponse_encode(struct PingPongResponse* data, uint8_t* payload, uint32_t len);
int32_t PingPongResponse_decode(struct PingPongResponse* data, const uint8_t* payload, uint32_t len,
                                bool is_native_endian);
int32_t PingPongResponse_encode_inplace(struct PingPongResponse* data, const uint8_t** payload_out);
struct PingPongResponse* PingPongResponse_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian);
void PingPongResponse_free(struct PingPongResponse* data);

_Static_assert(sizeof(struct PingPongResponse) == 12, "PingPongResponse must match its CDR-4 wire size - ABI mismatch");
_Static_assert(12 <= tt_MAX_BUFFER_LENGTH, "PingPongResponse's worst-case wire size exceeds a single datagram");

extern struct tt_Service PingPongService;
