/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from PingPong.srv - do not edit by hand.

#include "PingPong.h"

#include <stddef.h> // NULL, in *_decode_inplace
#include <stdint.h>

#include <tickle/hal.h>
#include <tickle/tickle.h>

struct tt_Service PingPongService = {
    .name = "PingPongService",
    .request_size = sizeof(struct PingPongRequest),
    .response_size = sizeof(struct PingPongResponse),
    .request_encode_size = (tt_REQUEST_ENCODE_SIZE)PingPongRequest_encode_size,
    .request_encode = (tt_REQUEST_ENCODE)PingPongRequest_encode,
    .request_decode = (tt_REQUEST_DECODE)PingPongRequest_decode,
    .request_free = (tt_REQUEST_FREE)PingPongRequest_free,
    .response_encode_size = (tt_RESPONSE_ENCODE_SIZE)PingPongResponse_encode_size,
    .response_encode = (tt_RESPONSE_ENCODE)PingPongResponse_encode,
    .response_decode = (tt_RESPONSE_DECODE)PingPongResponse_decode,
    .response_free = (tt_RESPONSE_FREE)PingPongResponse_free,
    .call_retry_interval = 0, // 0 means auto
    .call_retry_count = 0,    // 0 means tt_CALL_RETRY_COUNT
};

int32_t PingPongRequest_encode_size(struct PingPongRequest* data) {
    (void)data;
    return 12;
}

int32_t PingPongRequest_encode(struct PingPongRequest* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        *(uint32_t*)(payload + encoded) = data->seq;
        encoded += 4;
    }
    {
        if ((uint32_t)encoded + 8 > len) {
            return -1;
        }
        *(uint64_t*)(payload + encoded) = data->timestamp;
        encoded += 8;
    }
    return encoded;
}

int32_t PingPongRequest_decode(struct PingPongRequest* data, const uint8_t* payload, uint32_t len,
                               bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        uint32_t raw = *(const uint32_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_32(raw);
        }
        data->seq = raw;
        decoded += 4;
    }
    {
        if ((uint32_t)decoded + 8 > len) {
            return -1;
        }
        uint64_t raw = *(const uint64_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_64(raw);
        }
        data->timestamp = raw;
        decoded += 8;
    }
    return decoded;
}

int32_t PingPongRequest_encode_inplace(struct PingPongRequest* data, const uint8_t** payload_out) {
    *payload_out = (const uint8_t*)data;
    return 12;
}

struct PingPongRequest* PingPongRequest_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian) {
    if (!is_native_endian || len < 12) {
        return NULL;
    }
    return (struct PingPongRequest*)payload;
}

void PingPongRequest_free(struct PingPongRequest* data) {
    (void)data;
}

int32_t PingPongResponse_encode_size(struct PingPongResponse* data) {
    (void)data;
    return 12;
}

int32_t PingPongResponse_encode(struct PingPongResponse* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        *(uint32_t*)(payload + encoded) = data->seq;
        encoded += 4;
    }
    {
        if ((uint32_t)encoded + 8 > len) {
            return -1;
        }
        *(uint64_t*)(payload + encoded) = data->timestamp;
        encoded += 8;
    }
    return encoded;
}

int32_t PingPongResponse_decode(struct PingPongResponse* data, const uint8_t* payload, uint32_t len,
                                bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        uint32_t raw = *(const uint32_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_32(raw);
        }
        data->seq = raw;
        decoded += 4;
    }
    {
        if ((uint32_t)decoded + 8 > len) {
            return -1;
        }
        uint64_t raw = *(const uint64_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_64(raw);
        }
        data->timestamp = raw;
        decoded += 8;
    }
    return decoded;
}

int32_t PingPongResponse_encode_inplace(struct PingPongResponse* data, const uint8_t** payload_out) {
    *payload_out = (const uint8_t*)data;
    return 12;
}

struct PingPongResponse* PingPongResponse_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian) {
    if (!is_native_endian || len < 12) {
        return NULL;
    }
    return (struct PingPongResponse*)payload;
}

void PingPongResponse_free(struct PingPongResponse* data) {
    (void)data;
}
