/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from SetBool.srv - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#pragma pack(push, 4)
struct SetBoolRequest {
    bool data;
};
#pragma pack(pop)

int32_t SetBoolRequest_encode_size(struct SetBoolRequest* data);
int32_t SetBoolRequest_encode(struct SetBoolRequest* data, uint8_t* payload, uint32_t len);
int32_t SetBoolRequest_decode(struct SetBoolRequest* data, const uint8_t* payload, uint32_t len, bool is_native_endian);
int32_t SetBoolRequest_encode_inplace(struct SetBoolRequest* data, const uint8_t** payload_out);
struct SetBoolRequest* SetBoolRequest_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian);
void SetBoolRequest_free(struct SetBoolRequest* data);

_Static_assert(sizeof(struct SetBoolRequest) == 1, "SetBoolRequest must match its CDR-4 wire size - ABI mismatch");
_Static_assert(1 <= tt_MAX_BUFFER_LENGTH, "SetBoolRequest's worst-case wire size exceeds a single datagram");

#pragma pack(push, 4)
struct SetBoolResponse {
    bool success;
    char* message;
};
#pragma pack(pop)

int32_t SetBoolResponse_encode_size(struct SetBoolResponse* data);
int32_t SetBoolResponse_encode(struct SetBoolResponse* data, uint8_t* payload, uint32_t len);
int32_t SetBoolResponse_decode(struct SetBoolResponse* data, const uint8_t* payload, uint32_t len,
                               bool is_native_endian);
void SetBoolResponse_free(struct SetBoolResponse* data);

_Static_assert(4 <= tt_MAX_BUFFER_LENGTH, "SetBoolResponse's worst-case wire size exceeds a single datagram");

extern struct tt_Service SetBoolService;
