/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Stamped.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#include "std_msgs__Header.h"

#pragma pack(push, 4)
struct StampedData {
    struct std_msgs__Header header;
    uint32_t value;
};
#pragma pack(pop)

int32_t StampedData_encode_size(struct StampedData* data);
int32_t StampedData_encode(struct StampedData* data, uint8_t* payload, uint32_t len);
int32_t StampedData_decode(struct StampedData* data, const uint8_t* payload, uint32_t len, bool is_native_endian);
void StampedData_free(struct StampedData* data);

_Static_assert(16 <= tt_MAX_BUFFER_LENGTH, "StampedData's worst-case wire size exceeds a single datagram");

extern struct tt_Topic StampedTopic;
