/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Stamped.msg - do not edit by hand.

#include "Stamped.h"

#include <stdint.h>
#include <string.h>

#include <tickle/hal.h>
#include <tickle/tickle.h>

#include "std_msgs__Header.h"

struct tt_Topic StampedTopic = {
    .name = "StampedTopic",
    .data_size = sizeof(struct StampedData),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)StampedData_encode_size,
    .data_encode = (tt_DATA_ENCODE)StampedData_encode,
    .data_decode = (tt_DATA_DECODE)StampedData_decode,
    .data_free = (tt_DATA_FREE)StampedData_free,
};

int32_t StampedData_encode_size(struct StampedData* data) {
    int32_t size = 0;
    {
        int32_t nested_size = std_msgs__Header_encode_size(&data->header);
        if (nested_size < 0) {
            return nested_size;
        }
        size += nested_size;
    }
    size += (int32_t)((uint32_t)(-size) & 3U);
    size += 4;
    return size;
}

int32_t StampedData_encode(struct StampedData* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        int32_t nested_size = std_msgs__Header_encode(&data->header, payload + encoded, len - (uint32_t)encoded);
        if (nested_size < 0) {
            return nested_size;
        }
        encoded += nested_size;
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 3U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    {
        if ((uint32_t)encoded + 4 > len) {
            return -1;
        }
        *(uint32_t*)(payload + encoded) = data->value;
        encoded += 4;
    }
    return encoded;
}

int32_t StampedData_decode(struct StampedData* data, const uint8_t* payload, uint32_t len, bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        int32_t nested_size =
            std_msgs__Header_decode(&data->header, payload + decoded, len - (uint32_t)decoded, is_native_endian);
        if (nested_size < 0) {
            return nested_size;
        }
        decoded += nested_size;
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 3U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    {
        if ((uint32_t)decoded + 4 > len) {
            return -1;
        }
        uint32_t raw = *(const uint32_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_32(raw);
        }
        data->value = raw;
        decoded += 4;
    }
    return decoded;
}

void StampedData_free(struct StampedData* data) {
    (void)data;
}
