/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from std_msgs/Header.msg - do not edit by hand.

#include "std_msgs__Header.h"

#include <stdint.h>
#include <string.h>

#include <tickle/config.h> // tt_MAX_STRING_LENGTH
#include <tickle/hal.h>

#include "builtin_interfaces__Time.h"

int32_t std_msgs__Header_encode_size(struct std_msgs__Header* data) {
    int32_t size = 0;
    {
        int32_t nested_size = builtin_interfaces__Time_encode_size(&data->stamp);
        if (nested_size < 0) {
            return nested_size;
        }
        size += nested_size;
    }
    if (data->frame_id == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(data->frame_id, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        size += (int32_t)(2 + str_len);
        size += (int32_t)((uint32_t)(-size) & 3U);
    }
    return size;
}

int32_t std_msgs__Header_encode(struct std_msgs__Header* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        int32_t nested_size = builtin_interfaces__Time_encode(&data->stamp, payload + encoded, len - (uint32_t)encoded);
        if (nested_size < 0) {
            return nested_size;
        }
        encoded += nested_size;
    }
    if (data->frame_id == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(data->frame_id, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = (uint16_t)str_len;
        encoded += 2;
        if ((uint32_t)encoded + str_len > len) {
            return -1;
        }
        memcpy(payload + encoded, data->frame_id, str_len);
        encoded += (int32_t)str_len;
        {
            uint32_t pad4 = ((uint32_t)(-encoded) & 3U);
            if ((uint32_t)encoded + pad4 > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad4);
            encoded += (int32_t)pad4;
        }
    }
    return encoded;
}

int32_t std_msgs__Header_decode(struct std_msgs__Header* data, const uint8_t* payload, uint32_t len,
                                bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        int32_t nested_size =
            builtin_interfaces__Time_decode(&data->stamp, payload + decoded, len - (uint32_t)decoded, is_native_endian);
        if (nested_size < 0) {
            return nested_size;
        }
        decoded += nested_size;
    }
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t str_len = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            str_len = _tt_bswap_16(str_len);
        }
        if (str_len == 0) {
            return -2;
        }
        decoded += 2;
        if ((uint32_t)decoded + str_len > len) {
            return -1;
        }
        if (payload[decoded + str_len - 1] != '\0') {
            return -2;
        }
        data->frame_id = (char*)(payload + decoded); // aliases the input buffer - see *_free()
        decoded += str_len;
        decoded += (int32_t)((uint32_t)(-decoded) & 3U);
        if ((uint32_t)decoded > len) {
            return -1;
        }
    }
    return decoded;
}

void std_msgs__Header_free(struct std_msgs__Header* data) {
    (void)data;
}
