/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from std_msgs/Header.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH

#include "builtin_interfaces__Time.h"

#pragma pack(push, 4)
struct std_msgs__Header {
    struct builtin_interfaces__Time stamp;
    char* frame_id;
};
#pragma pack(pop)

int32_t std_msgs__Header_encode_size(struct std_msgs__Header* data);
int32_t std_msgs__Header_encode(struct std_msgs__Header* data, uint8_t* payload, uint32_t len);
int32_t std_msgs__Header_decode(struct std_msgs__Header* data, const uint8_t* payload, uint32_t len,
                                bool is_native_endian);
void std_msgs__Header_free(struct std_msgs__Header* data);

_Static_assert(10 <= tt_MAX_BUFFER_LENGTH, "std_msgs__Header's worst-case wire size exceeds a single datagram");
