/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from StringArrays.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#define STRINGARRAYSDATA__BOUNDED_NAMES_CAPACITY 4
#define STRINGARRAYSDATA__TAGGED_NAMES_CAPACITY 5

#pragma pack(push, 4)
struct StringArraysData {
    char* fixed_names[3];
    uint16_t bounded_names_count; // <= 4
    char* bounded_names[4];
    uint16_t tagged_names_count; // <= 5
    char* tagged_names[5];
};
#pragma pack(pop)

int32_t StringArraysData_encode_size(struct StringArraysData* data);
int32_t StringArraysData_encode(struct StringArraysData* data, uint8_t* payload, uint32_t len);
int32_t StringArraysData_decode(struct StringArraysData* data, const uint8_t* payload, uint32_t len,
                                bool is_native_endian);
void StringArraysData_free(struct StringArraysData* data);

_Static_assert(28 <= tt_MAX_BUFFER_LENGTH, "StringArraysData's worst-case wire size exceeds a single datagram");

extern struct tt_Topic StringArraysTopic;
