/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from StringArrayDefaults.msg - do not edit by hand.

#include "StringArrayDefaults.h"

#include <stdint.h>
#include <string.h>

#include <tickle/config.h> // tt_MAX_STRING_LENGTH
#include <tickle/hal.h>
#include <tickle/tickle.h>

struct tt_Topic StringArrayDefaultsTopic = {
    .name = "StringArrayDefaultsTopic",
    .data_size = sizeof(struct StringArrayDefaultsData),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)StringArrayDefaultsData_encode_size,
    .data_encode = (tt_DATA_ENCODE)StringArrayDefaultsData_encode,
    .data_decode = (tt_DATA_DECODE)StringArrayDefaultsData_decode,
    .data_free = (tt_DATA_FREE)StringArrayDefaultsData_free,
};

void StringArrayDefaultsData_init(struct StringArrayDefaultsData* data) {
    memset(data, 0, sizeof(*data));
    data->fixed_with_default[0] = "";
    data->fixed_with_default[1] = "hello";
    data->bounded_with_default[0] = "a";
    data->bounded_with_default[1] = "bb";
    data->bounded_with_default_count = 2;
}

static int32_t StringArrayDefaultsData_encode_string_element(const char* str, uint8_t* payload, uint32_t len,
                                                             int32_t encoded) {
    if (str == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(str, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = (uint16_t)str_len;
        encoded += 2;
        if ((uint32_t)encoded + str_len > len) {
            return -1;
        }
        memcpy(payload + encoded, str, str_len);
        encoded += (int32_t)str_len;
        {
            uint32_t pad4 = ((uint32_t)(-encoded) & 3U);
            if ((uint32_t)encoded + pad4 > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad4);
            encoded += (int32_t)pad4;
        }
    }
    return encoded;
}

static int32_t StringArrayDefaultsData_decode_string_element(char** out, const uint8_t* payload, uint32_t len,
                                                             int32_t decoded, bool is_native_endian) {
    if ((uint32_t)decoded + 2 > len) {
        return -1;
    }
    {
        uint16_t str_len = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            str_len = _tt_bswap_16(str_len);
        }
        if (str_len == 0) {
            return -2;
        }
        decoded += 2;
        if ((uint32_t)decoded + str_len > len) {
            return -1;
        }
        if (payload[decoded + str_len - 1] != '\0') {
            return -2;
        }
        *out = (char*)(payload + decoded); // aliases the input buffer - see *_free()
        decoded += str_len;
        decoded += (int32_t)((uint32_t)(-decoded) & 3U);
        if ((uint32_t)decoded > len) {
            return -1;
        }
    }
    return decoded;
}

static int32_t StringArrayDefaultsData_string_element_size(const char* str, int32_t size) {
    if (str == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(str, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        size += (int32_t)(2 + str_len);
        size += (int32_t)((uint32_t)(-size) & 3U);
    }
    return size;
}

int32_t StringArrayDefaultsData_encode_size(struct StringArrayDefaultsData* data) {
    int32_t size = 0;
    for (uint32_t i = 0; i < 2; i++) {
        size = StringArrayDefaultsData_string_element_size(data->fixed_with_default[i], size);
        if (size < 0) {
            return size;
        }
    }
    size += (int32_t)((uint32_t)(-size) & 1U);
    if (data->bounded_with_default_count > 4) {
        return -2;
    }
    size += 2;
    for (uint32_t i = 0; i < data->bounded_with_default_count; i++) {
        size = StringArrayDefaultsData_string_element_size(data->bounded_with_default[i], size);
        if (size < 0) {
            return size;
        }
    }
    return size;
}

int32_t StringArrayDefaultsData_encode(struct StringArrayDefaultsData* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    for (uint32_t i = 0; i < 2; i++) {
        int32_t next =
            StringArrayDefaultsData_encode_string_element(data->fixed_with_default[i], payload, len, encoded);
        if (next < 0) {
            return next;
        }
        encoded = next;
    }
    {
        uint32_t pad = ((uint32_t)(-encoded) & 1U);
        if ((uint32_t)encoded + pad > len) {
            return -1;
        }
        memset(payload + encoded, 0, pad);
        encoded += (int32_t)pad;
    }
    if (data->bounded_with_default_count > 4) {
        return -2;
    }
    if ((uint32_t)encoded + 2 > len) {
        return -1;
    }
    *(uint16_t*)(payload + encoded) = data->bounded_with_default_count;
    encoded += 2;
    for (uint32_t i = 0; i < data->bounded_with_default_count; i++) {
        int32_t next =
            StringArrayDefaultsData_encode_string_element(data->bounded_with_default[i], payload, len, encoded);
        if (next < 0) {
            return next;
        }
        encoded = next;
    }
    return encoded;
}

int32_t StringArrayDefaultsData_decode(struct StringArrayDefaultsData* data, const uint8_t* payload, uint32_t len,
                                       bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    for (uint32_t i = 0; i < 2; i++) {
        int32_t next = StringArrayDefaultsData_decode_string_element(&data->fixed_with_default[i], payload, len,
                                                                     decoded, is_native_endian);
        if (next < 0) {
            return next;
        }
        decoded = next;
    }
    decoded += (int32_t)((uint32_t)(-decoded) & 1U);
    if ((uint32_t)decoded > len) {
        return -1;
    }
    if ((uint32_t)decoded + 2 > len) {
        return -1;
    }
    {
        uint16_t count = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            count = _tt_bswap_16(count);
        }
        if (count > 4) {
            return -2;
        }
        decoded += 2;
        for (uint32_t i = 0; i < count; i++) {
            int32_t next = StringArrayDefaultsData_decode_string_element(&data->bounded_with_default[i], payload, len,
                                                                         decoded, is_native_endian);
            if (next < 0) {
                return next;
            }
            decoded = next;
        }
        data->bounded_with_default_count = count;
    }
    return decoded;
}

void StringArrayDefaultsData_free(struct StringArrayDefaultsData* data) {
    (void)data;
}
