/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Trigger.srv - do not edit by hand.

#include "Trigger.h"

#include <stdint.h>
#include <string.h>

#include <tickle/config.h> // tt_MAX_STRING_LENGTH
#include <tickle/hal.h>
#include <tickle/tickle.h>

struct tt_Service TriggerService = {
    .name = "TriggerService",
    .request_size = sizeof(struct TriggerRequest),
    .response_size = sizeof(struct TriggerResponse),
    .request_encode_size = (tt_REQUEST_ENCODE_SIZE)TriggerRequest_encode_size,
    .request_encode = (tt_REQUEST_ENCODE)TriggerRequest_encode,
    .request_decode = (tt_REQUEST_DECODE)TriggerRequest_decode,
    .request_free = (tt_REQUEST_FREE)TriggerRequest_free,
    .response_encode_size = (tt_RESPONSE_ENCODE_SIZE)TriggerResponse_encode_size,
    .response_encode = (tt_RESPONSE_ENCODE)TriggerResponse_encode,
    .response_decode = (tt_RESPONSE_DECODE)TriggerResponse_decode,
    .response_free = (tt_RESPONSE_FREE)TriggerResponse_free,
    .call_retry_interval = 0, // 0 means auto
    .call_retry_count = 0,    // 0 means tt_CALL_RETRY_COUNT
};

int32_t TriggerRequest_encode_size(struct TriggerRequest* data) {
    (void)data;
    return 0;
}

int32_t TriggerRequest_encode(struct TriggerRequest* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    return encoded;
}

int32_t TriggerRequest_decode(struct TriggerRequest* data, const uint8_t* payload, uint32_t len,
                              bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    return decoded;
}

void TriggerRequest_free(struct TriggerRequest* data) {
    (void)data;
}

int32_t TriggerResponse_encode_size(struct TriggerResponse* data) {
    int32_t size = 0;
    size += 1;
    size += 1;
    if (data->message == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(data->message, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        size += (int32_t)(2 + str_len);
        size += (int32_t)((uint32_t)(-size) & 3U);
    }
    return size;
}

int32_t TriggerResponse_encode(struct TriggerResponse* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 1 > len) {
            return -1;
        }
        *(bool*)(payload + encoded) = data->success;
        encoded += 1;
    }
    if ((uint32_t)encoded + (1) > len) {
        return -1;
    }
    memset(payload + encoded, 0, 1);
    encoded += (int32_t)(1);
    if (data->message == NULL) {
        return -3;
    }
    {
        size_t str_len = _tt_strnlen(data->message, tt_MAX_STRING_LENGTH) + 1;
        if (str_len > tt_MAX_STRING_LENGTH) {
            return -2;
        }
        if ((uint32_t)encoded + 2 > len) {
            return -1;
        }
        *(uint16_t*)(payload + encoded) = (uint16_t)str_len;
        encoded += 2;
        if ((uint32_t)encoded + str_len > len) {
            return -1;
        }
        memcpy(payload + encoded, data->message, str_len);
        encoded += (int32_t)str_len;
        {
            uint32_t pad4 = ((uint32_t)(-encoded) & 3U);
            if ((uint32_t)encoded + pad4 > len) {
                return -1;
            }
            memset(payload + encoded, 0, pad4);
            encoded += (int32_t)pad4;
        }
    }
    return encoded;
}

int32_t TriggerResponse_decode(struct TriggerResponse* data, const uint8_t* payload, uint32_t len,
                               bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 1 > len) {
            return -1;
        }
        data->success = *(const bool*)(payload + decoded);
        decoded += 1;
    }
    if ((uint32_t)decoded + 1 > len) {
        return -1;
    }
    decoded += 1;
    {
        if ((uint32_t)decoded + 2 > len) {
            return -1;
        }
        uint16_t str_len = *(const uint16_t*)(payload + decoded);
        if (!is_native_endian) {
            str_len = _tt_bswap_16(str_len);
        }
        if (str_len == 0) {
            return -2;
        }
        decoded += 2;
        if ((uint32_t)decoded + str_len > len) {
            return -1;
        }
        if (payload[decoded + str_len - 1] != '\0') {
            return -2;
        }
        data->message = (char*)(payload + decoded); // aliases the input buffer - see *_free()
        decoded += str_len;
        decoded += (int32_t)((uint32_t)(-decoded) & 3U);
        if ((uint32_t)decoded > len) {
            return -1;
        }
    }
    return decoded;
}

void TriggerResponse_free(struct TriggerResponse* data) {
    (void)data;
}
