/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Trigger.srv - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/tickle.h>

#pragma pack(push, 4)
struct TriggerRequest {
    uint8_t reserved; // empty message - not serialized, just fills the struct
};
#pragma pack(pop)

int32_t TriggerRequest_encode_size(struct TriggerRequest* data);
int32_t TriggerRequest_encode(struct TriggerRequest* data, uint8_t* payload, uint32_t len);
int32_t TriggerRequest_decode(struct TriggerRequest* data, const uint8_t* payload, uint32_t len, bool is_native_endian);
void TriggerRequest_free(struct TriggerRequest* data);

#pragma pack(push, 4)
struct TriggerResponse {
    bool success;
    char* message;
};
#pragma pack(pop)

int32_t TriggerResponse_encode_size(struct TriggerResponse* data);
int32_t TriggerResponse_encode(struct TriggerResponse* data, uint8_t* payload, uint32_t len);
int32_t TriggerResponse_decode(struct TriggerResponse* data, const uint8_t* payload, uint32_t len,
                               bool is_native_endian);
void TriggerResponse_free(struct TriggerResponse* data);

extern struct tt_Service TriggerService;
