/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Twist.msg - do not edit by hand.

#include "Twist.h"

#include <stddef.h> // NULL, in *_decode_inplace
#include <stdint.h>

#include <tickle/tickle.h>

#include "geometry_msgs__Vector3.h"

struct tt_Topic TwistTopic = {
    .name = "TwistTopic",
    .data_size = sizeof(struct TwistData),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)TwistData_encode_size,
    .data_encode = (tt_DATA_ENCODE)TwistData_encode,
    .data_encode_inplace = (tt_DATA_ENCODE_INPLACE)TwistData_encode_inplace,
    .data_decode = (tt_DATA_DECODE)TwistData_decode,
    .data_decode_inplace = (tt_DATA_DECODE_INPLACE)TwistData_decode_inplace,
    .data_free = (tt_DATA_FREE)TwistData_free,
};

int32_t TwistData_encode_size(struct TwistData* data) {
    (void)data;
    return 48;
}

int32_t TwistData_encode(struct TwistData* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        int32_t nested_size = geometry_msgs__Vector3_encode(&data->linear, payload + encoded, len - (uint32_t)encoded);
        if (nested_size < 0) {
            return nested_size;
        }
        encoded += nested_size;
    }
    {
        int32_t nested_size = geometry_msgs__Vector3_encode(&data->angular, payload + encoded, len - (uint32_t)encoded);
        if (nested_size < 0) {
            return nested_size;
        }
        encoded += nested_size;
    }
    return encoded;
}

int32_t TwistData_decode(struct TwistData* data, const uint8_t* payload, uint32_t len, bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        int32_t nested_size =
            geometry_msgs__Vector3_decode(&data->linear, payload + decoded, len - (uint32_t)decoded, is_native_endian);
        if (nested_size < 0) {
            return nested_size;
        }
        decoded += nested_size;
    }
    {
        int32_t nested_size =
            geometry_msgs__Vector3_decode(&data->angular, payload + decoded, len - (uint32_t)decoded, is_native_endian);
        if (nested_size < 0) {
            return nested_size;
        }
        decoded += nested_size;
    }
    return decoded;
}

int32_t TwistData_encode_inplace(struct TwistData* data, const uint8_t** payload_out) {
    *payload_out = (const uint8_t*)data;
    return 48;
}

struct TwistData* TwistData_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian) {
    if (!is_native_endian || len < 48) {
        return NULL;
    }
    return (struct TwistData*)payload;
}

void TwistData_free(struct TwistData* data) {
    (void)data;
}
