/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from Twist.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#include "geometry_msgs__Vector3.h"

#pragma pack(push, 4)
struct TwistData {
    struct geometry_msgs__Vector3 linear;
    struct geometry_msgs__Vector3 angular;
};
#pragma pack(pop)

int32_t TwistData_encode_size(struct TwistData* data);
int32_t TwistData_encode(struct TwistData* data, uint8_t* payload, uint32_t len);
int32_t TwistData_decode(struct TwistData* data, const uint8_t* payload, uint32_t len, bool is_native_endian);
int32_t TwistData_encode_inplace(struct TwistData* data, const uint8_t** payload_out);
struct TwistData* TwistData_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian);
void TwistData_free(struct TwistData* data);

_Static_assert(sizeof(struct TwistData) == 48, "TwistData must match its CDR-4 wire size - ABI mismatch");
_Static_assert(48 <= tt_MAX_BUFFER_LENGTH, "TwistData's worst-case wire size exceeds a single datagram");

extern struct tt_Topic TwistTopic;
