/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from UInt64.msg - do not edit by hand.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include <tickle/config.h> // tt_MAX_BUFFER_LENGTH
#include <tickle/tickle.h>

#pragma pack(push, 4)
struct UInt64Data {
    uint64_t data;
};
#pragma pack(pop)

int32_t UInt64Data_encode_size(struct UInt64Data* data);
int32_t UInt64Data_encode(struct UInt64Data* data, uint8_t* payload, uint32_t len);
int32_t UInt64Data_decode(struct UInt64Data* data, const uint8_t* payload, uint32_t len, bool is_native_endian);
int32_t UInt64Data_encode_inplace(struct UInt64Data* data, const uint8_t** payload_out);
struct UInt64Data* UInt64Data_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian);
void UInt64Data_free(struct UInt64Data* data);

_Static_assert(sizeof(struct UInt64Data) == 8, "UInt64Data must match its CDR-4 wire size - ABI mismatch");
_Static_assert(8 <= tt_MAX_BUFFER_LENGTH, "UInt64Data's worst-case wire size exceeds a single datagram");

extern struct tt_Topic UInt64Topic;
