/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from UInt64.msg - do not edit by hand.

#include "UInt64.h"

#include <stdint.h>

#include <tickle/hal.h>
#include <tickle/tickle.h>

struct tt_Topic UInt64Topic = {
    .name = "UInt64Topic",
    .data_size = sizeof(struct UInt64Data),
    .data_encode_size = (tt_DATA_ENCODE_SIZE)UInt64Data_encode_size,
    .data_encode = (tt_DATA_ENCODE)UInt64Data_encode,
    .data_encode_inplace = (tt_DATA_ENCODE_INPLACE)UInt64Data_encode_inplace,
    .data_decode = (tt_DATA_DECODE)UInt64Data_decode,
    .data_decode_inplace = (tt_DATA_DECODE_INPLACE)UInt64Data_decode_inplace,
    .data_free = (tt_DATA_FREE)UInt64Data_free,
};

int32_t UInt64Data_encode_size(struct UInt64Data* data) {
    (void)data;
    return 8;
}

int32_t UInt64Data_encode(struct UInt64Data* data, uint8_t* payload, uint32_t len) {
    (void)data;
    (void)payload;
    (void)len;
    int32_t encoded = 0;
    {
        if ((uint32_t)encoded + 8 > len) {
            return -1;
        }
        *(uint64_t*)(payload + encoded) = data->data;
        encoded += 8;
    }
    return encoded;
}

int32_t UInt64Data_decode(struct UInt64Data* data, const uint8_t* payload, uint32_t len, bool is_native_endian) {
    (void)data;
    (void)payload;
    (void)len;
    (void)is_native_endian;
    int32_t decoded = 0;
    {
        if ((uint32_t)decoded + 8 > len) {
            return -1;
        }
        uint64_t raw = *(const uint64_t*)(payload + decoded);
        if (!is_native_endian) {
            raw = _tt_bswap_64(raw);
        }
        data->data = raw;
        decoded += 8;
    }
    return decoded;
}

int32_t UInt64Data_encode_inplace(struct UInt64Data* data, const uint8_t** payload_out) {
    *payload_out = (const uint8_t*)data;
    return 8;
}

struct UInt64Data* UInt64Data_decode_inplace(const uint8_t* payload, uint32_t len, bool is_native_endian) {
    if (!is_native_endian || len < 8) {
        return NULL;
    }
    return (struct UInt64Data*)payload;
}

void UInt64Data_free(struct UInt64Data* data) {
    (void)data;
}
