# Copyright (c) 2025-2026 TSN Lab, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 3, as published by the Free
# Software Foundation. A proprietary license is also available on request - see README.md.

"""Formatting is never the empy templates' job (PLAN.md) - this prepends the license/provenance
banner and runs the project's own clang-format over the result, so generated code looks exactly
like hand-written code would."""

import shutil
import subprocess

_HEADER_BANNER = """\
/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// Generated by tools/typesupport from {source} - do not edit by hand.
"""


def add_banner(text, source_name):
    return _HEADER_BANNER.format(source=source_name) + "\n" + text


def clang_format(text, *, style_dir, filename, clang_format_bin=None):
    """Runs clang-format over `text` (as a .c/.h buffer, via stdin/stdout - no temp file needed
    for the buffer itself). `style_dir` is where clang-format's `-style=file` search for
    .clang-format starts (it walks up from the *current directory*, not from
    -assume-filename, when formatting stdin) - pass the directory the generated file will
    actually live in, or the repo root. `filename` must be the real `<Name>.c`/`<Name>.h`
    basename the output will be written as (NOT a placeholder like "generated.c"): clang-format's
    IncludeCategories main-header rule (hoisting `#include "<Name>.h"` above every other include)
    only fires when -assume-filename's own basename - stripped of its extension - matches the
    quoted include, so a wrong/placeholder name silently skips that reordering and produces
    output that `make lint`'s real clang-format --dry-run then rejects. Raises if clang-format
    isn't available or fails, rather than silently shipping unformatted output - the whole point
    of this step is that generated code must pass `make lint` exactly like hand-written code."""
    binary = clang_format_bin or shutil.which("clang-format")
    if binary is None:
        raise RuntimeError("clang-format not found on PATH - required to format generated code")
    result = subprocess.run(
        [binary, "-style=file", f"-assume-filename={filename}"],
        input=text,
        capture_output=True,
        text=True,
        check=False,
        cwd=style_dir,
    )
    if result.returncode != 0:
        raise RuntimeError(f"clang-format failed:\n{result.stderr}")
    return result.stdout
