# Copyright (c) 2025-2026 TSN Lab, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 3, as published by the Free
# Software Foundation. A proprietary license is also available on request - see README.md.

"""Entry point `python3 -m tickle_typesupport.ros2_cli`, invoked once per .msg/.srv by rosidl_
typesupport_tickle_c's own CMake extension (rmw_tickle/rosidl_typesupport_tickle_c/cmake/
rosidl_typesupport_tickle_c_generate_interfaces.cmake, registered into `rosidl_generate_
interfaces()`'s `rosidl_generate_idl_interfaces` extension point - rmw_tickle/PLAN.md's Milestone
1(c)) during a *real* ROS 2 `colcon build` - NOT the `tickle-typesupport` console script (cli.py),
which targets tools/typesupport's own codegen pipeline for TickLE's own examples/ and has no
notion of ROS 2 at all.

For one <package>/msg/<name>.msg, writes into --outdir:
  <name>.h / <name>.c                                              - TickLE's own codec (cli.py's
                                                                      generate_interface() output,
                                                                      unchanged - just invoked
                                                                      programmatically here)
  <package>__msg__<name>__rosidl_typesupport_tickle_c.h/.c         - the ROS 2 <-> TickLE struct
                                                                      converter (ros2_adapter.
                                                                      render_adapter())
  <package>__msg__<name>__type_support.c                          - the rosidl_message_type_
                                                                      support_t wrapper that makes
                                                                      the above actually reachable
                                                                      from a real rmw_create_
                                                                      publisher() call (ros2_adapter.
                                                                      render_type_support() - see its
                                                                      own docstring for why this step
                                                                      is mandatory, not optional)

For one <package>/srv/<name>.srv, writes the same three files *twice* - once for
<package>__srv__<name>_Request, once for <package>__srv__<name>_Response (a .srv's request/
response are each ordinary ROS 2 messages in their own right, generated by rosidl_generator_c the
same way any other message is - just sharing one <name>.h/.c pair, rendered by render.
render_service() instead of render.render_topic()) - plus one more:
  <package>__srv__<name>__type_support.c    - the rosidl_service_type_support_t wrapper
                                               (ros2_adapter.render_service_type_support()),
                                               tying the request/response message handles above
                                               together into the one handle rmw_create_client()/
                                               rmw_create_service() actually receive

Rejects (SystemExit) anything else (subfolders other than msg/srv, e.g. action). A nested message
field is resolved via resolve.Ros2Resolver - see its own doc comment for why that's a genuinely
different resolver than cli.py's own -I/tickle_typesupport.builtins-based one, not just a thin
wrapper: every message a real ROS 2 package's own nested field could reference is *also*
independently generated as its own top-level interface by this exact same extension (either a
sibling .msg in this same package - the common case, and the only one this CLI can find without
an explicit -I - or another package's, if it too builds rosidl_typesupport_tickle_c and is found
on a caller-supplied -I path), so Ros2Resolver reuses that already-generated struct/codec instead
of writing (and linking) a second, differently-named copy. Only TickLE's own two small bundled
builtins (std_msgs/Header, builtin_interfaces/Time) still need - and get - their own freshly
generated <pkg>__<Name>.h/.c pair, written out here the same way cli.py's own loop does it.
"""

import argparse
import os

from . import _rosidl_parser as rosidl
from . import adapt, cli, postprocess, render, resolve, ros2_adapter


def _write_text(outdir, filename, text, source_label, fmt_dir):
    path = os.path.join(outdir, filename)
    formatted = postprocess.clang_format(postprocess.add_banner(text, source_label), style_dir=fmt_dir, filename=filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(formatted)
    return path


def _generate_message_typesupport(struct, ros_name, tickle_header, source_label, outdir, fmt_dir):
    """The adapter + type-support-wrapper pair every ROS 2 message needs - shared between a plain
    .msg (called once) and a .srv's request/response structs (called once each, see generate()
    below) - both are ordinary ROS 2 messages as far as rosidl_typesupport_tickle_c is concerned.
    Returns the list of file paths written."""
    written = []
    adapter_header_name = f"{ros_name}__rosidl_typesupport_tickle_c.h"
    adapter_source_name = f"{ros_name}__rosidl_typesupport_tickle_c.c"
    adapter_header, adapter_source = ros2_adapter.render_adapter(struct, ros_name, tickle_header)
    written.append(_write_text(outdir, adapter_header_name, adapter_header, source_label, fmt_dir))
    written.append(_write_text(outdir, adapter_source_name, adapter_source, source_label, fmt_dir))

    type_support_name = f"{ros_name}__type_support.c"
    type_support_source = ros2_adapter.render_type_support(struct, ros_name, tickle_header, adapter_header_name)
    written.append(_write_text(outdir, type_support_name, type_support_source, source_label, fmt_dir))
    return written


def _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir):
    """resolve.Ros2Resolver's own in_discovery_order() only ever reports TickLE's two small
    bundled builtins (std_msgs/Header, builtin_interfaces/Time) - everything else it resolves
    reuses an already-independently-generated sibling .msg's own file instead of writing a new
    one (see its own doc comment). Same render_nested() call cli.py's own identical loop makes."""
    written = []
    for _pkg_name, _msg_name, nested_struct in resolver.in_discovery_order():
        nested_header, nested_source = render.render_nested(nested_struct)
        written += cli._write_generated(nested_struct.c_name, nested_header, nested_source, source_label, outdir, fmt_dir)
    return written


def generate(package, subfolder, name, input_path, outdir, *, style_dir=None, include_dirs=()):
    """Returns the list of file paths written - same "top-level interface first" convention as
    cli.generate_interface()."""
    os.makedirs(outdir, exist_ok=True)
    fmt_dir = style_dir or outdir
    source_label = os.path.basename(input_path)
    text = open(input_path, encoding="utf-8").read()
    tickle_header = f"{name}.h"
    # A nested field's own type is looked for alongside this exact .msg/.srv first (resolve.
    # Ros2Resolver's own "same-package sibling" case - see its doc comment) - the directory
    # holding --input is exactly where a sibling .msg would live too, ROS 2's own pkg/msg/*.msg
    # layout.
    resolver = resolve.Ros2Resolver(package, os.path.dirname(input_path), include_dirs)

    if subfolder == "msg":
        spec = rosidl.parse_message_string(package, name, text)
        ir = adapt.adapt_message(name, spec, resolver)
        header, source = render.render_topic(ir)
        written = list(cli._write_generated(name, header, source, source_label, outdir, fmt_dir))
        ros_name = f"{package}__msg__{name}"
        written += _generate_message_typesupport(ir.data, ros_name, tickle_header, source_label, outdir, fmt_dir)
        written += _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir)
        return written

    if subfolder == "srv":
        spec = rosidl.parse_service_string(package, name, text)
        ir = adapt.adapt_service(name, spec, resolver)
        header, source = render.render_service(ir)
        written = list(cli._write_generated(name, header, source, source_label, outdir, fmt_dir))
        ros_service_name = f"{package}__srv__{name}"
        written += _generate_message_typesupport(
            ir.request, f"{ros_service_name}_Request", tickle_header, source_label, outdir, fmt_dir
        )
        written += _generate_message_typesupport(
            ir.response, f"{ros_service_name}_Response", tickle_header, source_label, outdir, fmt_dir
        )
        service_type_support_source = ros2_adapter.render_service_type_support(ros_service_name)
        written.append(
            _write_text(outdir, f"{ros_service_name}__type_support.c", service_type_support_source, source_label, fmt_dir)
        )
        written += _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir)
        return written

    raise SystemExit(f"{input_path}: rosidl_typesupport_tickle_c only supports .msg/.srv, not .{subfolder}")


def main(argv=None):
    parser = argparse.ArgumentParser(prog="tickle-typesupport-ros2")
    parser.add_argument("--package", required=True)
    parser.add_argument("--subfolder", required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--input", required=True, metavar="FILE.msg|FILE.srv")
    parser.add_argument("--outdir", required=True)
    parser.add_argument("--style-dir")
    parser.add_argument(
        "-I",
        "--include-dir",
        action="append",
        default=[],
        metavar="DIR",
        help="search DIR/<pkg>/msg/<Name>.msg to resolve a *cross-package* nested message field "
        "(repeatable) - a same-package sibling is always found automatically, no -I needed; "
        "builtin_interfaces/Time and std_msgs/Header are always available even without one - see "
        "resolve.Ros2Resolver/tickle_typesupport.builtins. The real CMake extension "
        "(rosidl_typesupport_tickle_c_generate_interfaces.cmake) passes one of these per "
        "dependency package (each one's own share root, computed from that package's own "
        "find_package()-set _DIR variable) - see rmw_tickle/PLAN.md's own Milestone for this.",
    )
    args = parser.parse_args(argv)

    written = generate(
        args.package,
        args.subfolder,
        args.name,
        args.input,
        args.outdir,
        style_dir=args.style_dir,
        include_dirs=args.include_dir,
    )
    print(f"{args.input} -> {', '.join(written)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
