# Copyright (c) 2025-2026 TSN Lab, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 3, as published by the Free
# Software Foundation. A proprietary license is also available on request - see README.md.

"""Entry point `python3 -m tickle_typesupport.ros2_cli`, invoked once per .msg/.srv by rosidl_
typesupport_tickle_c's own CMake extension (rmw_tickle/rosidl_typesupport_tickle_c/cmake/
rosidl_typesupport_tickle_c_generate_interfaces.cmake, registered into `rosidl_generate_
interfaces()`'s `rosidl_generate_idl_interfaces` extension point - rmw_tickle/PLAN.md's Milestone
1(c)) during a *real* ROS 2 `colcon build` - NOT the `tickle-typesupport` console script (cli.py),
which targets tools/typesupport's own codegen pipeline for TickLE's own examples/ and has no
notion of ROS 2 at all.

For one <package>/msg/<name>.msg, writes into --outdir:
  <name>.h / <name>.c                                              - TickLE's own codec (cli.py's
                                                                      generate_interface() output,
                                                                      unchanged - just invoked
                                                                      programmatically here)
  <package>__msg__<name>__rosidl_typesupport_tickle_c.h/.c         - the ROS 2 <-> TickLE struct
                                                                      converter (ros2_adapter.
                                                                      render_adapter())
  <package>__msg__<name>__type_support.c                          - the rosidl_message_type_
                                                                      support_t wrapper that makes
                                                                      the above actually reachable
                                                                      from a real rmw_create_
                                                                      publisher() call (ros2_adapter.
                                                                      render_type_support() - see its
                                                                      own docstring for why this step
                                                                      is mandatory, not optional)

For one <package>/srv/<name>.srv, writes the same three files *twice* - once for
<package>__srv__<name>_Request, once for <package>__srv__<name>_Response (a .srv's request/
response are each ordinary ROS 2 messages in their own right, generated by rosidl_generator_c the
same way any other message is - just sharing one <name>.h/.c pair, rendered by render.
render_service() instead of render.render_topic()) - plus one more:
  <package>__srv__<name>__type_support.c    - the rosidl_service_type_support_t wrapper
                                               (ros2_adapter.render_service_type_support()),
                                               tying the request/response message handles above
                                               together into the one handle rmw_create_client()/
                                               rmw_create_service() actually receive

Rejects (SystemExit) anything else (subfolders other than msg/srv, e.g. action). A nested message
field is resolved via resolve.Ros2Resolver - see its own doc comment for why that's a genuinely
different resolver than cli.py's own -I/tickle_typesupport.builtins-based one, not just a thin
wrapper: every message a real ROS 2 package's own nested field could reference is *also*
independently generated as its own top-level interface by this exact same extension (either a
sibling .msg in this same package - the common case, and the only one this CLI can find without
an explicit -I - or another package's, if it too builds rosidl_typesupport_tickle_c and is found
on a caller-supplied -I path), so Ros2Resolver reuses that already-generated struct/codec instead
of writing (and linking) a second, differently-named copy. Only TickLE's own two small bundled
builtins (std_msgs/Header, builtin_interfaces/Time) still need - and get - their own freshly
generated <pkg>__<Name>.h/.c pair, written out here the same way cli.py's own loop does it.
"""

import argparse
import os
import sys

from . import _rosidl_parser as rosidl
from . import adapt, cli, postprocess, render, resolve, ros2_adapter


def _write_text(outdir, filename, text, source_label, fmt_dir):
    path = os.path.join(outdir, filename)
    formatted = postprocess.clang_format(postprocess.add_banner(text, source_label), style_dir=fmt_dir, filename=filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(formatted)
    return path


def _generate_message_typesupport(struct, ros_name, tickle_header, source_label, outdir, fmt_dir):
    """The adapter + type-support-wrapper pair every ROS 2 message needs - shared between a plain
    .msg (called once) and a .srv's request/response structs (called once each, see generate()
    below) - both are ordinary ROS 2 messages as far as rosidl_typesupport_tickle_c is concerned.
    Returns the list of file paths written."""
    written = []
    adapter_header_name = f"{ros_name}__rosidl_typesupport_tickle_c.h"
    adapter_source_name = f"{ros_name}__rosidl_typesupport_tickle_c.c"
    adapter_header, adapter_source = ros2_adapter.render_adapter(struct, ros_name, tickle_header)
    written.append(_write_text(outdir, adapter_header_name, adapter_header, source_label, fmt_dir))
    written.append(_write_text(outdir, adapter_source_name, adapter_source, source_label, fmt_dir))

    type_support_name = f"{ros_name}__type_support.c"
    type_support_source = ros2_adapter.render_type_support(struct, ros_name, tickle_header, adapter_header_name)
    written.append(_write_text(outdir, type_support_name, type_support_source, source_label, fmt_dir))
    return written


def _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir):
    """resolve.Ros2Resolver's own in_discovery_order() only ever reports TickLE's two small
    bundled builtins (std_msgs/Header, builtin_interfaces/Time) - everything else it resolves
    reuses an already-independently-generated sibling .msg's own file instead of writing a new
    one (see its own doc comment). Same render_nested() call cli.py's own identical loop makes."""
    written = []
    for _pkg_name, _msg_name, nested_struct in resolver.in_discovery_order():
        nested_header, nested_source = render.render_nested(nested_struct)
        written += cli._write_generated(nested_struct.c_name, nested_header, nested_source, source_label, outdir, fmt_dir)
    return written


def _decline(package, subfolder, name, outdir, source_label, fmt_dir, reason):
    """Writes the files CMake expects for a message TickLE cannot generate, carrying the reason.

    The files have to exist: rosidl_typesupport_tickle_c_generate_interfaces.cmake declares each
    one by name in an add_custom_command, so a missing output fails the build exactly as hard as
    a broken one. What they must not do is define anything - no struct, no codec, and above all no
    get_message_type_support_handle symbol, so rosidl's own lookup finds nothing and
    rmw_create_publisher refuses the topic with a clear error instead of accepting it and failing
    later.

    The reason goes in the file rather than only in build output, because build output scrolls
    past and the generated header is what somebody opens when they want to know why their message
    does not work.
    """
    ros_name = f"{package}__{subfolder}__{name}"
    banner = (
        f"// TickLE has no typesupport for {package}/{subfolder}/{name}.\n"
        f"//\n"
        f"// {reason}\n"
        f"//\n"
        f"// This file is deliberately empty of declarations. Nothing is registered, so\n"
        f"// rmw_create_publisher()/rmw_create_subscription() on this type fails with a clear\n"
        f"// error rather than succeeding and breaking later. Every other type in this package is\n"
        f"// unaffected - declining one type must not fail a build for consumers that never use\n"
        f"// it, which is the whole reason this is a stub and not a compile error.\n"
    )
    # A typedef rather than nothing at all: an empty translation unit is not valid ISO C.
    marker = f"typedef int {ros_name}__tickle_unsupported_t;\n"
    written = []
    for filename in (
        f"{name}.h",
        f"{name}.c",
        f"{ros_name}__rosidl_typesupport_tickle_c.h",
        f"{ros_name}__rosidl_typesupport_tickle_c.c",
        f"{ros_name}__type_support.c",
    ):
        written.append(_write_text(outdir, filename, banner + marker, source_label, fmt_dir))
    print(f"{source_label}: DECLINED - {reason}", file=sys.stderr)
    return written


def generate(package, subfolder, name, input_path, outdir, *, style_dir=None, include_dirs=(),
             typesupport_packages=()):
    """Returns the list of file paths written - same "top-level interface first" convention as
    cli.generate_interface()."""
    os.makedirs(outdir, exist_ok=True)
    fmt_dir = style_dir or outdir
    source_label = os.path.basename(input_path)
    text = open(input_path, encoding="utf-8").read()
    tickle_header = f"{name}.h"
    # A nested field's own type is looked for in this package's own msg/ dir first (resolve.
    # Ros2Resolver's own "same-package sibling" case - see its doc comment) - a *nested* field is
    # always some other .msg, never a .srv (ROS 2's own grammar doesn't allow a .srv to nest another
    # .srv), so this is msg/ regardless of whether --input itself is a .msg or a .srv: for a .msg,
    # os.path.dirname(input_path) already *is* <pkg>/msg, so going up one more level and back down
    # into "msg" is a no-op; for a .srv, plain os.path.dirname(input_path) would give <pkg>/srv
    # instead - the real bug this sidesteps (found via rcl_interfaces' own SetParameters.srv, which
    # nests msg/Parameter - a same-package sibling *lookup that used to look in the wrong
    # directory and silently fall through to a stale copy on the -I search path instead, e.g. an
    # apt-installed rcl_interfaces missing rcl_interfaces_rmw_tickle.patch's own `# @capacity`
    # annotations - see rosidl_typesupport_tickle_c_generate_interfaces.cmake's own former .srv
    # skip, removed together with this fix).
    package_root = os.path.dirname(os.path.dirname(input_path))
    resolver = resolve.Ros2Resolver(package, os.path.join(package_root, "msg"), include_dirs,
                                    typesupport_packages)

    if subfolder == "msg":
        spec = rosidl.parse_message_string(package, name, text)
        try:
            ir = adapt.adapt_message(name, spec, resolver)
        except resolve.UnsupportedNestedPackage as unsupported:
            return _decline(
                package, subfolder, name, outdir, source_label, fmt_dir,
                f"It nests {unsupported.pkg_name}/{unsupported.msg_name}, and {unsupported.pkg_name} does not "
                f"build rosidl_typesupport_tickle_c. This applies even to a type TickLE bundles a definition "
                f"for, such as std_msgs/Header: having the struct is not the same as being able to adapt it, "
                f"because the generated ROS adapter needs {unsupported.pkg_name}'s own "
                f"...__rosidl_typesupport_tickle_c.h to convert the ROS C struct into the TickLE one, and that "
                f"header exists only if {unsupported.pkg_name} builds this typesupport itself. "
                f"This is NOT a size limit - see <Name>_FITS_ONE_DATAGRAM for that, which is a different problem "
                f"with a different fix. The remedy here is to build {unsupported.pkg_name} from source in this "
                f"workspace with the TickLE typesupport extension applied, the way std_msgs ships FastDDS "
                f"typesupport of its own.",
            )
        header, source = render.render_topic(ir)
        written = list(cli._write_generated(name, header, source, source_label, outdir, fmt_dir))
        ros_name = f"{package}__msg__{name}"
        written += _generate_message_typesupport(ir.data, ros_name, tickle_header, source_label, outdir, fmt_dir)
        written += _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir)
        return written

    if subfolder == "srv":
        # Milestone 55/56 - a same-package .msg and .srv can share one base name (real, found via
        # test_msgs' own BasicTypes.msg + BasicTypes.srv): both would otherwise write a bare
        # "<name>.h/.c" into their own msg/srv output subdirectory, and since a real CMake build
        # puts *both* directories on one compile unit's own -I list simultaneously, the C
        # preprocessor's own same-directory-first quoted-include search silently picks whichever
        # one lives in *this* file's own directory - wrong whenever a .srv needs the .msg's own
        # struct (Arrays.srv nesting the real BasicTypes message, say), a hard "incomplete element
        # type" compile error, not a warning. A .srv's own file, unlike a .msg's, is never a valid
        # *nested-field* target (ROS 2's grammar has no way to nest a .srv inside anything), so
        # nothing outside this one function ever looks a .srv's own TickLE-side name up again the
        # way resolve.Ros2Resolver does for a .msg - safe to qualify only this side, leaving every
        # .msg's own existing bare "<name>.h/.c" convention (and resolve.Ros2Resolver's own
        # matching "{msg_name}.h" computation) completely untouched.
        srv_tickle_name = f"{name}_srv"
        spec = rosidl.parse_service_string(package, name, text)
        ir = adapt.adapt_service(srv_tickle_name, spec, resolver)
        header, source = render.render_service(ir)
        written = list(cli._write_generated(srv_tickle_name, header, source, source_label, outdir, fmt_dir))
        srv_tickle_header = f"{srv_tickle_name}.h"
        ros_service_name = f"{package}__srv__{name}"
        written += _generate_message_typesupport(
            ir.request, f"{ros_service_name}_Request", srv_tickle_header, source_label, outdir, fmt_dir
        )
        written += _generate_message_typesupport(
            ir.response, f"{ros_service_name}_Response", srv_tickle_header, source_label, outdir, fmt_dir
        )
        service_type_support_source = ros2_adapter.render_service_type_support(ros_service_name)
        written.append(
            _write_text(outdir, f"{ros_service_name}__type_support.c", service_type_support_source, source_label, fmt_dir)
        )
        written += _write_builtin_nested_files(resolver, source_label, outdir, fmt_dir)
        return written

    raise SystemExit(f"{input_path}: rosidl_typesupport_tickle_c only supports .msg/.srv, not .{subfolder}")


def main(argv=None):
    parser = argparse.ArgumentParser(prog="tickle-typesupport-ros2")
    parser.add_argument("--package", required=True)
    parser.add_argument("--subfolder", required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--input", required=True, metavar="FILE.msg|FILE.srv")
    parser.add_argument("--outdir", required=True)
    parser.add_argument("--style-dir")
    parser.add_argument(
        "-I",
        "--include-dir",
        action="append",
        default=[],
        metavar="DIR",
        help="search DIR/<pkg>/msg/<Name>.msg to resolve a *cross-package* nested message field "
        "(repeatable) - a same-package sibling is always found automatically, no -I needed; "
        "builtin_interfaces/Time and std_msgs/Header are always available even without one - see "
        "resolve.Ros2Resolver/tickle_typesupport.builtins. The real CMake extension "
        "(rosidl_typesupport_tickle_c_generate_interfaces.cmake) passes one of these per "
        "dependency package (each one's own share root, computed from that package's own "
        "find_package()-set _DIR variable) - see rmw_tickle/PLAN.md's own Milestone for this.",
    )
    parser.add_argument(
        "--typesupport-package",
        action="append",
        default=[],
        metavar="PKG",
        help="PKG builds TickLE typesupport of its own, so a nested field from it can be resolved "
        "(repeatable). Without this, a cross-package nested type is DECLINED, because nothing "
        "visible here distinguishes a package that generated its own TickLE struct and ROS adapter "
        "from one that merely has a .msg on the -I search path - std_msgs has the .msg and neither "
        "of the rest. The CMake extension determines it by looking for that package's exported "
        "<pkg>::<pkg>__rosidl_typesupport_tickle_c target, which only exists if it ran this "
        "extension.",
    )
    args = parser.parse_args(argv)

    written = generate(
        args.package,
        args.subfolder,
        args.name,
        args.input,
        args.outdir,
        style_dir=args.style_dir,
        include_dirs=args.include_dir,
        typesupport_packages=args.typesupport_package,
    )
    print(f"{args.input} -> {', '.join(written)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
