/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

// The .srv counterpart to test_dispatch.c: proves a *service* generated by rosidl_typesupport_
// tickle_c is reachable through the standard get_service_typesupport_handle() dispatch chain a
// real rmw_create_client()/rmw_create_service() call would use, and that its own request_
// typesupport/response_typesupport in turn resolve through get_message_typesupport_handle() the
// exact same way a plain message's does (test_dispatch.c) - rmw_tickle/PLAN.md's Milestone 4.

#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosidl_runtime_c/service_type_support_struct.h>
#include <rosidl_typesupport_tickle_c/identifier.h>
#include <rosidl_typesupport_tickle_c/message_type_support.h>
#include <rosidl_typesupport_tickle_c/service_type_support.h>

#include "rosidl_typesupport_tickle_c_tests/srv/simple_service.h"

static const rosidl_typesupport_tickle_c_message_callbacks_t* message_callbacks(const rosidl_message_type_support_t* top) {
    const rosidl_message_type_support_t* ours = get_message_typesupport_handle(top, rosidl_typesupport_tickle_c__identifier);
    assert(ours != NULL);
    assert(ours->typesupport_identifier == rosidl_typesupport_tickle_c__identifier);
    return (const rosidl_typesupport_tickle_c_message_callbacks_t*)ours->data;
}

int main(void) {
    // The same handle a real rmw_create_client(node, type_support, ...)/rmw_create_service() call
    // would receive.
    const rosidl_service_type_support_t* top =
        ROSIDL_GET_SRV_TYPE_SUPPORT(rosidl_typesupport_tickle_c_tests, srv, SimpleService);
    assert(top != NULL);

    const rosidl_service_type_support_t* ours = get_service_typesupport_handle(top, rosidl_typesupport_tickle_c__identifier);
    assert(ours != NULL);
    assert(ours->typesupport_identifier == rosidl_typesupport_tickle_c__identifier);
    assert(ours->request_typesupport != NULL);
    assert(ours->response_typesupport != NULL);

    const rosidl_typesupport_tickle_c_service_callbacks_t* service_callbacks =
        (const rosidl_typesupport_tickle_c_service_callbacks_t*)ours->data;
    assert(service_callbacks != NULL);
    assert(strcmp(service_callbacks->ros_type_name, "rosidl_typesupport_tickle_c_tests/srv/SimpleService") == 0);

    const rosidl_typesupport_tickle_c_message_callbacks_t* request_callbacks = message_callbacks(ours->request_typesupport);
    const rosidl_typesupport_tickle_c_message_callbacks_t* response_callbacks = message_callbacks(ours->response_typesupport);
    assert(request_callbacks->tickle_struct_size > 0 && request_callbacks->tickle_struct_size <= 64);
    assert(response_callbacks->tickle_struct_size > 0 && response_callbacks->tickle_struct_size <= 64);

    struct rosidl_typesupport_tickle_c_tests__srv__SimpleService_Request request_in;
    memset(&request_in, 0, sizeof(request_in));
    request_in.request_value = true;

    uint64_t request_storage[8] = {0};
    assert(request_callbacks->to_tickle(&request_in, request_storage));

    struct rosidl_typesupport_tickle_c_tests__srv__SimpleService_Request request_out;
    memset(&request_out, 0, sizeof(request_out));
    assert(request_callbacks->from_tickle(request_storage, &request_out));
    assert(request_out.request_value == request_in.request_value);

    struct rosidl_typesupport_tickle_c_tests__srv__SimpleService_Response response_in;
    memset(&response_in, 0, sizeof(response_in));
    response_in.response_value = true;

    uint64_t response_storage[8] = {0};
    assert(response_callbacks->to_tickle(&response_in, response_storage));

    struct rosidl_typesupport_tickle_c_tests__srv__SimpleService_Response response_out;
    memset(&response_out, 0, sizeof(response_out));
    assert(response_callbacks->from_tickle(response_storage, &response_out));
    assert(response_out.response_value == response_in.response_value);

    printf("rosidl_typesupport_tickle_c service dispatch: PASS\n");
    return 0;
}
