#!/usr/bin/env python3
"""Classify every ROS 2 interface (.msg/.srv) in a set of package source trees by what TickLE's
own generator would need to support it over rmw_tickle.

Research tool for rmw_tickle/PLAN.md's standard-message milestone (user decisions 2026-09-24:
all packages where the message fits one UDP datagram, jazzy, capacity defaults the user can
override). Lives under rmw_tickle/ because it is about ROS 2 packages; TickLE core must not
depend on ROS 2. It imports tools/typesupport, which in turn imports nothing from ROS.

It runs the real generator front end rather than re-deriving the rules: tools/typesupport's
vendored parser, adapt.adapt_message/adapt_service with ros2_resolve.Ros2Resolver, and
layout.max_wire_size/max_encoded_size. Every scanned package is passed as a typesupport
package, which models the post-provisioning world where all of them build TickLE typesupport, so
a cross-package nested type is resolved rather than declined.

Classes, per message (or per service request/response):
  OK          adapts as-is and max_encoded_size <= datagram budget - a hard bound exists
  OK_STRINGS  adapts as-is and the fixed part fits, but it carries a plain string (or string
              array) whose length is only bounded at runtime - works, with a runtime length limit
  NEEDS_CAP   the generator refuses it until a capacity is chosen (more than one unbounded
              array, a non-trailing one, string arrays, ...) - the capacity-defaults table's job
  TOO_BIG     adapts, but even its fixed part exceeds the datagram budget
  ACTION      .action - rosidl_typesupport_tickle_c does not generate actions at all today
  ERROR       anything else the generator rejects; the reason is printed

Usage: p2_inventory.py <share-root> [<share-root> ...]
  each share root holds <pkg>/msg/*.msg and <pkg>/srv/*.srv (a colcon src/ tree works if its
  package directories sit directly under it; pass several roots for several repos).
"""
import os
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent.parent / "tools" / "typesupport"))
sys.path.insert(0, str(HERE.parent / "rosidl_typesupport_tickle_c"))

from tickle_typesupport import _rosidl_parser as rosidl  # noqa: E402
from rosidl_typesupport_tickle_c import ros2_resolve  # noqa: E402
from tickle_typesupport import adapt, layout, model  # noqa: E402

BUDGET = model.TT_MAX_BUFFER_LENGTH - model.FRAMING_OVERHEAD


def packages(roots):
    found = {}
    for root in roots:
        for pkg_xml in pathlib.Path(root).rglob("package.xml"):
            pkg_dir = pkg_xml.parent
            if any(part in ("test", "tests", "build", "install") for part in pkg_dir.parts):
                continue
            if any((pkg_dir / sub).is_dir() for sub in ("msg", "srv", "action")):
                found[pkg_dir.name] = pkg_dir
    return found


def has_runtime_string(struct):
    for f in struct.fields:
        if f.kind == "string" and f.capacity is None:
            return True
        if f.kind == "array" and f.array_element_kind == "string":
            return True
        if f.nested is not None and has_runtime_string(f.nested):
            return True
    return False


def classify_struct(struct):
    wire = layout.max_wire_size(struct)
    enc = layout.max_encoded_size(struct)
    if wire > BUDGET:
        return "TOO_BIG", f"fixed part {wire} B > {BUDGET}"
    if enc is not None and enc <= BUDGET:
        return "OK", f"max {enc} B"
    if has_runtime_string(struct):
        return "OK_STRINGS", f"fixed part {wire} B, strings bounded at runtime"
    return "OK", f"fixed part {wire} B"


def main(argv):
    pkgs = packages(argv[1:])
    # A flat search path of <dir>/<pkg>/msg/<Name>.msg, as Ros2Resolver expects - one symlink
    # farm so packages from different repos resolve each other.
    farm = pathlib.Path(os.environ.get("P2_FARM", "/tmp/p2_research/farm"))
    farm.mkdir(parents=True, exist_ok=True)
    for name, path in pkgs.items():
        link = farm / name
        if not link.exists():
            link.symlink_to(path.resolve())
    include_dirs = [str(farm)]
    typesupport_packages = set(pkgs)

    for pkg in sorted(pkgs):
        pdir = pkgs[pkg]
        for sub in ("msg", "srv", "action"):
            d = pdir / sub
            if not d.is_dir():
                continue
            for f in sorted(d.iterdir()):
                if f.suffix not in (".msg", ".srv", ".action"):
                    continue
                name = f.stem
                label = f"{pkg}/{sub}/{name}"
                if sub == "action":
                    print(f"{label}\tACTION\tactions are not generated by rosidl_typesupport_tickle_c")
                    continue
                text = f.read_text(encoding="utf-8")
                resolver = ros2_resolve.Ros2Resolver(pkg, str(pdir / "msg"), include_dirs, typesupport_packages)
                try:
                    if sub == "msg":
                        ir = adapt.adapt_message(name, rosidl.parse_message_string(pkg, name, text), resolver)
                        cls, why = classify_struct(ir.data)
                        print(f"{label}\t{cls}\t{why}")
                    else:
                        ir = adapt.adapt_service(f"{name}_srv", rosidl.parse_service_string(pkg, name, text), resolver)
                        for part, struct in (("Request", ir.request), ("Response", ir.response)):
                            cls, why = classify_struct(struct)
                            print(f"{label}_{part}\t{cls}\t{why}")
                except adapt.UnsupportedFieldError as e:
                    print(f"{label}\tNEEDS_CAP\t{e}")
                except Exception as e:  # noqa: BLE001 - every rejection is data here
                    print(f"{label}\tERROR\t{type(e).__name__}: {e}")


if __name__ == "__main__":
    main(sys.argv)
