/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h> // getenv()/strtoull() - env_bytes_or()
#include <string.h>

#include "rcutils/allocator.h"
#include "rmw/error_handling.h"
#include "rmw_tickle_c/rmw_tickle.h"
#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_runtime_c/service_type_support_struct.h"
#include "rosidl_typesupport_tickle_c/identifier.h"
#include "rosidl_typesupport_tickle_c/message_type_support.h"
#include "rosidl_typesupport_tickle_c/service_type_support.h"
#include "rosidl_typesupport_tickle_cpp/identifier.h"

const rosidl_typesupport_tickle_c_message_callbacks_t*
rmw_tickle_get_message_callbacks(const rosidl_message_type_support_t* type_support, const char* what,
                                 const char* name) {
    if (NULL == type_support) {
        RMW_SET_ERROR_MSG("type_support is null");
        return NULL;
    }

    // A real rclcpp::Node's create_publisher<T>()/create_subscription<T>() never hand us a
    // C-level type_support directly - they always start from the C++-level "rosidl_typesupport_
    // cpp" dispatch, whose own per-message candidate list only ever contains whatever's registered
    // as a "rosidl_typesupport_cpp" ament_index resource (rosidl_typesupport_tickle_cpp, see its
    // own package.xml doc comment for the full story - this identifier is unreachable from rclcpp
    // without it). Try that one first; fall back to the plain "_c" identifier for lower-level/
    // C-only callers (e.g. a hand-rolled rcl C application, or a future rclc/micro-ROS consumer)
    // that hand us an already-C-level type_support with no C++ wrapper to begin with.
    const rosidl_message_type_support_t* ours =
        get_message_typesupport_handle(type_support, rosidl_typesupport_tickle_cpp__identifier);
    if (NULL == ours) {
        rmw_reset_error();
        ours = get_message_typesupport_handle(type_support, rosidl_typesupport_tickle_c__identifier);
    }
    if (NULL == ours) {
        // Not a message this rmw_tickle_c build error - could be a real mismatch (a message that
        // uses a nested field, or a .srv - rosidl_typesupport_tickle_c doesn't generate a
        // typesupport for either yet, see its own PLAN.md notes) or simply this interface
        // package's own CMakeLists.txt never having find_package()-d rosidl_typesupport_tickle_c
        // before calling rosidl_generate_interfaces().
        rmw_reset_error(); // ours replaces the dispatch's own; say so rather than let rcutils warn
        if (NULL != name) {
            RMW_SET_ERROR_MSG_WITH_FORMAT_STRING("no " RMW_TICKLE_IDENTIFIER
                                                 " typesupport for the type of %s '%s' - was its package built with "
                                                 "rosidl_typesupport_tickle_c?",
                                                 what, name);
        } else {
            RMW_SET_ERROR_MSG("no " RMW_TICKLE_IDENTIFIER " typesupport for this message type - "
                              "was it generated by rosidl_typesupport_tickle_c?");
        }
        return NULL;
    }

    const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks =
        (const rosidl_typesupport_tickle_c_message_callbacks_t*)ours->data;
    // First, and before reading any other field: a struct from another generator version has a
    // different layout, so even its ros_type_name is not where this build would look for it
    // (message_type_support.h's struct_size).
    if (0 != callbacks->struct_size &&
        sizeof(rosidl_typesupport_tickle_c_message_callbacks_t) != callbacks->struct_size) {
        RMW_SET_ERROR_MSG_WITH_FORMAT_STRING(
            "a message type's " RMW_TICKLE_IDENTIFIER " typesupport was generated by a different "
            "rosidl_typesupport_tickle_c (its callbacks struct reads as %zu bytes, this rmw_tickle's is %zu) - "
            "rebuild the interface package against this rmw_tickle",
            callbacks->struct_size, sizeof(rosidl_typesupport_tickle_c_message_callbacks_t));
        return NULL;
    }
    return callbacks;
}

bool rmw_tickle_check_callbacks_usable(const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks) {
    if (0 != callbacks->tickle_max_buffer_length &&
        (size_t)tt_MAX_BUFFER_LENGTH != callbacks->tickle_max_buffer_length) {
        RMW_SET_ERROR_MSG_WITH_FORMAT_STRING(
            "type '%s' was generated for tt_MAX_BUFFER_LENGTH %zu, but rmw_tickle was built with %d - rebuild the "
            "interface package with the same value",
            callbacks->ros_type_name, callbacks->tickle_max_buffer_length, tt_MAX_BUFFER_LENGTH);
        return false;
    }
    if (callbacks->tickle_struct_size > (size_t)tt_MAX_BUFFER_LENGTH) {
        RMW_SET_ERROR_MSG_WITH_FORMAT_STRING(
            "type '%s' needs %zu bytes at its largest (every field at capacity), more than one %d-byte datagram - "
            "rmw_tickle cannot carry it; lower its capacities or raise tt_MAX_BUFFER_LENGTH",
            callbacks->ros_type_name, callbacks->tickle_struct_size, tt_MAX_BUFFER_LENGTH);
        return false;
    }
    return true;
}

bool rmw_tickle_check_topic_callbacks_usable(const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks) {
    if (callbacks->tickle_struct_size <= (size_t)tt_MAX_BUFFER_LENGTH) {
        return rmw_tickle_check_callbacks_usable(callbacks);
    }
    // Large-message stage 2 (DESIGN.md section 8): a topic's message may be larger than a datagram - a fixed 1 MB
    // array as much as an unbounded sequence - up to RMW_TICKLE_MAX_SAMPLE_BYTES. Services keep the datagram bound
    // (rmw_tickle_check_callbacks_usable()). The generator-version check is the same.
    if (0 != callbacks->tickle_max_buffer_length &&
        (size_t)tt_MAX_BUFFER_LENGTH != callbacks->tickle_max_buffer_length) {
        return rmw_tickle_check_callbacks_usable(callbacks); // sets its own error
    }
    size_t limit = (size_t)rmw_tickle_max_sample_bytes();
    if (callbacks->tickle_struct_size > limit) {
        RMW_SET_ERROR_MSG_WITH_FORMAT_STRING(
            "type '%s' needs %zu bytes at its largest (every field at capacity), more than RMW_TICKLE_MAX_SAMPLE_BYTES "
            "(%zu) - rmw_tickle cannot carry it; lower its capacities or raise RMW_TICKLE_MAX_SAMPLE_BYTES",
            callbacks->ros_type_name, callbacks->tickle_struct_size, limit);
        return false;
    }
    return true;
}

#define RMW_TICKLE_CACHE_BYTES_DEFAULT (1024ULL * 1024ULL)
// 512 KiB: the same order as CycloneDDS's own default bound on what a reliable writer holds
// unacknowledged - its WhcHigh watermark is 500 kB (read from the installed libddsc 11.0.1's own
// configuration defaults, 2026-09-25, not recalled). Measured against it at 2800-byte samples,
// TickLE's unbudgeted KEEP_ALL held up to the whole 1024-sample ack window, ~2.9 MB.
//
// What the number rests on if that anchor moves: a KEEP_ALL budget is how long a writer may keep
// sending while no acknowledgement arrives, measured in bytes - link rate times the longest ack stall
// worth riding out. 512 KiB is ~42ms at the 100 Mbit/s the rig runs, and ~420ms at the 10 Mbit/s of
// 10BASE-T1S, TickLE's own target. Re-derive from that, not from whatever the vendor ships next.
#define RMW_TICKLE_KEEP_ALL_BYTES_DEFAULT (512ULL * 1024ULL)

// 512 KiB again, and for the reader's own reason rather than by copying the writer's. This is the
// bound on what one KEEP_ALL subscription may hold for an application that has not taken it, and
// what it buys is the length of a take-side stall the reader can absorb without pushing back on its
// writers: 512 KiB is ~180 samples of a 2800-byte type, or ~340 of a 1500-byte one. Past it a
// RELIABLE reader declines and the writer holds the sample (tt_Subscriber.accept_callback), and a
// BEST_EFFORT one drops it and counts it, because BEST_EFFORT has nothing to hold it with.
//
// Why not unbounded, when KEEP_ALL is often read that way: in DDS, KEEP_ALL is bounded by
// RESOURCE_LIMITS, and what separates it from KEEP_LAST is not capacity but what a full cache does
// - KEEP_LAST overwrites the oldest unread sample and KEEP_ALL refuses to. That is the promise
// rosbag2 needs and it is keepable in bounded memory (RMW_GAPS_PLAN.md g13).
#define RMW_TICKLE_READER_KEEP_ALL_BYTES_DEFAULT (512ULL * 1024ULL)

// A byte budget from the environment, or `fallback` when unset, malformed or out of range - a
// malformed tuning knob must not stop a node starting.
static unsigned long long env_bytes_or(const char* name, unsigned long long fallback) {
    const char* env = getenv(name);
    if (NULL == env || '\0' == env[0]) {
        return fallback;
    }
    char* end = NULL;
    unsigned long long value = strtoull(env, &end, 10);
    if (end == env || (end != NULL && '\0' != *end) || value == 0 || value > UINT32_MAX) {
        return fallback;
    }
    return value;
}

unsigned long long rmw_tickle_cache_budget_bytes(void) {
    return env_bytes_or("RMW_TICKLE_CACHE_BYTES", RMW_TICKLE_CACHE_BYTES_DEFAULT);
}

unsigned long long rmw_tickle_keep_all_budget_bytes(void) {
    return env_bytes_or("RMW_TICKLE_KEEP_ALL_BYTES", RMW_TICKLE_KEEP_ALL_BYTES_DEFAULT);
}

unsigned long long rmw_tickle_reader_keep_all_budget_bytes(void) {
    return env_bytes_or("RMW_TICKLE_READER_KEEP_ALL_BYTES", RMW_TICKLE_READER_KEEP_ALL_BYTES_DEFAULT);
}

uint32_t rmw_tickle_message_slot_bytes(const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks,
                                       size_t framing) {
    unsigned long long bytes = (unsigned long long)framing + (unsigned long long)tt_MAX_BUFFER_LENGTH;
    if (NULL != callbacks && ROSIDL_TYPESUPPORT_TICKLE_C_ENCODED_SIZE_UNBOUNDED != callbacks->tickle_max_encoded_size) {
        bytes = (unsigned long long)framing + (unsigned long long)callbacks->tickle_max_encoded_size;
    }
    if (bytes > (unsigned long long)tt_MAX_BUFFER_LENGTH) {
        bytes = (unsigned long long)tt_MAX_BUFFER_LENGTH; // no submessage can be larger than its datagram
    }
    return (uint32_t)RMW_TICKLE_ROUND_UP_8(bytes);
}

bool rmw_tickle_type_can_loan(const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks) {
    if (0 == callbacks->inplace_bytes || callbacks->inplace_bytes > callbacks->ros_struct_size ||
        callbacks->inplace_bytes > (size_t)tt_MAX_BUFFER_LENGTH) {
        return false; // not a type whose wire bytes are its message (a hand-written struct, or one that is not plain)
    }
    size_t align = callbacks->ros_struct_align;
    // A loan's buffer comes from the allocator, which aligns for any scalar; a wider demand is not one it can meet.
    if (0 == align || (align & (align - 1)) != 0 || align > _Alignof(max_align_t)) {
        return false;
    }
    const char* env = getenv("RMW_TICKLE_LOANS");
    return NULL == env || 0 != strcmp(env, "0");
}

void* rmw_tickle_ros_message_create(const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks,
                                    const rcutils_allocator_t* allocator) {
    void* ros_message = allocator->zero_allocate(1, callbacks->ros_struct_size, allocator->state);
    if (NULL != ros_message && NULL != callbacks->ros_init) {
        callbacks->ros_init(ros_message);
    }
    return ros_message;
}

void rmw_tickle_ros_message_destroy(const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks, void* ros_message,
                                    const rcutils_allocator_t* allocator) {
    if (NULL == ros_message) {
        return;
    }
    if (NULL != callbacks->ros_fini) {
        callbacks->ros_fini(ros_message);
    }
    allocator->deallocate(ros_message, allocator->state);
}

void rmw_tickle_ros_message_move(const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks, void* dst,
                                 void* src) {
    if (NULL != callbacks->ros_move) {
        callbacks->ros_move(dst, src);
        return;
    }
    // A C message: its owned buffers change hands with the pointers, so src must stop pointing at
    // them. Clearing it here, rather than leaving that to each caller, is what lets a service's
    // request storage be filled again safely - until 2026-09-25 it was not cleared after a take,
    // and the next request's rosidl_runtime_c__String__assign() reallocated a buffer the caller
    // of the previous take already owned.
    memcpy(dst, src, callbacks->ros_struct_size);
    memset(src, 0, callbacks->ros_struct_size);
}

bool rmw_tickle_get_service_callbacks(const rosidl_service_type_support_t* type_support, const char* what,
                                      const char* name, rmw_tickle_service_typesupport_t* out) {
    if (NULL == type_support) {
        RMW_SET_ERROR_MSG("type_support is null");
        return false;
    }

    // The C++ identifier first, as rmw_tickle_get_message_callbacks() above does and for the same
    // reason: rclcpp's services (a default Node's type description and parameter services among
    // them) start from rosidl_typesupport_cpp's dispatch, which only knows rosidl_typesupport_tickle_
    // cpp. Asking it for the C identifier finds nothing, and every rclcpp::Node failed to start here
    // once its message types were available. rosidl_typesupport_tickle_cpp's service handle carries
    // the C++ Request/Response handles, which rmw_tickle_get_message_callbacks() resolves the same way.
    const rosidl_service_type_support_t* ours =
        get_service_typesupport_handle(type_support, rosidl_typesupport_tickle_cpp__identifier);
    if (NULL == ours) {
        rmw_reset_error();
        ours = get_service_typesupport_handle(type_support, rosidl_typesupport_tickle_c__identifier);
    }
    if (NULL == ours) {
        // Same reasoning as rmw_tickle_get_message_callbacks()'s own NULL case - could be a real
        // mismatch (a service using a request/response with a nested field - not yet supported)
        // or simply this interface package never having find_package()-d rosidl_typesupport_
        // tickle_c before calling rosidl_generate_interfaces().
        rmw_reset_error(); // as above
        RMW_SET_ERROR_MSG_WITH_FORMAT_STRING("no " RMW_TICKLE_IDENTIFIER
                                             " typesupport for the type of %s '%s' - was its package built with "
                                             "rosidl_typesupport_tickle_c?",
                                             what, name);
        return false;
    }

    const rosidl_typesupport_tickle_c_message_callbacks_t* request =
        rmw_tickle_get_message_callbacks(ours->request_typesupport, what, name);
    if (NULL == request || !rmw_tickle_check_callbacks_usable(request)) {
        return false; // error message already set
    }
    const rosidl_typesupport_tickle_c_message_callbacks_t* response =
        rmw_tickle_get_message_callbacks(ours->response_typesupport, what, name);
    if (NULL == response || !rmw_tickle_check_callbacks_usable(response)) {
        return false; // error message already set
    }

    out->service = (const rosidl_typesupport_tickle_c_service_callbacks_t*)ours->data;
    out->request = request;
    out->response = response;
    return true;
}
