/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

#include <stdbool.h>
#include <stddef.h>

#include "rmw/error_handling.h"
#include "rmw_tickle_c/rmw_tickle.h"
#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_runtime_c/service_type_support_struct.h"
#include "rosidl_typesupport_tickle_c/identifier.h"
#include "rosidl_typesupport_tickle_c/message_type_support.h"
#include "rosidl_typesupport_tickle_c/service_type_support.h"

const rosidl_typesupport_tickle_c_message_callbacks_t*
rmw_tickle_get_message_callbacks(const rosidl_message_type_support_t* type_support) {
    if (NULL == type_support) {
        RMW_SET_ERROR_MSG("type_support is null");
        return NULL;
    }

    const rosidl_message_type_support_t* ours =
        get_message_typesupport_handle(type_support, rosidl_typesupport_tickle_c__identifier);
    if (NULL == ours) {
        // Not a message this rmw_tickle_c build error - could be a real mismatch (a message that
        // uses a nested field, or a .srv - rosidl_typesupport_tickle_c doesn't generate a
        // typesupport for either yet, see its own PLAN.md notes) or simply this interface
        // package's own CMakeLists.txt never having find_package()-d rosidl_typesupport_tickle_c
        // before calling rosidl_generate_interfaces().
        RMW_SET_ERROR_MSG("no " RMW_TICKLE_IDENTIFIER " typesupport for this message type - "
                          "was it generated by rosidl_typesupport_tickle_c?");
        return NULL;
    }

    return (const rosidl_typesupport_tickle_c_message_callbacks_t*)ours->data;
}

bool rmw_tickle_get_service_callbacks(const rosidl_service_type_support_t* type_support,
                                      rmw_tickle_service_typesupport_t* out) {
    if (NULL == type_support) {
        RMW_SET_ERROR_MSG("type_support is null");
        return false;
    }

    const rosidl_service_type_support_t* ours =
        get_service_typesupport_handle(type_support, rosidl_typesupport_tickle_c__identifier);
    if (NULL == ours) {
        // Same reasoning as rmw_tickle_get_message_callbacks()'s own NULL case - could be a real
        // mismatch (a service using a request/response with a nested field - not yet supported)
        // or simply this interface package never having find_package()-d rosidl_typesupport_
        // tickle_c before calling rosidl_generate_interfaces().
        RMW_SET_ERROR_MSG("no " RMW_TICKLE_IDENTIFIER " typesupport for this service type - "
                          "was it generated by rosidl_typesupport_tickle_c?");
        return false;
    }

    const rosidl_typesupport_tickle_c_message_callbacks_t* request =
        rmw_tickle_get_message_callbacks(ours->request_typesupport);
    if (NULL == request) {
        return false; // error message already set
    }
    const rosidl_typesupport_tickle_c_message_callbacks_t* response =
        rmw_tickle_get_message_callbacks(ours->response_typesupport);
    if (NULL == response) {
        return false; // error message already set
    }

    out->service = (const rosidl_typesupport_tickle_c_service_callbacks_t*)ours->data;
    out->request = request;
    out->response = response;
    return true;
}
