/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

#include "rmw/error_handling.h"
#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_typesupport_tickle_c/identifier.h"
#include "rmw_tickle_c/rmw_tickle.h"

const rosidl_typesupport_tickle_c_message_callbacks_t*
rmw_tickle_get_message_callbacks(const rosidl_message_type_support_t* type_support) {
    if (NULL == type_support) {
        RMW_SET_ERROR_MSG("type_support is null");
        return NULL;
    }

    const rosidl_message_type_support_t* ours =
        get_message_typesupport_handle(type_support, rosidl_typesupport_tickle_c__identifier);
    if (NULL == ours) {
        // Not a message this rmw_tickle_c build error - could be a real mismatch (a message that
        // uses a nested field, or a .srv - rosidl_typesupport_tickle_c doesn't generate a
        // typesupport for either yet, see its own PLAN.md notes) or simply this interface
        // package's own CMakeLists.txt never having find_package()-d rosidl_typesupport_tickle_c
        // before calling rosidl_generate_interfaces().
        RMW_SET_ERROR_MSG(
            "no " RMW_TICKLE_IDENTIFIER " typesupport for this message type - "
            "was it generated by rosidl_typesupport_tickle_c?");
        return NULL;
    }

    return (const rosidl_typesupport_tickle_c_message_callbacks_t*)ours->data;
}
