/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// The one string every generated <pkg>__<subfolder>__<Name>__type_support.cpp's
// rosidl_message_type_support_t sets as its own .typesupport_identifier, and the same string
// this package registers as an ament_index "rosidl_typesupport_cpp" resource (see this package's
// own CMakeLists.txt) - together, what lets rclcpp's own top-level "rosidl_typesupport_cpp"
// dispatch (built from every package registered that way - see package.xml's own doc comment)
// ever reach a message generated by rosidl_typesupport_tickle_c at all.
extern const char* rosidl_typesupport_tickle_cpp__identifier;

#ifdef __cplusplus
}
#endif
