/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

#pragma once

// pthread_t/pthread_mutex_t/pthread_cond_t below are declared through a private glibc header
// reached transitively via this one (misc-include-cleaner attributes them there instead of to
// pthread.h itself) - same class of system-header quirk as hal_linux.c's own EINTR/POLLIN NOLINTs.
#include <pthread.h> // NOLINT(misc-include-cleaner)
#include <stdatomic.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h> // strcmp() - rmw_tickle_identifier_matches(), below

#include <tickle/tickle.h>

#include "rcutils/allocator.h"
#include "rmw/init.h"      // rmw_context_t
#include "rmw/ret_types.h" // rmw_ret_t
#include "rmw/types.h"     // rmw_node_t, rmw_publisher_t, rmw_subscription_t, rmw_client_t,
                           // rmw_service_t, rmw_guard_condition_t, rmw_wait_set_t, rmw_qos_profile_t
#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_runtime_c/service_type_support_struct.h"
#include "rosidl_typesupport_tickle_c/message_type_support.h" // rosidl_typesupport_tickle_c_message_callbacks_t
#include "rosidl_typesupport_tickle_c/service_type_support.h" // rosidl_typesupport_tickle_c_service_callbacks_t

#ifdef __cplusplus
extern "C" {
#endif

// TickLE RMW implementation identifier
#define RMW_TICKLE_IDENTIFIER "rmw_tickle"

// TickLE serialization format
#define RMW_TICKLE_SERIALIZATION_FORMAT "tickle"

// External identifier variables
extern const char* const rmw_tickle_identifier;
extern const char* const rmw_tickle_serialization_format;

// Every rmw_*_t entity's own implementation_identifier field (rmw_node_t, rmw_publisher_t, ...)
// is NULL on a caller-supplied zero-initialized struct - a real, expected caller mistake rmw's
// own contract requires rejecting cleanly (test_rmw_implementation's own *_with_bad_arguments
// tests across test_create_destroy_node.cpp/test_publisher.cpp/test_subscription.cpp/etc.
// construct exactly this), not something a bare strcmp() can safely be handed. Every rmw_tickle
// source file's own `strcmp(x->implementation_identifier, RMW_TICKLE_IDENTIFIER) != 0` identifier
// check should go through this instead of a bare strcmp().
static inline bool rmw_tickle_identifier_matches(const char* identifier) {
    return NULL != identifier && strcmp(identifier, RMW_TICKLE_IDENTIFIER) == 0;
}

// Shared by rmw_publisher.c/rmw_subscription.c/rmw_serialize.c (src/rmw_typesupport.c): resolves
// a real ROS 2 rosidl_message_type_support_t* down to rosidl_typesupport_tickle_c's own callback
// struct, via the same standard get_message_typesupport_handle() dispatch chain rmw_tickle/
// PLAN.md's Milestone 1(c) proved reachable. Returns NULL and sets an rmw error message (via
// RMW_SET_ERROR_MSG) if type_support wasn't generated by rosidl_typesupport_tickle_c at all (e.g.
// a .msg with a nested field, not yet supported - see rosidl_typesupport_tickle_c/PLAN.md notes) -
// never asserts/crashes on a mismatched type_support the way the lower-level dispatch functions
// themselves might.
const rosidl_typesupport_tickle_c_message_callbacks_t*
rmw_tickle_get_message_callbacks(const rosidl_message_type_support_t* type_support);

// The service-level counterpart, for rmw_client.c/rmw_service.c (Milestone 4) - bundles the one
// rmw_tickle_get_message_callbacks() lookup per side plus the service's own callbacks (just its
// ros_type_name - see rosidl_typesupport_tickle_c/service_type_support.h) into the three pieces
// building a struct tt_Service (rmw_tickle_client_t/rmw_tickle_service_t's own, below) needs.
// Returns false (+ RMW_SET_ERROR_MSG) on the same failure conditions rmw_tickle_get_message_
// callbacks() has - `*out` is left untouched in that case.
typedef struct rmw_tickle_service_typesupport_t {
    const rosidl_typesupport_tickle_c_service_callbacks_t* service;
    const rosidl_typesupport_tickle_c_message_callbacks_t* request;
    const rosidl_typesupport_tickle_c_message_callbacks_t* response;
} rmw_tickle_service_typesupport_t;

bool rmw_tickle_get_service_callbacks(const rosidl_service_type_support_t* type_support,
                                      rmw_tickle_service_typesupport_t* out);

// rmw_create_publisher()/_subscription()/_client()/_service() each pass their own kind so rmw_
// tickle_validate_qos_profile() can tell a topic (Publisher/Subscriber - no retry mechanism of any
// kind) from a service/client (TickLE's own tt_Client_call() already retries up to tt_CALL_RETRY_
// COUNT times, tt_CALL_RETRY_INTERVAL apart) - see that function's own comment on RELIABILITY for
// why the distinction matters.
typedef enum rmw_tickle_entity_kind_t {
    RMW_TICKLE_ENTITY_PUBLISHER,
    RMW_TICKLE_ENTITY_SUBSCRIPTION,
    RMW_TICKLE_ENTITY_SERVICE_OR_CLIENT,
} rmw_tickle_entity_kind_t;

// rmw_tickle/PLAN.md's Milestone 7: shared by rmw_create_publisher()/_subscription()/_client()/
// _service() - rejects (RMW_RET_UNSUPPORTED + RMW_SET_ERROR_MSG) any QoS policy the "QoS roadmap"
// table (PLAN.md) hasn't implemented yet, rather than silently ignoring it the way every create
// function did through Milestone 6.
rmw_ret_t rmw_tickle_validate_qos_profile(const rmw_qos_profile_t* qos_profile, rmw_tickle_entity_kind_t entity_kind);

// Forward reference only (pointer field below) - rmw_tickle_context_impl_t's own full definition
// needs rmw_tickle_guard_condition_t to already be complete (it embeds one), so the two are
// declared in this order rather than the other way around.
typedef struct rmw_tickle_context_impl_t rmw_tickle_context_impl_t;

// TickLE specific guard condition data. Shared by rmw_guard_condition.c's own rmw_create_guard_
// condition() (heap-allocated, one per rmw_create_guard_condition() call) and rmw_init()'s
// context_impl.graph_guard_condition (embedded, one per context) - rmw_wait_set.c's rmw_wait()
// treats both identically since they're the same struct shape either way.
typedef struct rmw_tickle_guard_condition_t {
    rmw_guard_condition_t rmw_guard_condition; // RMW guard condition structure (must be first)
    rmw_tickle_context_impl_t* context_impl;   // to reach wait_mutex/wait_cond below on trigger
    // atomic rather than mutex-guarded: rmw_trigger_guard_condition() only ever needs to set it,
    // and rmw_wait()'s own check-then-clear (a guard condition is edge-triggered - observing it
    // ready in one rmw_wait() call consumes it, so the next one blocks again until retriggered) is
    // a single atomic_exchange(), needing no separate lock of its own.
    atomic_bool has_triggered;
    rcutils_allocator_t allocator;
} rmw_tickle_guard_condition_t;

// TickLE context implementation
struct rmw_tickle_context_impl_t {
    // Wired up so a wait set can safely include it without crashing (Milestone 5) - actually
    // *triggered* on a real graph change only from Milestone 6 onward (0(c)'s discovery callback);
    // until then it simply never fires on its own, same as a graph that never changes would look.
    rmw_tickle_guard_condition_t graph_guard_condition;

    // Milestone 5's own single condition variable, shared by every waitable entity belonging to
    // this context (subscriber queues, client responses, service requests, guard conditions) -
    // see rmw_wait_set.c's own module doc comment for the multi-lock design this enables: a
    // producer (subscriber_callback() et al.) updates its own entity-local state under its own
    // fine-grained lock, *then* briefly takes wait_mutex just to broadcast wait_cond: since rmw_
    // wait() holds wait_mutex continuously across its own check-every-entity pass and into
    // pthread_cond_timedwait() itself, a producer's broadcast can never land in the gap between
    // the waiter's last check and it actually starting to wait (the classic lost-wakeup race) -
    // the producer's attempt to lock wait_mutex simply blocks until the waiter reaches the wait
    // call, at which point the broadcast is guaranteed to be observed.
    pthread_mutex_t wait_mutex; // NOLINT(misc-include-cleaner) - see this file's own <pthread.h> comment
    pthread_cond_t wait_cond;   // NOLINT(misc-include-cleaner)

    // rmw's own lifecycle contract (rmw_init.c's rmw_shutdown()/rmw_context_fini()): shutdown must
    // be called before finalization, shutdown itself is idempotent (calling it twice succeeds),
    // and finalizing an already-finalized or never-shut-down context must fail cleanly rather than
    // silently double-freeing - test_rmw_implementation's own test_init_shutdown.cpp exercises all
    // of this directly. false until rmw_shutdown() sets it.
    bool shutdown;
};

// TickLE specific node data
typedef struct rmw_tickle_node_t {
    rmw_node_t rmw_node; // RMW node structure (must be first)
    struct tt_Node tickle_node;
    rcutils_allocator_t allocator;
    const rmw_context_t* context; // Store context reference

    // rmw_tickle/PLAN.md's threading model ("TickLE" row: "Stays single-threaded per tt_Node...";
    // "rmw_tickle" row: "Owns all lock/thread management. A background thread per node drives
    // tt_Node_poll(); a per-node mutex serializes every other entry point (rmw_publish, ...)
    // against it"). poll_thread loops tt_Node_poll(&tickle_node, tt_RECEIVE_TIMEOUT), holding
    // `mutex` only around each individual call (not across iterations, and not while blocked in
    // the syscall underneath it for longer than that short timeout - see rmw_node.c) - every
    // other rmw_tickle_c entry point that touches tickle_node (rmw_publish() et al., Milestone
    // 3+) must tt_Node_interrupt(&tickle_node) *then* lock `mutex` before doing so, the same
    // pattern rmw_destroy_node() itself uses to stop poll_thread. tt_Node_interrupt() is the one
    // tt_Node_* call explicitly safe to make without holding `mutex` first (see tickle.h's own
    // doc comment on it).
    pthread_t poll_thread; // NOLINT(misc-include-cleaner) - see this file's own <pthread.h> comment
    pthread_mutex_t mutex; // NOLINT(misc-include-cleaner)
    volatile bool poll_thread_running;

    // rmw_tickle/PLAN.md's Milestone 6: opts this node into TickLE's own opt-in graph
    // introspection (tt_Node_set_discovery(), Milestone 0(c)) - every remote Publisher/Subscriber/
    // Client/Server this node hears announced, for rmw_count_publishers()/_subscribers()/rmw_
    // service_server_is_available() (rmw_graph.c) to scan. Embedded rather than heap-allocated,
    // matching struct tt_Discovery's own doc comment ("owned by the caller, e.g. embedded in an
    // rmw wrapper's own node struct") - zero_allocate() above already satisfies tt_Node_set_
    // discovery()'s own "must already be zeroed" precondition. Records only *remote* entities
    // (other nodes' announces) - this node's own locally-created endpoints are counted separately,
    // straight from tickle_node.endpoints[] (see rmw_graph.c's own count_matching()).
    struct tt_Discovery discovery;
} rmw_tickle_node_t;

// rmw_graph.c's own count_matching()'s core scan, exposed lock-free for QoS roadmap #3
// (LIVELINESS)'s own RMW_EVENT_LIVELINESS_CHANGED periodic check (rmw_subscription.c) to call
// directly. That check runs from a tt_Node_schedule() callback, which fires from *inside*
// tt_Node_poll() - already called with node_impl->mutex held by poll_thread (rmw_tickle_node_t's
// own doc comment above) - so it must NOT take that mutex itself the way count_matching() (used
// by rmw_count_publishers()/_subscribers(), called from an arbitrary application thread) does;
// doing so would self-deadlock (mutex is a plain, non-recursive pthread_mutex_t - rmw_node.c's
// own rmw_create_node()). Never call this from anywhere except the poll thread itself.
size_t rmw_tickle_count_matching_locked(rmw_tickle_node_t* node_impl, const char* topic_name, uint8_t kind);

// count_matching_locked()'s own tombstone counterpart (rmw_graph.c) - how many Publishers/
// Subscriptions on this topic are currently known but presumed dead (struct tt_DiscoveredEntity.
// alive's own doc comment, tickle.h), not the "currently active" count rmw_tickle_count_matching_
// locked() above answers. Same threading rule as that function - poll-thread-only, no locking of
// its own.
size_t rmw_tickle_count_not_alive_matching_locked(rmw_tickle_node_t* node_impl, const char* topic_name, uint8_t kind);

// QoS roadmap #2 (DEADLINE) + #3 (LIVELINESS) - shared by every status this rmw tracks below.
// total_count: cumulative, atomic (rmw_take_event(), rmw_event.c, reads it; only ever incremented,
// always from the poll thread's own scheduled check - see rmw_publisher.c/rmw_subscription.c).
// unread_count: how much of total_count hasn't been reported via rmw_take_event() yet -
// atomic_exchange(0) there (that call's own *_count_change), atomic_load-only peek for rmw_wait()
// readiness (rmw_wait_set.c's own check_events()) - same peek(never mutates)-vs-finalize(consumes)
// split check_guard_conditions() already established; a peek must never consume, since rmw_wait()
// itself doesn't drain an event the way a separate rmw_take_event() call does (mirrors rmw_wait()
// peeking rmw_tickle_subscriber_t.queue_count, never popping it - only rmw_take() does that).
typedef struct rmw_tickle_event_status_t {
    atomic_int total_count;
    atomic_int unread_count;
} rmw_tickle_event_status_t;

// RMW_EVENT_LIVELINESS_CHANGED's own status (rmw_subscription.c) - two fields wider than plain
// rmw_tickle_event_status_t above: alive_count/not_alive_count are live snapshots, not deltas.
typedef struct rmw_tickle_liveliness_changed_status_t {
    atomic_int alive_count;              // current count from rmw_tickle_count_matching_locked(), not
                                         // cumulative - read directly by rmw_take_event()
    atomic_int not_alive_count;          // current count from rmw_tickle_count_not_alive_matching_locked()
                                         // (tt_Discovery's own tombstones, tickle.h's struct tt_
                                         // DiscoveredEntity.alive) - likewise a live snapshot, not
                                         // cumulative; real data now, not always 0 (was, before that
                                         // tombstone concept existed)
    rmw_tickle_event_status_t alive;     // .total_count/.unread_count track alive_count_change
    rmw_tickle_event_status_t not_alive; // .total_count/.unread_count track not_alive_count_change
    int last_alive_count;                // plain, poll-thread-only - the periodic check's own previous reading
} rmw_tickle_liveliness_changed_status_t;

// TickLE specific publisher data
typedef struct rmw_tickle_publisher_t {
    rmw_publisher_t rmw_publisher; // RMW publisher structure (must be first)
    struct tt_Publisher tickle_publisher;
    // Owned by this publisher, must outlive tickle_publisher (tickle.h's "Lifetime / ownership" -
    // every struct passed to tt_Node_create_publisher() must stay valid and unmoved until
    // tt_Publisher_destroy()) - .name points at callbacks->ros_type_name, a generated code string
    // literal that outlives the whole process, so no separate storage/copy is needed for it.
    struct tt_Topic topic;
    rmw_tickle_node_t* node;
    const rosidl_message_type_support_t* type_support;
    const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks;
    rcutils_allocator_t allocator;
    // The qos_profile rmw_create_publisher() was given, after rmw_tickle_validate_qos_profile()
    // already accepted it - rmw_publisher_get_actual_qos() just returns this back verbatim, since
    // this rmw never negotiates/downgrades a QoS policy the way a real DDS vendor might.
    rmw_qos_profile_t qos;
    // QoS roadmap #5 (RELIABILITY) / #4 (DURABILITY) - NULL unless qos.reliability is RMW_QOS_
    // POLICY_RELIABILITY_RELIABLE and/or qos.durability is RMW_QOS_POLICY_DURABILITY_TRANSIENT_
    // LOCAL, in which case rmw_create_publisher() allocator->zero_allocate()s one (sized by
    // qos.depth, clamped to tt_MAX_RELIABLE_HISTORY) and points tickle_publisher.reliable_cache at
    // it, setting tickle_publisher.reliable/.durable to match whichever of the two was actually
    // requested - see struct tt_ReliableCache's own doc comment (tickle.h) for why one cache/one
    // depth cap now serves both policies (used to be two independently-allocated caches here,
    // struct tt_DurableCache, since removed - PLAN.md's Milestone 24). Freed in rmw_destroy_
    // publisher(); NULL is also this field's own "neither policy requested" sentinel. No matching
    // field exists on rmw_tickle_subscriber_t below (or on struct tt_Subscriber itself) for
    // durability specifically - it's purely a Publisher-side decision, a Subscription just
    // receives whatever backlog arrives.
    struct tt_ReliableCache* reliable_cache;

    // QoS roadmap #2 (DEADLINE) - deadline_period_ns == 0 (rmw_create_publisher()'s own default):
    // not requested, no tt_Node_schedule() entry ever armed, costs nothing. Non-zero: qos.deadline
    // in nanoseconds; last_activity_time (tt_get_ns() at creation, updated by rmw_publish() on
    // every successful send) is compared against it by a periodic scheduled check - see
    // rmw_publisher.c's own RMW_EVENT_OFFERED_DEADLINE_MISSED handling. Both fields are only ever
    // touched under node->mutex (rmw_publish() already holds it; the scheduled check runs from
    // inside tt_Node_poll(), which poll_thread also holds it around - rmw_tickle_node_t's own doc
    // comment) - deadline_missed's own counts are the only part read cross-thread, hence atomic.
    uint64_t deadline_period_ns;
    uint64_t last_activity_time;
    rmw_tickle_event_status_t deadline_missed;

    // QoS roadmap #3 (LIVELINESS) - RMW_EVENT_LIVELINESS_LOST. Always total_count == 0 - see
    // rmw_publisher.c's own rmw_publisher_event_init() doc comment for why this is a structural,
    // honest limitation (not a placeholder bug) rather than something a future pass would "finish".
    rmw_tickle_event_status_t liveliness_lost;
} rmw_tickle_publisher_t;

// rmw_tickle/PLAN.md's Milestone 3: rmw_take()'s own bounded queue, holding already-from_tickle()-
// converted, independently-owned ROS messages - see rmw_subscription.c's own subscriber_callback()
// doc comment for why the conversion can't be deferred to rmw_take() time. Milestone 7's QoS
// roadmap item #1 ("HISTORY/DEPTH") wires the *capacity* (rmw_tickle_subscriber_t.queue_capacity,
// below) to qos_profile->depth at rmw_create_subscription() time - this is just the fallback used
// when depth is RMW_QOS_POLICY_DEPTH_SYSTEM_DEFAULT (0, "unset"), matching ROS 2's own common
// default queue size.
#define RMW_TICKLE_SUBSCRIPTION_QUEUE_DEFAULT_DEPTH 10

typedef struct rmw_tickle_queued_message_t {
    void* ros_message; // callbacks->ros_struct_size bytes, allocator-owned
    uint64_t source_timestamp;
    uint64_t received_timestamp;
    uint64_t publication_sequence_number;
    uint64_t reception_sequence_number;
} rmw_tickle_queued_message_t;

// TickLE specific subscriber data
typedef struct rmw_tickle_subscriber_t {
    rmw_subscription_t rmw_subscription; // RMW subscription structure (must be first)
    struct tt_Subscriber tickle_subscriber;
    struct tt_Topic topic; // see rmw_tickle_publisher_t.topic's own comment
    rmw_tickle_node_t* node;
    const rosidl_message_type_support_t* type_support;
    const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks;
    rcutils_allocator_t allocator;

    // Guards queue*/reception_sequence_number below - separate from rmw_tickle_node_t.mutex since
    // subscriber_callback() (poll thread, already holding node->mutex) and rmw_take() (whichever
    // thread the application calls it from) both need this, and rmw_take() has no reason to wait
    // on the node mutex just to pop an already-queued message.
    pthread_mutex_t queue_mutex;
    // queue_capacity entries, allocator-owned - sized from qos_profile->depth at rmw_create_
    // subscription() time (Milestone 7's QoS roadmap item #1), not a fixed compile-time bound.
    rmw_tickle_queued_message_t* queue;
    size_t queue_capacity;
    size_t queue_head;
    size_t queue_count;
    uint64_t reception_sequence_number;
    // See rmw_tickle_publisher_t.qos's own doc comment - same reasoning, for rmw_subscription_
    // get_actual_qos().
    rmw_qos_profile_t qos;

    // QoS roadmap #2 (DEADLINE) - RMW_EVENT_REQUESTED_DEADLINE_MISSED. Same shape/threading as
    // rmw_tickle_publisher_t's own deadline_period_ns/last_activity_time/deadline_missed - see
    // their own doc comment - last_activity_time here is updated by subscriber_callback() (also
    // poll-thread, already under node->mutex) on every real received sample instead.
    uint64_t deadline_period_ns;
    uint64_t last_activity_time;
    rmw_tickle_event_status_t deadline_missed;

    // QoS roadmap #3 (LIVELINESS) - RMW_EVENT_LIVELINESS_CHANGED. liveliness_lease_ns == 0: no
    // periodic check has been started yet - rmw_subscription_event_init() starts it lazily
    // (idempotent) the first time this event type is actually requested, at either qos.liveliness_
    // lease_duration (if finite) or tt_LIVELINESS_MISS_THRESHOLD * tt_NODE_UPDATE_INTERVAL (rmw_
    // qos.c's own accepted floor - rechecking faster than that can never usefully change the
    // answer, since that's TickLE core's own fastest possible peer-death detection latency). See
    // rmw_subscription.c's own handling for the full mechanism, and rmw_tickle_liveliness_
    // changed_status_t's own doc comment (above) for what alive_count/not_alive_count can and
    // can't honestly report.
    uint64_t liveliness_lease_ns;
    rmw_tickle_liveliness_changed_status_t liveliness_changed;

    // QoS roadmap #6 (LIFESPAN) - 0 (zero_allocate() default): disabled, today's only behavior for
    // a Subscription that didn't request one. Non-zero: rmw_take_with_info() (rmw_subscription.c)
    // discards any queue[] entry whose source_timestamp is already this old before returning it -
    // "as if it had never been sent" (RMW_RET_OK, *taken = false, same as an empty queue), matching
    // tt_Publisher.lifespan_duration_ns's own reliable_cache-side wording exactly. Deliberately
    // independent of the Publisher's own lifespan_duration_ns (tickle.h) rather than negotiated
    // with it - both read the same underlying data_header->timestamp (already on the wire
    // regardless of either side's QoS, carried through to source_timestamp below), so a
    // Subscription can enforce its own age floor with no coordination needed.
    uint64_t lifespan_ns;
} rmw_tickle_subscriber_t;

// TickLE specific client data
typedef struct rmw_tickle_client_t {
    rmw_client_t rmw_client; // RMW client structure (must be first)
    struct tt_Client tickle_client;
    // .name is service_callbacks->ros_type_name (a generated-code string literal - see
    // rmw_tickle_publisher_t.topic's own doc comment for the identical reasoning applied there).
    struct tt_Service service;
    rmw_tickle_node_t* node;
    const rosidl_service_type_support_t* type_support;
    const rosidl_typesupport_tickle_c_message_callbacks_t* request_callbacks;
    const rosidl_typesupport_tickle_c_message_callbacks_t* response_callbacks;
    rcutils_allocator_t allocator;

    // rmw_send_request()/rmw_take_response() bridge (rmw_client.c) - TickLE's own tt_Client
    // supports exactly *one* outstanding call at a time (tt_Client_call() refuses a second call
    // while one is already pending - see tickle.h's own tt_Client doc comment); rmw_tickle
    // mirrors that limit directly (a real, documented gap versus full ROS 2 rmw semantics, which
    // allow several in-flight requests per client - see rmw_tickle/PLAN.md) rather than queueing.
    // Guards everything below - separate from `node`'s own mutex for the same reason rmw_tickle_
    // subscriber_t.queue_mutex is (the client_callback() below runs on the poll thread, already
    // holding node->mutex; rmw_take_response() - whichever thread the application calls it from -
    // has no reason to wait on that just to poll this one response slot).
    pthread_mutex_t response_mutex;
    bool response_ready;   // client_callback() has filled response_storage (or gave up)
    bool response_success; // false if the call timed out (tt_CALL_TIMEOUT) - response_storage
                           // wasn't touched in that case
    int64_t response_sequence_id;
    void* response_storage; // response_callbacks->ros_struct_size bytes, reused across calls
                            // (only one outstanding at a time - see above)
    int64_t next_sequence_id;
} rmw_tickle_client_t;

// TickLE specific service data
typedef struct rmw_tickle_service_t {
    rmw_service_t rmw_service; // RMW service structure (must be first)
    struct tt_Server tickle_server;
    struct tt_Service service; // see rmw_tickle_client_t.service's own doc comment
    rmw_tickle_node_t* node;
    const rosidl_service_type_support_t* type_support;
    const rosidl_typesupport_tickle_c_message_callbacks_t* request_callbacks;
    const rosidl_typesupport_tickle_c_message_callbacks_t* response_callbacks;
    rcutils_allocator_t allocator;

    // rmw_take_request()/rmw_send_response() bridge (rmw_service.c) - see server_callback()'s own
    // doc comment there for the full handoff. Since TickLE core's own tt_CALL_DEFERRED/tt_Server_
    // send_response() (Milestone 17) now separates "a request arrived" from "here's the answer"
    // for real, this only ever guards a plain producer/consumer handoff between server_callback()
    // (the poll thread) and rmw_take_request()/rmw_send_response() (whatever thread the ROS
    // executor uses) - no condition variable needed anymore, nothing here ever waits on the other
    // side. Still only one outstanding request at a time (mirroring rmw_tickle_client_t's own
    // same limit) - a deliberate, documented, unchanged scope boundary (Milestone 17), not
    // something this milestone tries to fix: server_callback() now rejects a second request
    // outright while one is still un-answered, rather than the old design's "the whole poll
    // thread is blocked so a second one can't even arrive" side effect.
    pthread_mutex_t request_mutex;
    bool request_available; // server_callback() has a request waiting for rmw_take_request()
    int64_t current_sequence_id;
    // The TickLE-level identity of the currently-available/in-flight request - server_callback()
    // sets it, rmw_send_response() reads it back to call tt_Server_send_response() with the right
    // one. Meaningless (and never read) once request_available goes false without a response
    // ever having been sent for it.
    tt_RequestId pending_request_id;
    // ROS-shaped (request_callbacks->ros_struct_size bytes) - server_callback() converts TickLE's
    // own request (aliasing node->rx_buffer, same DESIGN.md "Strings" concern as rmw_subscription.
    // c's subscriber_callback()) into this *before* rmw_take_request() can see it.
    void* request_storage;
    // TickLE-shaped (response_callbacks->tickle_struct_size bytes, not ros_struct_size - the
    // opposite direction from request_storage above) - rmw_send_response() converts the
    // application's ROS response into this scratch buffer, then hands it straight to tt_Server_
    // send_response(), which copies it into TickLE core's own pending-response slot immediately
    // (see that function's own doc comment) - this doesn't need to outlive that one call the way
    // it used to when server_callback() copied it back out itself, still waiting.
    void* response_storage;
    int64_t next_sequence_id;
} rmw_tickle_service_t;

// TickLE specific wait set data. Unlike a typical DDS-backed rmw, this doesn't need its own
// condition variable or any pre-sized entity storage - rmw_wait() (rmw_wait_set.c) waits directly
// on context_impl->wait_cond (shared by the one node/context this rmw currently supports - see
// PLAN.md's "Deferred: multiple ROS 2 nodes per process"), and the entity arrays it scans each
// call are owned and sized by rcl itself, not by this wait set. `max_conditions` (rmw_create_wait_
// set()'s own parameter) has nothing to size here for the same reason and is simply ignored.
typedef struct rmw_tickle_wait_set_t {
    rmw_wait_set_t rmw_wait_set; // RMW wait set structure (must be first)
    rmw_tickle_context_impl_t* context_impl;
    rcutils_allocator_t allocator;
} rmw_tickle_wait_set_t;

#ifdef __cplusplus
}
#endif
