/*
 * Copyright (c) 2025-2026 TSN Lab, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of TickLE. TickLE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3, as published by the Free
 * Software Foundation. A proprietary license is also available on request - see README.md.
 */

#pragma once

// pthread_t/pthread_mutex_t/pthread_cond_t below are declared through a private glibc header
// reached transitively via this one (misc-include-cleaner attributes them there instead of to
// pthread.h itself) - same class of system-header quirk as hal_linux.c's own EINTR/POLLIN NOLINTs.
#include <pthread.h> // NOLINT(misc-include-cleaner)
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <tickle/config.h> // tt_SECOND
#include <tickle/tickle.h>

#include "rcutils/allocator.h"
#include "rmw/init.h"  // rmw_context_t
#include "rmw/types.h" // rmw_node_t, rmw_publisher_t, rmw_subscription_t, rmw_client_t, rmw_service_t,
                       // rmw_guard_condition_t, rmw_wait_set_t
#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_runtime_c/service_type_support_struct.h"
#include "rosidl_typesupport_tickle_c/message_type_support.h" // rosidl_typesupport_tickle_c_message_callbacks_t
#include "rosidl_typesupport_tickle_c/service_type_support.h" // rosidl_typesupport_tickle_c_service_callbacks_t

#ifdef __cplusplus
extern "C" {
#endif

// TickLE RMW implementation identifier
#define RMW_TICKLE_IDENTIFIER "rmw_tickle"

// TickLE serialization format
#define RMW_TICKLE_SERIALIZATION_FORMAT "tickle"

// External identifier variables
extern const char* const rmw_tickle_identifier;
extern const char* const rmw_tickle_serialization_format;

// Shared by rmw_publisher.c/rmw_subscription.c/rmw_serialize.c (src/rmw_typesupport.c): resolves
// a real ROS 2 rosidl_message_type_support_t* down to rosidl_typesupport_tickle_c's own callback
// struct, via the same standard get_message_typesupport_handle() dispatch chain rmw_tickle/
// PLAN.md's Milestone 1(c) proved reachable. Returns NULL and sets an rmw error message (via
// RMW_SET_ERROR_MSG) if type_support wasn't generated by rosidl_typesupport_tickle_c at all (e.g.
// a .msg with a nested field, not yet supported - see rosidl_typesupport_tickle_c/PLAN.md notes) -
// never asserts/crashes on a mismatched type_support the way the lower-level dispatch functions
// themselves might.
const rosidl_typesupport_tickle_c_message_callbacks_t*
rmw_tickle_get_message_callbacks(const rosidl_message_type_support_t* type_support);

// The service-level counterpart, for rmw_client.c/rmw_service.c (Milestone 4) - bundles the one
// rmw_tickle_get_message_callbacks() lookup per side plus the service's own callbacks (just its
// ros_type_name - see rosidl_typesupport_tickle_c/service_type_support.h) into the three pieces
// building a struct tt_Service (rmw_tickle_client_t/rmw_tickle_service_t's own, below) needs.
// Returns false (+ RMW_SET_ERROR_MSG) on the same failure conditions rmw_tickle_get_message_
// callbacks() has - `*out` is left untouched in that case.
typedef struct rmw_tickle_service_typesupport_t {
    const rosidl_typesupport_tickle_c_service_callbacks_t* service;
    const rosidl_typesupport_tickle_c_message_callbacks_t* request;
    const rosidl_typesupport_tickle_c_message_callbacks_t* response;
} rmw_tickle_service_typesupport_t;

bool rmw_tickle_get_service_callbacks(const rosidl_service_type_support_t* type_support,
                                      rmw_tickle_service_typesupport_t* out);

// TickLE context implementation
typedef struct rmw_tickle_context_impl_t {
    // Graph guard condition for node discovery
    rmw_guard_condition_t graph_guard_condition;
    // Placeholder for TickLE context data
    // This can be extended with TickLE-specific context information
    int dummy; // Temporary field to avoid empty struct
} rmw_tickle_context_impl_t;

// TickLE specific node data
typedef struct rmw_tickle_node_t {
    rmw_node_t rmw_node; // RMW node structure (must be first)
    struct tt_Node tickle_node;
    rcutils_allocator_t allocator;
    const rmw_context_t* context; // Store context reference

    // rmw_tickle/PLAN.md's threading model ("TickLE" row: "Stays single-threaded per tt_Node...";
    // "rmw_tickle" row: "Owns all lock/thread management. A background thread per node drives
    // tt_Node_poll(); a per-node mutex serializes every other entry point (rmw_publish, ...)
    // against it"). poll_thread loops tt_Node_poll(&tickle_node, tt_RECEIVE_TIMEOUT), holding
    // `mutex` only around each individual call (not across iterations, and not while blocked in
    // the syscall underneath it for longer than that short timeout - see rmw_node.c) - every
    // other rmw_tickle_c entry point that touches tickle_node (rmw_publish() et al., Milestone
    // 3+) must tt_Node_interrupt(&tickle_node) *then* lock `mutex` before doing so, the same
    // pattern rmw_destroy_node() itself uses to stop poll_thread. tt_Node_interrupt() is the one
    // tt_Node_* call explicitly safe to make without holding `mutex` first (see tickle.h's own
    // doc comment on it).
    pthread_t poll_thread; // NOLINT(misc-include-cleaner) - see this file's own <pthread.h> comment
    pthread_mutex_t mutex; // NOLINT(misc-include-cleaner)
    volatile bool poll_thread_running;
} rmw_tickle_node_t;

// TickLE specific publisher data
typedef struct rmw_tickle_publisher_t {
    rmw_publisher_t rmw_publisher; // RMW publisher structure (must be first)
    struct tt_Publisher tickle_publisher;
    // Owned by this publisher, must outlive tickle_publisher (tickle.h's "Lifetime / ownership" -
    // every struct passed to tt_Node_create_publisher() must stay valid and unmoved until
    // tt_Publisher_destroy()) - .name points at callbacks->ros_type_name, a generated code string
    // literal that outlives the whole process, so no separate storage/copy is needed for it.
    struct tt_Topic topic;
    rmw_tickle_node_t* node;
    const rosidl_message_type_support_t* type_support;
    const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks;
    rcutils_allocator_t allocator;
} rmw_tickle_publisher_t;

// rmw_tickle/PLAN.md's Milestone 3 first cut: rmw_take()'s own bounded queue, holding already-
// from_tickle()-converted, independently-owned ROS messages - see rmw_subscription.c's own
// subscriber_callback() doc comment for why the conversion can't be deferred to rmw_take() time.
// A fixed capacity rather than something QoS depth (rmw_qos_profile_t.depth) actually drives -
// that's Milestone 7's QoS roadmap item #1 ("HISTORY/DEPTH - a bounded per-subscription queue"),
// not yet wired in; this is a placeholder KEEP_LAST-style depth matching ROS 2's own common
// default queue size until then.
#define RMW_TICKLE_SUBSCRIPTION_QUEUE_CAPACITY 10

typedef struct rmw_tickle_queued_message_t {
    void* ros_message; // callbacks->ros_struct_size bytes, allocator-owned
    uint64_t source_timestamp;
    uint64_t received_timestamp;
    uint64_t publication_sequence_number;
    uint64_t reception_sequence_number;
} rmw_tickle_queued_message_t;

// TickLE specific subscriber data
typedef struct rmw_tickle_subscriber_t {
    rmw_subscription_t rmw_subscription; // RMW subscription structure (must be first)
    struct tt_Subscriber tickle_subscriber;
    struct tt_Topic topic; // see rmw_tickle_publisher_t.topic's own comment
    rmw_tickle_node_t* node;
    const rosidl_message_type_support_t* type_support;
    const rosidl_typesupport_tickle_c_message_callbacks_t* callbacks;
    rcutils_allocator_t allocator;

    // Guards queue*/reception_sequence_number below - separate from rmw_tickle_node_t.mutex since
    // subscriber_callback() (poll thread, already holding node->mutex) and rmw_take() (whichever
    // thread the application calls it from) both need this, and rmw_take() has no reason to wait
    // on the node mutex just to pop an already-queued message.
    pthread_mutex_t queue_mutex;
    rmw_tickle_queued_message_t queue[RMW_TICKLE_SUBSCRIPTION_QUEUE_CAPACITY];
    size_t queue_head;
    size_t queue_count;
    uint64_t reception_sequence_number;
} rmw_tickle_subscriber_t;

// TickLE specific client data
typedef struct rmw_tickle_client_t {
    rmw_client_t rmw_client; // RMW client structure (must be first)
    struct tt_Client tickle_client;
    // .name is service_callbacks->ros_type_name (a generated-code string literal - see
    // rmw_tickle_publisher_t.topic's own doc comment for the identical reasoning applied there).
    struct tt_Service service;
    rmw_tickle_node_t* node;
    const rosidl_service_type_support_t* type_support;
    const rosidl_typesupport_tickle_c_message_callbacks_t* request_callbacks;
    const rosidl_typesupport_tickle_c_message_callbacks_t* response_callbacks;
    rcutils_allocator_t allocator;

    // rmw_send_request()/rmw_take_response() bridge (rmw_client.c) - TickLE's own tt_Client
    // supports exactly *one* outstanding call at a time (tt_Client_call() refuses a second call
    // while one is already pending - see tickle.h's own tt_Client doc comment); rmw_tickle
    // mirrors that limit directly (a real, documented gap versus full ROS 2 rmw semantics, which
    // allow several in-flight requests per client - see rmw_tickle/PLAN.md) rather than queueing.
    // Guards everything below - separate from `node`'s own mutex for the same reason rmw_tickle_
    // subscriber_t.queue_mutex is (the client_callback() below runs on the poll thread, already
    // holding node->mutex; rmw_take_response() - whichever thread the application calls it from -
    // has no reason to wait on that just to poll this one response slot).
    pthread_mutex_t response_mutex;
    bool response_ready;   // client_callback() has filled response_storage (or gave up)
    bool response_success; // false if the call timed out (tt_CALL_TIMEOUT) - response_storage
                           // wasn't touched in that case
    int64_t response_sequence_id;
    void* response_storage; // response_callbacks->ros_struct_size bytes, reused across calls
                            // (only one outstanding at a time - see above)
    int64_t next_sequence_id;
} rmw_tickle_client_t;

// rmw_service.c's own bridge (server_callback(), below) blocks the *whole node's* poll thread -
// not just this one service - between taking a request (rmw_take_request()) and the matching
// rmw_send_response(), because TickLE's own tt_SERVER_CALLBACK contract requires a response
// synchronously, before returning, with no separate "send it later" API of its own (rmw_tickle/
// PLAN.md's design philosophy keeps TickLE itself unmodified, so this is resolved entirely on the
// rmw_tickle side). Bounded rather than indefinite specifically so an application bug (a taken
// request whose handler never calls rmw_send_response() at all) degrades to "one slow/default
// response, node briefly unresponsive" rather than "poll thread wedged forever" - matches how
// quickly a synchronous rclcpp executor's own take-handle-send sequence normally completes, with
// generous headroom for a real handler's own work.
#define RMW_TICKLE_SERVICE_RESPONSE_TIMEOUT_NS (5 * tt_SECOND)

// TickLE specific service data
typedef struct rmw_tickle_service_t {
    rmw_service_t rmw_service; // RMW service structure (must be first)
    struct tt_Server tickle_server;
    struct tt_Service service; // see rmw_tickle_client_t.service's own doc comment
    rmw_tickle_node_t* node;
    const rosidl_service_type_support_t* type_support;
    const rosidl_typesupport_tickle_c_message_callbacks_t* request_callbacks;
    const rosidl_typesupport_tickle_c_message_callbacks_t* response_callbacks;
    rcutils_allocator_t allocator;

    // rmw_take_request()/rmw_send_response() bridge (rmw_service.c) - see server_callback()'s own
    // doc comment there for the full state machine this drives. Same single-outstanding-call
    // limit as rmw_tickle_client_t's own (mirroring TickLE's tt_Server, which likewise only ever
    // has one request in flight through a given server_callback() invocation at a time).
    pthread_mutex_t request_mutex;
    pthread_cond_t request_cond; // NOLINT(misc-include-cleaner) - see this file's own <pthread.h> comment
    bool request_available;      // server_callback() has a request waiting for rmw_take_request()
    bool response_ready;         // rmw_send_response() has filled response_storage for it
    int64_t current_sequence_id;
    // ROS-shaped (request_callbacks->ros_struct_size bytes) - server_callback() converts TickLE's
    // own request (aliasing node->rx_buffer, same DESIGN.md "Strings" concern as rmw_subscription.
    // c's subscriber_callback()) into this *before* rmw_take_request() can see it.
    void* request_storage;
    // TickLE-shaped (response_callbacks->tickle_struct_size bytes, not ros_struct_size - the
    // opposite direction from request_storage above) - rmw_send_response() converts the
    // application's ROS response into this; server_callback(), still waiting, then copies it
    // verbatim into TickLE's own response out-parameter once woken.
    void* response_storage;
    int64_t next_sequence_id;
} rmw_tickle_service_t;

// TickLE specific guard condition data
typedef struct rmw_tickle_guard_condition_t {
    rmw_guard_condition_t rmw_guard_condition; // RMW guard condition structure (must be first)
    bool has_triggered;
    rcutils_allocator_t allocator;
} rmw_tickle_guard_condition_t;

// TickLE specific wait set data
typedef struct rmw_tickle_wait_set_t {
    rmw_wait_set_t rmw_wait_set; // RMW wait set structure (must be first)
    rmw_tickle_guard_condition_t** guard_conditions;
    size_t guard_condition_count;
    rcutils_allocator_t allocator;
} rmw_tickle_wait_set_t;

#ifdef __cplusplus
}
#endif
