name: Check all

on:
  - push
  - pull_request

jobs:
  check-all:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install bear

      - name: Generate compile_commands.json
        run: |
          bear -- make all

      - name: Check all
        uses: tsnlab/check@main
        with:
          python_version: '3.12'
          github_token: ${{ secrets.GITHUB_TOKEN }}
